source: code/explore.cc File Reference
explore.cc File Reference
#include "ctype.h"
#include "errno.h"
#include "fcntl.h"
#include "libgen.h"
#include "limits.h"
#include "pthread.h"
#include "stdio.h"
#include "stdlib.h"
#include "string.h"
#include "termios.h"
#include "time.h"
#include "unistd.h"
#include "arpa/inet.h"
#include "sys/socket.h"
#include "sys/stat.h"
#include "sys/vfs.h"
Classes
struct ptr
struct mem
struct buf
struct txt
struct seq
struct map
struct grid
struct tbl
struct fd
struct pfile
struct pthread
struct timer
Functions
struct stat fs_stat (const mem &x)
bool accept (fd &x, fd &y)
void allocate (mem &x, const int y)
void append (mem &x, const mem &y)
void append (buf &x, const char *y)
void append (buf &x, const mem &y)
void append (buf &x, const buf &y)
void append (txt &x, const txt &y)
void append (seq &x, const seq &y)
void assign (mem &x, const char *y)
void assign (mem &x, const mem &y)
void assign (mem &x, const buf &y)
void assign (buf &x, const char *y)
void assign (buf &x, const buf &y)
void assign (txt &x, const txt &y)
void assign (seq &x, const seq &y)
void assign (map &x, const map &y)
char at (const mem &x, const int y)
char at (const buf &x, const int y)
mem at (const txt &x, const int y)
mem at (const seq &x, const int y)
char back (const mem &x)
char back (const mem &x, const int y)
void back (mem &x, const int y, const char z)
char back (const buf &x)
char back (const buf &x, const int y)
void back (buf &x, const int y, const char z)
mem back (const txt &x)
mem back (const seq &x)
void check (const bool x)
void clear (ptr &x)
void clear (mem &x)
void clear (buf &x)
void clear (txt &x)
void clear (seq &x)
void clear (fd &x)
void clear (pfile &x)
void clear (pthread &x)
void clear (map &x)
void clear (timer &x)
void clear (grid &x)
void clear (tbl &x)
mem compact (const mem &x)
mem concat (const mem &x, const mem &y)
mem concat (const mem &x, const mem &y, const mem &z)
mem concat (const mem &x, const mem &y, const mem &z, const mem &a)
mem concat (const mem &x, const mem &y, const mem &z, const mem &a, const mem &b)
mem concat (const mem &x, const mem &y, const mem &z, const mem &a, const mem &b, const mem &c)
mem concat (const mem &x, const mem &y, const mem &z, const mem &a, const mem &b, const mem &c, const mem &d)
mem concat (const mem &x, const mem &y, const mem &z, const mem &a, const mem &b, const mem &c, const mem &d, const mem &e)
mem concat (const mem &x, const mem &y, const mem &z, const mem &a, const mem &b, const mem &c, const mem &d, const mem &e, const mem &f)
mem concat (const mem &x, const mem &y, const mem &z, const mem &a, const mem &b, const mem &c, const mem &d, const mem &e, const mem &f, const mem &g)
mem concat (const mem &x, const mem &y, const mem &z, const mem &a, const mem &b, const mem &c, const mem &d, const mem &e, const mem &f, const mem &g, const mem &h)
bool contain (const mem &x, const char y)
bool contain (const mem &x, const mem &y)
bool contain (const txt &x, const mem &y)
bool contain (const seq &x, const mem &y)
void copy (ptr &x, const int y, const int z, const int a)
void copy (mem &x, const int y, const int z, const int a)
void copy (ptr &x, const int y, const ptr &z, const int a, const int b)
void copy (mem &x, const int y, const mem &z, const int a, const int b)
void copy (buf &x, const int y, const mem &z, const int a, const int b)
void copy (mem &x, const int y, const buf &z, const int a, const int b)
void copy (buf &x, const int y, const buf &z, const int a, const int b)
int count (const mem &x, const char y)
int count (const buf &x, const char y)
int count (const txt &x)
int count (const seq &x)
int count (const map &x)
void create (pthread &x, void(*y)(const map &), const map &z)
void * on_create (void *x)
mem decode (const mem &x)
seq delimit (const mem &x)
void deserialize (txt &x, const mem &y)
void deserialize (map &x, const mem &y)
void destruct (mem &x)
void destruct (fd &x)
void destruct (pfile &x)
void destruct (pthread &x)
ptr detach (ptr &x)
ptr detach (mem &x)
mem detach (buf &x)
void dim (buf &x, const int y)
void dir_change (const mem &x)
void dir_clean (const mem &x)
void dir_copy (const mem &x, const mem &y)
mem dir_current ()
txt dir_find (const mem &x)
txt dir_list (const mem &x)
mem dir_locate (const mem &x)
void dir_make (const mem &x)
void dir_remove (const mem &x)
void dir_reset (const mem &x)
long disk_free ()
long disk_size ()
long disk_usage ()
void drop_l (mem &x)
void drop_l (mem &x, const int y)
void drop_l (buf &x)
void drop_l (buf &x, const int y)
void drop_l (txt &x)
void drop_l (seq &x)
void drop_l (txt &x, const int y)
void drop_l (seq &x, const int y)
void drop_r (mem &x)
void drop_r (mem &x, const int y)
void drop_r (buf &x)
void drop_r (buf &x, const int y)
void drop_r (txt &x)
void drop_r (seq &x)
void drop_r (txt &x, const int y)
void drop_r (seq &x, const int y)
void dump (const bool x)
void dump (const char x)
void dump (const int x)
void dump (const unsigned x)
void dump (const long x)
void dump (const unsigned long x)
void dump (const double x)
void dump (const void *x)
void dump (const char *x)
void dump (const mem &x)
void dump (const buf &x)
void dump (const txt &x)
void dump (const seq &x)
void dump (const map &x)
void echo (const bool x)
void echo (const char x)
void echo (const int x)
void echo (const unsigned x)
void echo (const long x)
void echo (const unsigned long x)
void echo (const double x)
void echo (const void *x)
void echo (const char *x)
void echo (const mem &x)
void echo (const buf &x)
mem encode (const char x)
mem encode (const mem &x)
bool eq (const mem &x, const mem &y)
bool eq (const buf &x, const buf &y)
mem escape (const char x)
mem escape (const mem &x)
void file_copy (const mem &x, const mem &y)
bool file_eq (const mem &x, const mem &y)
mem file_locate (const mem &x)
int file_mtime (const mem &x)
long file_size (const mem &x)
int find (const mem &x, const char y)
void flower ()
void flower (const mem &x)
char front (const mem &x)
void front (mem &x, const char y)
char front (const buf &x)
void front (buf &x, const char y)
mem front (const txt &x)
mem front (const seq &x)
void fs_remove (const mem &x)
void fs_rename (const mem &x, const mem &y)
char * get_address (ptr &x)
char * get_address (mem &x)
const char * get_address (const mem &x)
char * get_address (ptr &x, const int y)
const char * get_address (const ptr &x, const int y)
char * get_address (mem &x, const int y)
const char * get_address (const mem &x, const int y)
int get_capacity (const buf &x)
mem get (const map &x, const mem &y)
mem get_date ()
mem get_date (const int x)
mem get_domain (const mem &x)
mem get_guid ()
mem get_guid (const int x)
mem get_ip (const fd &x)
int get_length (const ptr &x)
int get_length (const mem &x)
int get_length (const buf &x)
double get_now ()
int get_offset (const buf &x, const int y)
int get_overhead (const buf &x)
int get_random (const int x)
double get_time ()
mem glue (const txt &x)
mem glue (const seq &x)
mem glue (const txt &x, const char y)
mem glue (const seq &x, const char y)
mem glue (const txt &x, const mem &y)
mem glue (const seq &x, const mem &y)
bool has (map &x, const mem &y)
mem head (const mem &x, const int y)
mem head (const buf &x, const int y)
bool hit (const timer &x)
mem implode (const txt &x)
mem implode (const seq &x)
bool is_alnum (const char x)
bool is_alnum (const mem &x)
bool is_alpha (const char x)
bool is_alpha (const mem &x)
bool is_blank (const char x)
bool is_blank (const mem &x)
bool is_circular (const buf &x)
bool is_digit (const char x)
bool is_digit (const mem &x)
bool is_dir (const mem &x)
bool is_empty (const ptr &x)
bool is_empty (const buf &x)
bool is_empty (const mem &x)
bool is_empty (const txt &x)
bool is_empty (const seq &x)
bool is_empty (const fd &x)
bool is_empty (const pfile &x)
bool is_empty (const pthread &x)
bool is_empty (const map &x)
bool is_empty (const grid &x)
bool is_empty (const tbl &x)
bool is_file (const mem &x)
bool is_filled (const buf &x)
bool is_fs (const mem &x)
bool is_full (const ptr &x)
bool is_full (const mem &x)
bool is_full (const buf &x)
bool is_full (const fd &x)
bool is_full (const pfile &x)
bool is_full (const pthread &x)
bool is_full (const seq &x)
bool is_full (const txt &x)
bool is_full (const map &x)
bool is_full (const grid &x)
bool is_full (const tbl &x)
bool is_line (const mem &x)
bool is_nl (const char x)
bool is_nl (const mem &x)
bool is_normal (const buf &x)
bool is_punct (const char x)
bool is_space (const char x)
bool is_space (const mem &x)
bool is_text (const mem &x)
mem join (const txt &x)
mem join (const seq &x)
mem join (const txt &x, const char y)
mem join (const seq &x, const char y)
mem join (const txt &x, const mem &y)
mem join (const seq &x, const mem &y)
void * lift (const mem &x)
void * lift (const txt &x)
void * lift (const map &x)
void listen (fd &x, const int y)
mem load (const mem &x)
int main (const int x, const char **y)
bool match_l (const mem &x, const char y)
bool match_l (const buf &x, const char y)
bool match_l (const mem &x, const mem &y)
bool match_l (const buf &x, const mem &y)
bool match_r (const mem &x, const char y)
bool match_r (const buf &x, const char y)
bool match_r (const mem &x, const mem &y)
bool match_r (const buf &x, const mem &y)
void move (ptr &x, ptr &y)
void move (mem &x, mem &y)
void move (buf &x, buf &y)
void move (txt &x, txt &y)
void move (seq &x, seq &y)
void move (map &x, map &y)
void move (timer &x, timer &y)
void move (grid &x, grid &y)
void move (tbl &x, tbl &y)
bool neq (const mem &x, const mem &y)
bool neq (const buf &x, const buf &y)
void normalize (buf &x)
void open (fd &x, const mem &y)
void open (fd &x, const mem &y, const int z)
void open (pfile &x, const mem &y)
mem os_execute (const mem &x)
int os_system (const mem &x)
int os_system (const mem &x, const mem &y)
mem pad_l (const int x, const int y)
mem pad_l (const mem &x, const int y, const char z)
mem pad_r (const int x, const int y)
mem pad_r (const mem &x, const int y, const char z)
mem path_base (const mem &x)
mem path_concat (const mem &x, const mem &y)
mem path_dir (const mem &x)
mem path_ext (const mem &x)
mem path_name (const mem &x)
mem path_real (const mem &x)
mem path_resolve (const mem &x)
mem path_tmp (const mem &x)
mem path_unique (const mem &x)
char pop (mem &x)
mem pop (mem &x, const int y)
char pop (buf &x)
mem pop (buf &x, const int y)
mem pop (txt &x)
mem pop (seq &x)
void prepend (mem &x, const mem &y)
void prepend (buf &x, const char *y)
void prepend (buf &x, const mem &y)
void prepend (buf &x, const buf &y)
void prepend (txt &x, const txt &y)
void prepend (seq &x, const seq &y)
void print ()
void print (const bool x)
void print (const char x)
void print (const int x)
void print (const unsigned x)
void print (const long x)
void print (const unsigned long x)
void print (const double x)
void print (const void *x)
void print (const mem &x)
void print (const buf &x)
void print (const char *x)
void print (const txt &x)
void print (const seq &x)
void print (const map &x)
void push (mem &x, const char y)
void push (buf &x, const char y)
void push (txt &x, const mem &y)
void push (seq &x, const mem &y)
void put (map &x, const mem &y, const mem &z)
mem quote (const mem &x)
mem read (const fd &x)
mem read (const pfile &x)
mem read (const fd &x, const int y)
mem read (const pfile &x, const int y)
mem receive (const fd &x)
void remove (txt &x, const int y)
void remove (txt &x, const int y, const int z)
void remove (seq &x, const int y)
void remove (seq &x, const int y, const int z)
mem repeat (const mem &x, const int y)
mem replace (const mem &x, const char y, const char z)
mem replace (const mem &x, const mem &y, const mem &z)
void report ()
void reserve (buf &x, const int y)
void reset (buf &x)
void save (const mem &x, const mem &y)
void send (const fd &x, const mem &y)
void serialize (mem &x, const txt &y)
void serialize (mem &x, const map &y)
void set (mem &x, const int y, const char z)
void set (buf &x, const int y, const char z)
void set (map &x, const mem &y, const mem &z)
void set_non_block (const fd &x)
char shift (mem &x)
mem shift (mem &x, const int y)
char shift (buf &x)
mem shift (buf &x, const int y)
mem shift (txt &x)
mem shift (seq &x)
void shuffle (txt &x)
void shuffle (seq &x)
mem single_quote (const mem &x)
mem slice (const mem &x, const int y)
mem slice (const buf &x, const int y)
txt slice (const txt &x, const int y)
seq slice (const seq &x, const int y)
mem slice (const mem &x, const int y, const int z)
mem slice (const buf &x, const int y, const int z)
txt slice (const txt &x, const int y, const int z)
seq slice (const seq &x, const int y, const int z)
mem slice_l (const mem &x, const int y)
mem slice_l (const buf &x, const int y)
txt slice_l (const txt &x, const int y)
seq slice_l (const seq &x, const int y)
mem slice_r (const mem &x, const int y)
mem slice_r (const buf &x, const int y)
txt slice_r (const txt &x, const int y)
seq slice_r (const seq &x, const int y)
void sort (txt &x)
txt split (const mem &x, const char y)
txt split (const mem &x, const mem &y)
void stop ()
mem strip_l (const mem &x, const char y)
mem strip_l (const buf &x, const char y)
mem strip_l (const mem &x, const mem &y)
mem strip_l (const buf &x, const mem &y)
mem strip_r (const mem &x, const char y)
mem strip_r (const buf &x, const char y)
mem strip_r (const mem &x, const mem &y)
mem strip_r (const buf &x, const mem &y)
void swap (bool &x, bool &y)
void swap (char &x, char &y)
void swap (int &x, int &y)
void swap (unsigned &x, unsigned &y)
void swap (long &x, long &y)
void swap (unsigned long &x, unsigned long &y)
void swap (double &x, double &y)
void swap (char *&x, char *&y)
void swap (FILE *&x, FILE *&y)
void swap (ptr &x, ptr &y)
void swap (mem &x, mem &y)
void swap (buf &x, buf &y)
void swap (txt &x, txt &y)
void swap (seq &x, seq &y)
void swap (fd &x, fd &y)
void swap (pfile &x, pfile &y)
void swap (map &x, map &y)
void swap (grid &x, grid &y)
void swap (tbl &x, tbl &y)
void swap (timer &x, timer &y)
mem tail (const mem &x, const int y)
mem tail (const buf &x, const int y)
bool term_hit ()
mem term_read ()
int term_width ()
timer timeout (const double x)
void title_l (const mem &x)
void title_l (const mem &x, const mem &y)
void title_r (const mem &x)
void title_r (const mem &x, const mem &y)
mem to_bsize (const long x)
buf to_buf (const mem &x)
mem to_c (const mem &x)
mem to_hexa (const int x)
int to_int (const mem &x)
mem to_lit (const char x)
mem to_lit (const mem &x)
mem to_lit (const buf &x)
long to_long (const mem &x)
char to_lower (const char x)
mem to_lower (const mem &x)
mem to_mem (const bool x)
mem to_mem (const char x)
mem to_mem (const int x)
mem to_mem (const unsigned x)
mem to_mem (const long x)
mem to_mem (const unsigned long x)
mem to_mem (const double x)
mem to_mem (const double x, const int y)
mem to_mem (const void *x)
mem to_mem (const char *x)
mem to_mem (const buf &x)
mem to_mem (const txt &x)
mem to_mem (const seq &x)
mem to_mem (const map &x)
seq to_seq (const txt &x)
txt to_txt (const mem &x)
char to_upper (const char x)
mem to_upper (const mem &x)
mem translit (const mem &x)
mem trim (const mem &x)
mem trim_l (const mem &x)
txt trim_l (const txt &x)
mem trim_r (const mem &x)
txt trim_r (const txt &x)
void unlift (mem &x, void *y)
void unlift (txt &x, void *y)
void unlift (map &x, void *y)
void unshift (mem &x, const char y)
void unshift (buf &x, const char y)
void unshift (txt &x, const mem &y)
void unshift (seq &x, const mem &y)
void unwrap (void *x, const int y, const mem &z)
void unwrap (bool &x, const mem &y)
void unwrap (char &x, const mem &y)
void unwrap (int &x, const mem &y)
void unwrap (unsigned &x, const mem &y)
void unwrap (long &x, const mem &y)
void unwrap (unsigned long &x, const mem &y)
void unwrap (double &x, const mem &y)
void unwrap (void *&x, const mem &y)
void unwrap (txt &x, const mem &y)
void unwrap (map &x, const mem &y)
void wait (const double x)
mem wrap (const void *x, const int y)
mem wrap (const bool y)
mem wrap (const char y)
mem wrap (const int y)
mem wrap (const unsigned y)
mem wrap (const long y)
mem wrap (const unsigned long y)
mem wrap (const double y)
mem wrap (const void *y)
mem wrap (const txt &x)
mem wrap (const map &x)
void write (const fd &x, const mem &y)
mem doc_generate ()
void entry (const txt &x)
Function Documentation
accept()
bool accept (fd & x, fd & y)
Definition at line 757 of file explore.cc.
 {
  clear(y);
  y.handle=accept(x.handle,0,0);
  if(y.handle==-1)
  {
   check(errno==EAGAIN||errno==EWOULDBLOCK);
   return false;
  }
  set_non_block(y);
  return true;
 }
References check(), clear(), fd::handle, and set_non_block().
allocate()
void allocate (mem & x, const int y)
Definition at line 769 of file explore.cc.
 {
  check(y>=0);
  const int l=get_length(x);
  if(y==l)
   return;
  if(y==0)
  {
   clear(x);
   return;
  }
  if(is_empty(x))
  {
   x.pointer.pointer=(char*)malloc(y);
   check(x.pointer.pointer!=0);
  }
  else
  {
   char* pointer=get_address(x);
   char* p=(char*)realloc(pointer,y);
   check(p!=0);
   x.pointer.pointer=p;
  }
  x.pointer.length=y;
 }
References check(), clear(), get_address(), get_length(), is_empty(), ptr::length, ptr::pointer, and mem::pointer.
Referenced by append(), assign(), dir_current(), drop_l(), drop_r(), path_real(), prepend(), push(), read(), receive(), reserve(), slice(), to_hexa(), to_mem(), unshift(), and wrap().
append() [1/6]
void append (buf & x, const buf & y)
Definition at line 820 of file explore.cc.
 {
  const int lx=get_length(x);
  const int ly=get_length(y);
  const int l=lx+ly;
  reserve(x,l);
  for(int i=0;i<ly;i++)
  {
   const char c=at(y,i);
   push(x,c);
  }
 }
References at(), get_length(), push(), and reserve().
append() [2/6]
void append (buf & x, const char * y)
Definition at line 802 of file explore.cc.
 {
  check(y!=0);
  const mem m=y;
  append(x,m);
 }
References append(), and check().
append() [3/6]
void append (buf & x, const mem & y)
Definition at line 808 of file explore.cc.
 {
  const int lx=get_length(x);
  const int ly=get_length(y);
  const int l=lx+ly;
  reserve(x,l);
  for(int i=0;i<ly;i++)
  {
   const char c=at(y,i);
   push(x,c);
  }
 }
References at(), get_length(), push(), and reserve().
append() [4/6]
void append (mem & x, const mem & y)
Definition at line 794 of file explore.cc.
 {
  const int lx=get_length(x);
  const int ly=get_length(y);
  const int l=lx+ly;
  allocate(x,l);
  copy(x,lx,y,0,ly);
 }
References allocate(), copy(), and get_length().
Referenced by append(), assign(), concat(), encode(), escape(), implode(), join(), path_unique(), push(), quote(), read(), receive(), repeat(), replace(), and single_quote().
append() [5/6]
void append (seq & x, const seq & y)
Definition at line 836 of file explore.cc.
 {
  append(x.text,y.text);
 }
References append(), and seq::text.
append() [6/6]
void append (txt & x, const txt & y)
Definition at line 832 of file explore.cc.
 {
  append(x.buffer,y.buffer);
 }
References append(), and txt::buffer.
assign() [1/8]
void assign (buf & x, const buf & y)
Definition at line 877 of file explore.cc.
 {
  reset(x);
  append(x,y);
 }
References append(), and reset().
assign() [2/8]
void assign (buf & x, const char * y)
Definition at line 865 of file explore.cc.
 {
  check(y!=0);
  const int l=strlen(y);
  reset(x);
  reserve(x,l);
  for(int i=0;i<l;i++)
  {
   const char c=y[i];
   push(x,c);
  }
 }
References check(), push(), reserve(), and reset().
assign() [3/8]
void assign (map & x, const map & y)
Definition at line 890 of file explore.cc.
 {
  assign(x.keys,y.keys);
  assign(x.values,y.values);
 }
References assign(), map::keys, and map::values.
assign() [4/8]
void assign (mem & x, const buf & y)
Definition at line 859 of file explore.cc.
 {
  const int l=get_length(y);
  allocate(x,l);
  copy(x,0,y,0,l);
 }
References allocate(), copy(), and get_length().
assign() [5/8]
void assign (mem & x, const char * y)
Definition at line 840 of file explore.cc.
 {
  check(y!=0);
  const int l=strlen(y);
  if(l==0)
  {
   clear(x);
   return;
  }
  allocate(x,l);
  char* p=get_address(x);
  memcpy(p,y,l);
 }
References allocate(), check(), clear(), and get_address().
Referenced by assign(), buf::buf(), map::map(), mem::mem(), mem::operator=(), buf::operator=(), map::operator=(), seq::operator=(), txt::operator=(), seq::seq(), and txt::txt().
assign() [6/8]
void assign (mem & x, const mem & y)
Definition at line 853 of file explore.cc.
 {
  const int l=get_length(y);
  allocate(x,l);
  copy(x,0,y,0,l);
 }
References allocate(), copy(), and get_length().
assign() [7/8]
void assign (seq & x, const seq & y)
Definition at line 886 of file explore.cc.
 {
  assign(x.text,y.text);
 }
References assign(), and seq::text.
assign() [8/8]
void assign (txt & x, const txt & y)
Definition at line 882 of file explore.cc.
 {
  assign(x.buffer,y.buffer);
 }
References assign(), and txt::buffer.
at() [1/4]
char at (const buf & x, const int y)
Definition at line 903 of file explore.cc.
 {
  const int l=get_length(x);
  check(y>=0);
  check(y<l);
  const int n=get_offset(x,y);
  return at(x.memory,n);
 }
References at(), check(), get_length(), get_offset(), and buf::memory.
at() [2/4]
char at (const mem & x, const int y)
Definition at line 895 of file explore.cc.
 {
  const int l=get_length(x);
  check(y>=0);
  check(y<l);
  const char* p=get_address(x,y);
  return *p;
 }
References check(), get_address(), and get_length().
Referenced by append(), at(), back(), copy(), count(), encode(), eq(), escape(), find(), front(), is_alnum(), is_alpha(), is_blank(), is_digit(), is_nl(), is_space(), join(), match_l(), replace(), shuffle(), to_lower(), and to_upper().
at() [3/4]
mem at (const seq & x, const int y)
Definition at line 919 of file explore.cc.
 {
  const mem m=at(x.text,y);
  return decode(m);
 }
References at(), decode(), and seq::text.
at() [4/4]
mem at (const txt & x, const int y)
Definition at line 911 of file explore.cc.
 {
  check(y>=0);
  check(y<count(x));
  txt t=x;
  drop_l(t,y);
  return shift(t);
 }
References check(), count(), drop_l(), and shift().
back() [1/8]
void back (buf & x, const int y, const char z)
Definition at line 958 of file explore.cc.
 {
  const int l=get_length(x);
  check(y>=0);
  check(y<l);
  const int n=l-y-1;
  set(x,n,z);
 }
References check(), get_length(), and set().
back() [2/8]
char back (const buf & x)
Definition at line 945 of file explore.cc.
 {
  check(is_full(x));
  return back(x,0);
 }
References back(), check(), and is_full().
back() [3/8]
char back (const buf & x, const int y)
Definition at line 950 of file explore.cc.
 {
  const int l=get_length(x);
  check(y>=0);
  check(y<l);
  const int n=l-y-1;
  return at(x,n);
 }
References at(), check(), and get_length().
back() [4/8]
char back (const mem & x)
Definition at line 924 of file explore.cc.
 {
  check(is_full(x));
  return back(x,0);
 }
References check(), and is_full().
Referenced by back(), delimit(), drop_r(), get_domain(), is_empty(), match_r(), path_unique(), pop(), prepend(), push(), to_mem(), and trim_r().
back() [5/8]
char back (const mem & x, const int y)
Definition at line 929 of file explore.cc.
 {
  const int l=get_length(x);
  check(y>=0);
  check(y<l);
  const int n=l-y-1;
  return at(x,n);
 }
References at(), check(), and get_length().
back() [6/8]
mem back (const seq & x)
Definition at line 982 of file explore.cc.
 {
  check(is_full(x));
  const mem m=back(x.text);
  return decode(m);
 }
References back(), check(), decode(), is_full(), and seq::text.
back() [7/8]
mem back (const txt & x)
Definition at line 966 of file explore.cc.
 {
  check(is_full(x));
  buf b;
  const int l=get_length(x.buffer);
  const int lx=l-1;
  for(int i=0;i<lx;i++)
  {
   const char n=i+1;
   const char c=back(x.buffer,n);
   if(c=='\n')
    break;
   unshift(b,c);
  }
  return detach(b);
 }
References back(), txt::buffer, check(), detach(), get_length(), is_full(), and unshift().
back() [8/8]
void back (mem & x, const int y, const char z)
Definition at line 937 of file explore.cc.
 {
  const int l=get_length(x);
  check(y>=0);
  check(y<l);
  const int n=l-y-1;
  set(x,n,z);
 }
References check(), get_length(), and set().
check()
void check (const bool x)
Definition at line 988 of file explore.cc.
 {
  if(x)
   return;
  stop();
 }
References stop().
Referenced by accept(), allocate(), append(), assign(), at(), back(), clear(), copy(), create(), dim(), dir_change(), dir_copy(), dir_current(), dir_find(), dir_list(), dir_locate(), dir_make(), dir_remove(), disk_size(), disk_usage(), drop_l(), drop_r(), dump(), echo(), file_copy(), file_eq(), file_locate(), file_mtime(), file_size(), flower(), front(), fs_remove(), fs_rename(), get(), get_address(), get_date(), get_guid(), get_ip(), get_offset(), get_random(), get_time(), glue(), has(), head(), is_empty(), listen(), on_create(), open(), pad_l(), pad_r(), path_real(), pop(), print(), push(), put(), read(), receive(), remove(), repeat(), reserve(), send(), set(), set_non_block(), shift(), slice(), slice_l(), slice_r(), split(), tail(), term_read(), timeout(), title_l(), title_r(), to_bsize(), to_hexa(), to_int(), to_long(), to_mem(), unlift(), unshift(), unwrap(), wait(), wrap(), and write().
clear() [1/12]
void clear (buf & x)
Definition at line 1006 of file explore.cc.
 {
  x.index=0;
  x.length=0;
  clear(x.memory);
 }
References clear(), buf::index, buf::length, and buf::memory.
clear() [2/12]
void clear (fd & x)
Definition at line 1020 of file explore.cc.
 {
  if(is_empty(x))
   return;
  const int n=close(x.handle);
  x.handle=-1;
  check(n==0);
 }
References check(), fd::handle, and is_empty().
clear() [3/12]
void clear (grid & x)
Definition at line 1055 of file explore.cc.
 {
  x.width=0;
  x.height=0;
  clear(x.cells);
 }
References grid::cells, clear(), grid::height, and grid::width.
clear() [4/12]
void clear (map & x)
Definition at line 1045 of file explore.cc.
 {
  clear(x.keys);
  clear(x.values);
 }
References clear(), map::keys, and map::values.
clear() [5/12]
void clear (mem & x)
Definition at line 999 of file explore.cc.
 {
  if(is_empty(x))
   return;
  free(x.pointer.pointer);
  clear(x.pointer);
 }
References clear(), is_empty(), ptr::pointer, and mem::pointer.
clear() [6/12]
void clear (pfile & x)
Definition at line 1028 of file explore.cc.
 {
  if(is_empty(x))
   return;
  const int n=pclose(x.pointer);
  x.pointer=0;
  check(n==0);
 }
References check(), is_empty(), and pfile::pointer.
clear() [7/12]
void clear (pthread & x)
Definition at line 1036 of file explore.cc.
 {
  if(is_empty(x))
   return;
  void* p=0;
  const int n=pthread_join(x.pointer,&p);
  x.pointer=0;
  check(n==0);
 }
References check(), is_empty(), and pthread::pointer.
clear() [8/12]
void clear (ptr & x)
Definition at line 994 of file explore.cc.
 {
  x.pointer=0;
  x.length=0;
 }
References ptr::length, and ptr::pointer.
Referenced by accept(), allocate(), assign(), clear(), create(), deserialize(), destruct(), detach(), get_domain(), listen(), move(), open(), and os_execute().
clear() [9/12]
void clear (seq & x)
Definition at line 1016 of file explore.cc.
 {
  clear(x.text);
 }
References clear(), and seq::text.
clear() [10/12]
void clear (tbl & x)
Definition at line 1061 of file explore.cc.
 {
  clear(x.columns);
  clear(x.cells);
 }
References tbl::cells, clear(), and tbl::columns.
clear() [11/12]
void clear (timer & x)
Definition at line 1050 of file explore.cc.
 {
  x.start=get_now();
  x.duration=1;
 }
References timer::duration, get_now(), and timer::start.
clear() [12/12]
void clear (txt & x)
Definition at line 1012 of file explore.cc.
 {
  clear(x.buffer);
 }
References txt::buffer, and clear().
compact()
mem compact (const mem & x)
Definition at line 1066 of file explore.cc.
 {
  txt t1=to_txt(x);
  txt t2;
  while(is_full(t1))
  {
   const mem m1=shift(t1);
   const mem m2=trim_r(m1);
   if(is_empty(m2))
    continue;
   push(t2,m2);
  }
  const mem m3=glue(t2);
  return trim_r(m3);
 }
References glue(), is_empty(), is_full(), push(), shift(), to_txt(), and trim_r().
concat() [1/10]
mem concat (const mem & x, const mem & y)
Definition at line 1081 of file explore.cc.
 {
  mem r;
  append(r,x);
  append(r,y);
  return r;
 }
References append().
Referenced by delimit(), dir_copy(), dir_find(), dir_list(), dir_make(), dir_remove(), doc_generate(), entry(), escape(), file_copy(), get_date(), get_domain(), os_execute(), path_concat(), report(), sort(), title_l(), title_r(), to_bsize(), to_mem(), and translit().
concat() [2/10]
mem concat (const mem & x, const mem & y, const mem & z)
Definition at line 1088 of file explore.cc.
 {
  mem r;
  append(r,x);
  append(r,y);
  append(r,z);
  return r;
 }
References append().
concat() [3/10]
mem concat (const mem & x, const mem & y, const mem & z, const mem & a)
Definition at line 1096 of file explore.cc.
 {
  mem r;
  append(r,x);
  append(r,y);
  append(r,z);
  append(r,a);
  return r;
 }
References append().
concat() [4/10]
mem concat (const mem & x, const mem & y, const mem & z, const mem & a, const mem & b)
Definition at line 1105 of file explore.cc.
 {
  mem r;
  append(r,x);
  append(r,y);
  append(r,z);
  append(r,a);
  append(r,b);
  return r;
 }
References append().
concat() [5/10]
mem concat (const mem & x, const mem & y, const mem & z, const mem & a, const mem & b, const mem & c)
Definition at line 1115 of file explore.cc.
 {
  mem r;
  append(r,x);
  append(r,y);
  append(r,z);
  append(r,a);
  append(r,b);
  append(r,c);
  return r;
 }
References append().
concat() [6/10]
mem concat (const mem & x, const mem & y, const mem & z, const mem & a, const mem & b, const mem & c, const mem & d)
Definition at line 1126 of file explore.cc.
 {
  mem r;
  append(r,x);
  append(r,y);
  append(r,z);
  append(r,a);
  append(r,b);
  append(r,c);
  append(r,d);
  return r;
 }
References append().
concat() [7/10]
mem concat (const mem & x, const mem & y, const mem & z, const mem & a, const mem & b, const mem & c, const mem & d, const mem & e)
Definition at line 1138 of file explore.cc.
 {
  mem r;
  append(r,x);
  append(r,y);
  append(r,z);
  append(r,a);
  append(r,b);
  append(r,c);
  append(r,d);
  append(r,e);
  return r;
 }
References append().
concat() [8/10]
mem concat (const mem & x, const mem & y, const mem & z, const mem & a, const mem & b, const mem & c, const mem & d, const mem & e, const mem & f)
Definition at line 1151 of file explore.cc.
 {
  mem r;
  append(r,x);
  append(r,y);
  append(r,z);
  append(r,a);
  append(r,b);
  append(r,c);
  append(r,d);
  append(r,e);
  append(r,f);
  return r;
 }
References append().
concat() [9/10]
mem concat (const mem & x, const mem & y, const mem & z, const mem & a, const mem & b, const mem & c, const mem & d, const mem & e, const mem & f, const mem & g)
Definition at line 1165 of file explore.cc.
 {
  mem r;
  append(r,x);
  append(r,y);
  append(r,z);
  append(r,a);
  append(r,b);
  append(r,c);
  append(r,d);
  append(r,e);
  append(r,f);
  append(r,g);
  return r;
 }
References append().
concat() [10/10]
mem concat (const mem & x, const mem & y, const mem & z, const mem & a, const mem & b, const mem & c, const mem & d, const mem & e, const mem & f, const mem & g, const mem & h)
Definition at line 1180 of file explore.cc.
 {
  mem r;
  append(r,x);
  append(r,y);
  append(r,z);
  append(r,a);
  append(r,b);
  append(r,c);
  append(r,d);
  append(r,e);
  append(r,f);
  append(r,g);
  append(r,h);
  return r;
 }
References append().
contain() [1/4]
bool contain (const mem & x, const char y)
Definition at line 1196 of file explore.cc.
 {
  if(is_empty(x))
   return false;
  const int l=get_length(x);
  const void* p=get_address(x);
  const void* pp=memchr(p,y,l);
  return pp!=0;
 }
References get_address(), get_length(), and is_empty().
Referenced by contain(), has(), is_alpha(), is_digit(), is_punct(), is_text(), push(), to_mem(), and unshift().
contain() [2/4]
bool contain (const mem & x, const mem & y)
Definition at line 1205 of file explore.cc.
 {
  if(is_empty(x))
   return false;
  if(is_empty(y))
   return false;
  const int lx=get_length(x);
  const int ly=get_length(y);
  const char* px=get_address(x);
  const char* py=get_address(y);
  void* p=memmem(px,lx,py,ly);
  return p!=0;
 }
References get_address(), get_length(), and is_empty().
contain() [3/4]
bool contain (const seq & x, const mem & y)
Definition at line 1229 of file explore.cc.
 {
  const mem m=encode(y);
  return contain(x.text,m);
 }
References contain(), encode(), and seq::text.
contain() [4/4]
bool contain (const txt & x, const mem & y)
Definition at line 1218 of file explore.cc.
 {
  txt t=x;
  while(is_full(t))
  {
   const mem m=shift(t);
   if(eq(m,y))
    return true;
  }
  return false;
 }
References eq(), is_full(), and shift().
copy() [1/7]
void copy (buf & x, const int y, const buf & z, const int a, const int b)
Definition at line 1338 of file explore.cc.
 {
  const int lx=get_length(x);
  const int lz=get_length(z);
  check(y>=0);
  check(y<=lx);
  check(a>=0);
  check(a<=lz);
  check(b>=0);
  check(b<=lz);
  check(y+b<=lx);
  check(a+b<=lz);
  if(b==0)
   return;
  if(is_circular(x)||is_circular(z))
  {
   for(int i=0;i<b;i++)
   {
    const int ny=y+i;
    const int na=a+i;
    const char c=at(z,na);
    set(x,ny,c);
   }
   return;
  }
  const int ny=x.index+y;
  const int na=z.index+a;
  copy(x.memory,ny,z.memory,na,b);
 }
References at(), check(), copy(), get_length(), buf::index, is_circular(), buf::memory, and set().
copy() [2/7]
void copy (buf & x, const int y, const mem & z, const int a, const int b)
Definition at line 1282 of file explore.cc.
 {
  const int lx=get_length(x);
  const int lz=get_length(z);
  check(y>=0);
  check(y<=lx);
  check(a>=0);
  check(a<=lz);
  check(b>=0);
  check(b<=lz);
  check(y+b<=lx);
  check(a+b<=lz);
  if(b==0)
   return;
  if(is_circular(x))
  {
   for(int i=0;i<b;i++)
   {
    const int ny=y+i;
    const int na=a+i;
    const char c=at(z,na);
    set(x,ny,c);
   }
   return;
  }
  const int ny=x.index+y;
  copy(x.memory,ny,z,a,b);
 }
References at(), check(), copy(), get_length(), buf::index, is_circular(), buf::memory, and set().
copy() [3/7]
void copy (mem & x, const int y, const buf & z, const int a, const int b)
Definition at line 1310 of file explore.cc.
 {
  const int lx=get_length(x);
  const int lz=get_length(z);
  check(y>=0);
  check(y<=lx);
  check(a>=0);
  check(a<=lz);
  check(b>=0);
  check(b<=lz);
  check(y+b<=lx);
  check(a+b<=lz);
  if(b==0)
   return;
  if(is_circular(z))
  {
   for(int i=0;i<b;i++)
   {
    const int ny=y+i;
    const int na=a+i;
    const char c=at(z,na);
    set(x,ny,c);
   }
   return;
  }
  const int na=z.index+a;
  copy(x,y,z.memory,na,b);
 }
References at(), check(), copy(), get_length(), buf::index, is_circular(), buf::memory, and set().
copy() [4/7]
void copy (mem & x, const int y, const int z, const int a)
Definition at line 1256 of file explore.cc.
 {
  copy(x.pointer,y,z,a);
 }
References copy(), and mem::pointer.
copy() [5/7]
void copy (mem & x, const int y, const mem & z, const int a, const int b)
Definition at line 1278 of file explore.cc.
 {
  copy(x.pointer,y,z.pointer,a,b);
 }
References copy(), and mem::pointer.
copy() [6/7]
void copy (ptr & x, const int y, const int z, const int a)
Definition at line 1234 of file explore.cc.
 {
  const int l=get_length(x);
  check(y>=0);
  check(y<=l);
  check(z>=0);
  check(z<=l);
  check(a>=0);
  check(a<=l);
  check(y+a<=l);
  check(z+a<=l);
  if(a==0)
   return;
  const int yz=y+z;
  const bool overlap=a>y&&a<yz;
  char* py=get_address(x,y);
  char* pz=get_address(x,z);
  if(overlap)
   memmove(py,pz,a);
  else
   memcpy(py,pz,a);
 }
References check(), get_address(), and get_length().
Referenced by append(), assign(), copy(), drop_l(), prepend(), reserve(), slice(), to_buf(), and unshift().
copy() [7/7]
void copy (ptr & x, const int y, const ptr & z, const int a, const int b)
Definition at line 1260 of file explore.cc.
 {
  const int lx=get_length(x);
  const int lz=get_length(z);
  check(y>=0);
  check(y<=lx);
  check(a>=0);
  check(a<=lz);
  check(b>=0);
  check(b<=lz);
  check(y+b<=lx);
  check(a+b<=lz);
  if(b==0)
   return;
  char* py=get_address(x,y);
  const char* pa=get_address(z,a);
  memcpy(py,pa,b);
 }
References check(), get_address(), and get_length().
count() [1/5]
int count (const buf & x, const char y)
Definition at line 1379 of file explore.cc.
 {
  int r=0;
  const int l=get_length(x);
  for(int i=0;i<l;i++)
  {
   const char c=at(x,i);
   if(c==y)
    r++;
  }
  return r;
 }
References at(), and get_length().
count() [2/5]
int count (const map & x)
Definition at line 1399 of file explore.cc.
 {
  return count(x.keys);
 }
References count(), and map::keys.
count() [3/5]
int count (const mem & x, const char y)
Definition at line 1367 of file explore.cc.
 {
  int r=0;
  const int l=get_length(x);
  for(int i=0;i<l;i++)
  {
   const char c=at(x,i);
   if(c==y)
    r++;
  }
  return r;
 }
References at(), and get_length().
Referenced by at(), count(), path_ext(), path_name(), remove(), shuffle(), slice(), slice_l(), and slice_r().
count() [4/5]
int count (const seq & x)
Definition at line 1395 of file explore.cc.
 {
  return count(x.text);
 }
References count(), and seq::text.
count() [5/5]
int count (const txt & x)
Definition at line 1391 of file explore.cc.
 {
  return count(x.buffer,'\n');
 }
References txt::buffer, and count().
create()
void create (pthread & x, void(*)(const map &) y, const map & z)
Definition at line 1403 of file explore.cc.
 {
  check(y!=0);
  clear(x);
  map m;
  set(m,"routine",wrap((void*)y));
  set(m,"arguments",wrap(z));
  void* p=lift(m);
  const int n=pthread_create(&x.pointer,0,on_create,p);
  check(n==0);
 }
References check(), clear(), lift(), on_create(), pthread::pointer, set(), and wrap().
decode()
mem decode (const mem & x)
Definition at line 1429 of file explore.cc.
 {
  buf output;
  buf input=to_buf(x);
  const mem bn="\\n";
  const mem bs="\\\\";
  const int ln=get_length(bn);
  const int ls=get_length(bs);
  while(is_full(input))
  {
   if(match_l(input,bn))
   {
    shift(input,ln);
    push(output,'\n');
   }
   else if(match_l(input,bs))
   {
    shift(input,ls);
    push(output,'\\');
   }
   else
   {
    const char c=shift(input);
    push(output,c);
   }
  }
  return detach(output);
 }
References detach(), get_length(), is_full(), match_l(), push(), shift(), and to_buf().
Referenced by at(), back(), deserialize(), front(), and unlift().
delimit()
seq delimit (const mem & x)
Definition at line 1457 of file explore.cc.
 {
  seq r;
  buf b=to_buf(x);
  while(is_full(b))
  {
   const char c=shift(b);
   if(is_empty(r))
   {
    mem m;
    push(m,c);
    push(r,m);
    continue;
   }
   const mem left=back(r);
   mem right;
   push(right,c);
   if(is_alnum(left)&&is_alnum(right))
   {
    const mem m=concat(left,right);
    drop_r(r);
    push(r,m);
   }
   else if(is_space(left)&&is_space(right))
   {
    const mem m=concat(left,right);
    drop_r(r);
    push(r,m);
   }
   else if(is_nl(left)&&is_nl(right))
   {
    const mem m=concat(left,right);
    drop_r(r);
    push(r,m);
   }
   else
    push(r,right);
  }
  return r;
 }
References back(), concat(), drop_r(), is_alnum(), is_empty(), is_full(), is_nl(), is_space(), push(), shift(), and to_buf().
deserialize() [1/2]
void deserialize (map & x, const mem & y)
Definition at line 1502 of file explore.cc.
 {
  clear(x);
  txt t;
  deserialize(t,y);
  while(is_full(t))
  {
   const mem m1=shift(t);
   const mem m2=shift(t);
   const mem m3=decode(m1);
   const mem key=trim(m3);
   const mem value=decode(m2);
   put(x,key,value);
  }
 }
References clear(), decode(), deserialize(), is_full(), put(), shift(), and trim().
deserialize() [2/2]
void deserialize (txt & x, const mem & y)
Definition at line 1497 of file explore.cc.
 {
  txt t=to_txt(y);
  move(x,t);
 }
References move(), and to_txt().
Referenced by deserialize(), unlift(), and unwrap().
destruct() [1/4]
void destruct (fd & x)
Definition at line 1528 of file explore.cc.
 {
  try
  {
   clear(x);
  }
  catch(...)
  {
   report();
  }
 }
References clear(), and report().
destruct() [2/4]
void destruct (mem & x)
Definition at line 1517 of file explore.cc.
 {
  try
  {
   clear(x);
  }
  catch(...)
  {
   report();
  }
 }
References clear(), and report().
Referenced by fd::~fd(), mem::~mem(), pfile::~pfile(), and pthread::~pthread().
destruct() [3/4]
void destruct (pfile & x)
Definition at line 1539 of file explore.cc.
 {
  try
  {
   clear(x);
  }
  catch(...)
  {
   report();
  }
 }
References clear(), and report().
destruct() [4/4]
void destruct (pthread & x)
Definition at line 1550 of file explore.cc.
 {
  try
  {
   clear(x);
  }
  catch(...)
  {
   report();
  }
 }
References clear(), and report().
detach() [1/3]
mem detach (buf & x)
Definition at line 1571 of file explore.cc.
 {
  if(is_normal(x))
  {
   mem r;
   swap(r,x.memory);
   reset(x);
   return r;
  }
  const mem r=to_mem(x);
  clear(x);
  return r;
 }
References clear(), is_normal(), buf::memory, reset(), swap(), and to_mem().
detach() [2/3]
ptr detach (mem & x)
Definition at line 1567 of file explore.cc.
 {
  return detach(x.pointer);
 }
References detach(), and mem::pointer.
detach() [3/3]
ptr detach (ptr & x)
Definition at line 1561 of file explore.cc.
 {
  const ptr r=x;
  clear(x);
  return r;
 }
References clear().
Referenced by back(), decode(), detach(), encode(), escape(), front(), get_guid(), lift(), path_unique(), read(), repeat(), replace(), split(), trim_l(), trim_r(), and unlift().
dim()
void dim (buf & x, const int y)
Definition at line 1584 of file explore.cc.
 {
  check(y>=0);
  reserve(x,y);
  x.length=y;
 }
References check(), buf::length, and reserve().
Referenced by to_buf().
dir_change()
void dir_change (const mem & x)
Definition at line 1590 of file explore.cc.
 {
  const mem m=to_c(x);
  const char* p=get_address(m);
  const int n=chdir(p);
  check(n==0);
 }
References check(), get_address(), and to_c().
Referenced by os_system().
dir_clean()
void dir_clean (const mem & x)
Definition at line 1597 of file explore.cc.
 {
  if(is_dir(x))
   dir_remove(x);
 }
References dir_remove(), and is_dir().
Referenced by dir_reset(), and entry().
dir_copy()
void dir_copy (const mem & x, const mem & y)
Definition at line 1602 of file explore.cc.
 {
  check(is_dir(x));
  check(is_dir(y));
  const mem qx=quote(x);
  const mem qy=quote(y);
  const mem m=concat("cp -rf ",qx," ",qy);
  os_execute(m);
 }
References check(), concat(), is_dir(), os_execute(), and quote().
dir_current()
mem dir_current ()
Definition at line 1611 of file explore.cc.
 {
  mem m;
  allocate(m,PATH_MAX);
  const int l=get_length(m);
  char* p=get_address(m);
  char* r=getcwd(p,l);
  check(r!=0);
  return r;
 }
References allocate(), check(), get_address(), and get_length().
Referenced by dir_locate(), file_locate(), and os_system().
dir_find()
txt dir_find (const mem & x)
Definition at line 1621 of file explore.cc.
 {
  check(is_dir(x));
  txt r;
  const mem qx=quote(x);
  const mem command=concat("find ",qx);
  const mem result=os_execute(command);
  txt t=to_txt(result);
  while(is_full(t))
  {
   const mem m1=shift(t);
   const mem m2=path_real(m1);
   if(is_file(m2))
    push(r,m2);
  }
  sort(r);
  return r;
 }
References check(), concat(), is_dir(), is_file(), is_full(), os_execute(), path_real(), push(), quote(), shift(), sort(), and to_txt().
dir_list()
txt dir_list (const mem & x)
Definition at line 1639 of file explore.cc.
 {
  check(is_dir(x));
  txt r;
  const mem dir=path_real(x);
  const mem qdir=quote(dir);
  const mem command=concat("ls ",qdir);
  const mem result=os_execute(command);
  txt t=to_txt(result);
  while(is_full(t))
  {
   const mem m1=shift(t);
   const mem m2=path_concat(x,m1);
   const mem m3=path_real(m2);
   if(eq(m3,dir))
    continue;
   push(r,m3);
  }
  sort(r);
  return r;
 }
References check(), concat(), eq(), is_dir(), is_full(), os_execute(), path_concat(), path_real(), push(), quote(), shift(), sort(), and to_txt().
Referenced by doc_generate().
dir_locate()
mem dir_locate (const mem & x)
Definition at line 1660 of file explore.cc.
 {
  check(is_full(x));
  const mem current=dir_current();
  txt dirs=split(current,'/');
  while(is_full(dirs))
  {
   const mem dir=join(dirs,'/');
   const mem path=path_concat(dir,x);
   if(is_dir(path))
    return path_real(path);
   drop_r(dirs);
  }
  stop();
  return {};
 }
References check(), dir_current(), drop_r(), is_dir(), is_full(), join(), path_concat(), path_real(), split(), and stop().
Referenced by doc_generate(), entry(), and path_tmp().
dir_make()
void dir_make (const mem & x)
Definition at line 1676 of file explore.cc.
 {
  check(!is_fs(x));
  const mem qx=quote(x);
  const mem command=concat("mkdir -p ",qx);
  os_execute(command);
  check(is_dir(x));
 }
References check(), concat(), is_dir(), is_fs(), os_execute(), and quote().
Referenced by dir_reset(), doc_generate(), and save().
dir_remove()
void dir_remove (const mem & x)
Definition at line 1684 of file explore.cc.
 {
  check(is_dir(x));
  const mem qx=quote(x);
  const mem m=concat("rm -rf ",qx);
  os_execute(m);
 }
References check(), concat(), is_dir(), os_execute(), and quote().
Referenced by dir_clean().
dir_reset()
void dir_reset (const mem & x)
Definition at line 1691 of file explore.cc.
 {
  dir_clean(x);
  dir_make(x);
 }
References dir_clean(), and dir_make().
Referenced by doc_generate().
disk_free()
long disk_free ()
Definition at line 1696 of file explore.cc.
 {
  const long s=disk_size();
  const long u=disk_usage();
  return s-u;
 }
References disk_size(), and disk_usage().
disk_size()
long disk_size ()
Definition at line 1702 of file explore.cc.
 {
  struct statfs s;
  const int n=statfs("/",&s);
  check(n==0);
  return s.f_bsize*s.f_blocks;
 }
References check().
Referenced by disk_free(), and disk_usage().
disk_usage()
long disk_usage ()
Definition at line 1709 of file explore.cc.
 {
  struct statfs s;
  const int n=statfs("/",&s);
  check(n==0);
  const long l=disk_size();
  return l-s.f_bsize*s.f_bfree;
 }
References check(), and disk_size().
Referenced by disk_free().
doc_generate()
mem doc_generate ()
Definition at line 4859 of file explore.cc.
 {
  const mem tmp=dir_locate("tmp");
  const mem work=path_concat(tmp,"doc-gen");
  const mem code=path_concat(work,"code");
  const mem config=path_concat(work,"Doxyfile");
  os_system("./build --build");
  dir_reset(work);
  dir_make(code);
  txt t1=dir_list("src/program");
  while(is_full(t1))
  {
   const mem left=shift(t1);
   const mem base=path_base(left);
   const mem out="out/out.cc";
   const mem cc=concat(base,".cc");
   const mem right=path_concat(code,cc);
   os_system(concat("./build --",base));
   file_copy(out,right);
  }
  txt t2;
  push(t2,concat("INPUT=",code));
  push(t2,"RECURSIVE=YES");
  push(t2,"EXTRACT_ALL=YES");
  push(t2,"INLINE_SOURCES=YES");
  push(t2,"SOURCE_BROWSER=YES");
  push(t2,"CALL_GRAPH=YES");
  push(t2,"CALLER_GRAPH=YES");
  push(t2,"REFERENCED_BY_RELATION=YES");
  push(t2,"REFERENCES_RELATION=YES");
  push(t2,"HTML_TIMESTAMP=YES");
  push(t2,"PROJECT_NAME=source");
  push(t2,"GENERATE_TREEVIEW=yes");
  push(t2,"GENERATE_LATEX=no");
  push(t2,"HAVE_DOT=yes");
  push(t2,"DOT_NUM_THREADS=16");
  push(t2,"DOT_GRAPH_MAX_NODES=256");
  push(t2,"COLLABORATION_GRAPH=yes");
  save(config,join(t2));
  os_system(work,concat("doxygen ",config));
  return path_concat(work,"html");
 }
References concat(), dir_list(), dir_locate(), dir_make(), dir_reset(), file_copy(), is_full(), join(), os_system(), path_base(), path_concat(), push(), save(), and shift().
Referenced by entry().
drop_l() [1/8]
void drop_l (buf & x)
Definition at line 1731 of file explore.cc.
 {
  check(is_full(x));
  drop_l(x,1);
 }
References check(), drop_l(), and is_full().
drop_l() [2/8]
void drop_l (buf & x, const int y)
Definition at line 1736 of file explore.cc.
 {
  check(y>=0);
  check(y<=x.length);
  const int l=get_capacity(x);
  x.index+=y;
  x.index%=l;
  x.length-=y;
 }
References check(), get_capacity(), buf::index, and buf::length.
drop_l() [3/8]
void drop_l (mem & x)
Definition at line 1717 of file explore.cc.
 {
  check(is_full(x));
  drop_l(x,1);
 }
References check(), and is_full().
Referenced by at(), drop_l(), send(), shift(), and slice().
drop_l() [4/8]
void drop_l (mem & x, const int y)
Definition at line 1722 of file explore.cc.
 {
  const int l=get_length(x);
  check(y>=0);
  check(y<=l);
  const int ly=l-y;
  copy(x,0,y,ly);
  allocate(x,ly);
 }
References allocate(), check(), copy(), and get_length().
drop_l() [5/8]
void drop_l (seq & x)
Definition at line 1755 of file explore.cc.
 {
  check(is_full(x));
  drop_l(x.text);
 }
References check(), drop_l(), is_full(), and seq::text.
drop_l() [6/8]
void drop_l (seq & x, const int y)
Definition at line 1768 of file explore.cc.
 {
  check(y>=0);
  for(int i=0;i<y;i++)
  {
   drop_l(x);
  }
 }
References check(), and drop_l().
drop_l() [7/8]
void drop_l (txt & x)
Definition at line 1745 of file explore.cc.
 {
  check(is_full(x));
  while(is_full(x.buffer))
  {
   const char c=shift(x.buffer);
   if(c=='\n')
    break;
  }
 }
References txt::buffer, check(), is_full(), and shift().
drop_l() [8/8]
void drop_l (txt & x, const int y)
Definition at line 1760 of file explore.cc.
 {
  check(y>=0);
  for(int i=0;i<y;i++)
  {
   drop_l(x);
  }
 }
References check(), and drop_l().
drop_r() [1/8]
void drop_r (buf & x)
Definition at line 1789 of file explore.cc.
 {
  check(is_full(x));
  drop_r(x,1);
 }
References check(), drop_r(), and is_full().
drop_r() [2/8]
void drop_r (buf & x, const int y)
Definition at line 1794 of file explore.cc.
 {
  const int l=get_length(x);
  check(y>=0);
  check(y<=l);
  x.length-=y;
 }
References check(), get_length(), and buf::length.
drop_r() [3/8]
void drop_r (mem & x)
Definition at line 1776 of file explore.cc.
 {
  check(is_full(x));
  drop_r(x,1);
 }
References check(), and is_full().
Referenced by delimit(), dir_locate(), drop_r(), file_locate(), glue(), path_name(), path_unique(), pop(), slice(), to_mem(), and trim_r().
drop_r() [4/8]
void drop_r (mem & x, const int y)
Definition at line 1781 of file explore.cc.
 {
  const int l=get_length(x);
  check(y>=0);
  check(y<=l);
  const int ly=l-y;
  allocate(x,ly);
 }
References allocate(), check(), and get_length().
drop_r() [5/8]
void drop_r (seq & x)
Definition at line 1813 of file explore.cc.
 {
  check(is_full(x));
  drop_r(x.text);
 }
References check(), drop_r(), is_full(), and seq::text.
drop_r() [6/8]
void drop_r (seq & x, const int y)
Definition at line 1826 of file explore.cc.
 {
  check(y>=0);
  for(int i=0;i<y;i++)
  {
   drop_r(x);
  }
 }
References check(), and drop_r().
drop_r() [7/8]
void drop_r (txt & x)
Definition at line 1801 of file explore.cc.
 {
  check(is_full(x));
  drop_r(x.buffer);
  while(is_full(x.buffer))
  {
   const char c=back(x.buffer);
   if(c=='\n')
    break;
   drop_r(x.buffer);
  }
 }
References back(), txt::buffer, check(), drop_r(), and is_full().
drop_r() [8/8]
void drop_r (txt & x, const int y)
Definition at line 1818 of file explore.cc.
 {
  check(y>=0);
  for(int i=0;i<y;i++)
  {
   drop_r(x);
  }
 }
References check(), and drop_r().
dump() [1/14]
void dump (const bool x)
Definition at line 1834 of file explore.cc.
 {
  print(x);
 }
References print().
Referenced by dump(), and print().
dump() [2/14]
void dump (const buf & x)
Definition at line 1877 of file explore.cc.
 {
  const mem m=to_lit(x);
  print(m);
 }
References print(), and to_lit().
dump() [3/14]
void dump (const char * x)
Definition at line 1866 of file explore.cc.
 {
  check(x!=0);
  const mem m=to_mem(x);
  dump(m);
 }
References check(), dump(), and to_mem().
dump() [4/14]
void dump (const char x)
Definition at line 1838 of file explore.cc.
 {
  print(x);
 }
References print().
dump() [5/14]
void dump (const double x)
Definition at line 1858 of file explore.cc.
 {
  print(x);
 }
References print().
dump() [6/14]
void dump (const int x)
Definition at line 1842 of file explore.cc.
 {
  print(x);
 }
References print().
dump() [7/14]
void dump (const long x)
Definition at line 1850 of file explore.cc.
 {
  print(x);
 }
References print().
dump() [8/14]
void dump (const map & x)
Definition at line 1910 of file explore.cc.
 {
  map m=x;
  while(is_full(m))
  {
   const mem k=shift(m.keys);
   const mem v=shift(m.values);
   echo(to_lit(k));
   echo(" ");
   echo(to_lit(v));
   print();
  }
 }
References echo(), is_full(), map::keys, print(), shift(), to_lit(), and map::values.
dump() [9/14]
void dump (const mem & x)
Definition at line 1872 of file explore.cc.
 {
  const mem m=to_lit(x);
  print(m);
 }
References print(), and to_lit().
dump() [10/14]
void dump (const seq & x)
Definition at line 1896 of file explore.cc.
 {
  seq s=x;
  int n=0;
  while(is_full(s))
  {
   const mem m=shift(s);
   echo("#");
   echo(n);
   echo(" ");
   dump(m);
   n++;
  }
 }
References dump(), echo(), is_full(), and shift().
dump() [11/14]
void dump (const txt & x)
Definition at line 1882 of file explore.cc.
 {
  txt t=x;
  int n=0;
  while(is_full(t))
  {
   const mem m=shift(t);
   echo("#");
   echo(n);
   echo(" ");
   dump(m);
   n++;
  }
 }
References dump(), echo(), is_full(), and shift().
dump() [12/14]
void dump (const unsigned long x)
Definition at line 1854 of file explore.cc.
 {
  print(x);
 }
References print().
dump() [13/14]
void dump (const unsigned x)
Definition at line 1846 of file explore.cc.
 {
  print(x);
 }
References print().
dump() [14/14]
void dump (const void * x)
Definition at line 1862 of file explore.cc.
 {
  print(x);
 }
References print().
echo() [1/11]
void echo (const bool x)
Definition at line 1923 of file explore.cc.
 {
  const mem m=to_mem(x);
  echo(m);
 }
References to_mem().
Referenced by dump(), echo(), and print().
echo() [2/11]
void echo (const buf & x)
Definition at line 1978 of file explore.cc.
 {
  const mem m=to_mem(x);
  echo(m);
 }
References echo(), and to_mem().
echo() [3/11]
void echo (const char * x)
Definition at line 1963 of file explore.cc.
 {
  check(x!=0);
  const mem m=to_mem(x);
  echo(m);
 }
References check(), echo(), and to_mem().
echo() [4/11]
void echo (const char x)
Definition at line 1928 of file explore.cc.
 {
  const mem m=to_mem(x);
  echo(m);
 }
References echo(), and to_mem().
echo() [5/11]
void echo (const double x)
Definition at line 1953 of file explore.cc.
 {
  const mem m=to_mem(x);
  echo(m);
 }
References echo(), and to_mem().
echo() [6/11]
void echo (const int x)
Definition at line 1933 of file explore.cc.
 {
  const mem m=to_mem(x);
  echo(m);
 }
References echo(), and to_mem().
echo() [7/11]
void echo (const long x)
Definition at line 1943 of file explore.cc.
 {
  const mem m=to_mem(x);
  echo(m);
 }
References echo(), and to_mem().
echo() [8/11]
void echo (const mem & x)
Definition at line 1969 of file explore.cc.
 {
  if(is_empty(x))
   return;
  const int l=get_length(x);
  const char* p=get_address(x);
  const int n=write(STDOUT_FILENO,p,l);
  check(n==l);
 }
References check(), get_address(), get_length(), is_empty(), and write().
echo() [9/11]
void echo (const unsigned long x)
Definition at line 1948 of file explore.cc.
 {
  const mem m=to_mem(x);
  echo(m);
 }
References echo(), and to_mem().
echo() [10/11]
void echo (const unsigned x)
Definition at line 1938 of file explore.cc.
 {
  const mem m=to_mem(x);
  echo(m);
 }
References echo(), and to_mem().
echo() [11/11]
void echo (const void * x)
Definition at line 1958 of file explore.cc.
 {
  const mem m=to_mem(x);
  echo(m);
 }
References echo(), and to_mem().
encode() [1/2]
mem encode (const char x)
Definition at line 1983 of file explore.cc.
 {
  mem r;
  if(x=='\\')
   append(r,"\\\\");
  else if(x=='\n')
   append(r,"\\n");
  else
   push(r,x);
  return r;
 }
References append(), and push().
Referenced by contain(), encode(), lift(), push(), serialize(), and unshift().
encode() [2/2]
mem encode (const mem & x)
Definition at line 1994 of file explore.cc.
 {
  const int l=get_length(x);
  buf b;
  reserve(b,l);
  for(int i=0;i<l;i++)
  {
   const char c=at(x,i);
   const mem m=encode(c);
   append(b,m);
  }
  return detach(b);
 }
References append(), at(), detach(), encode(), get_length(), and reserve().
entry()
void entry (const txt & x)
Definition at line 4901 of file explore.cc.
 {
  const mem html=doc_generate();
  const mem tmp=dir_locate("tmp");
  const mem repo="mabiven.github.io";
  const mem work=path_concat(tmp,repo);
  dir_clean(work);
  fs_rename(html,work);
  os_system("./build --commit");
  os_system(concat("out/commit-gcc-g ",work," github-a"));
  os_system("xdg-open https://mabiven.github.io/");
 }
References concat(), dir_clean(), dir_locate(), doc_generate(), fs_rename(), os_system(), and path_concat().
Referenced by main().
eq() [1/2]
bool eq (const buf & x, const buf & y)
Definition at line 2022 of file explore.cc.
 {
  const int lx=get_length(x);
  const int ly=get_length(y);
  if(lx!=ly)
   return false;
  for(int i=0;i<lx;i++)
  {
   const char cx=at(x,i);
   const char cy=at(y,i);
   if(cx!=cy)
    return false;
  }
  return true;
 }
References at(), and get_length().
eq() [2/2]
bool eq (const mem & x, const mem & y)
Definition at line 2007 of file explore.cc.
 {
  const int lx=get_length(x);
  const int ly=get_length(y);
  if(lx!=ly)
   return false;
  for(int i=0;i<lx;i++)
  {
   const char cx=at(x,i);
   const char cy=at(y,i);
   if(cx!=cy)
    return false;
  }
  return true;
 }
References at(), and get_length().
Referenced by contain(), dir_list(), file_eq(), get(), neq(), put(), and save().
escape() [1/2]
mem escape (const char x)
Definition at line 2037 of file explore.cc.
 {
  if(x==' ')
   return " ";
  if(x=='\r')
   return "\\r";
  if(x=='\n')
   return "\\n";
  if(x=='\t')
   return "\\t";
  if(x=='"')
   return "\\\"";
  if(is_punct(x))
  {
   mem r;
   push(r,x);
   return r;
  }
  if(is_alnum(x))
  {
   mem r;
   push(r,x);
   return r;
  }
  const unsigned char u=x;
  const mem m1=to_hexa(u);
  const mem m2=pad_l(m1,2,'0');
  return concat("\\x",m2);
 }
References concat(), is_alnum(), is_punct(), pad_l(), push(), and to_hexa().
Referenced by escape(), and to_lit().
escape() [2/2]
mem escape (const mem & x)
Definition at line 2066 of file explore.cc.
 {
  const int l=get_length(x);
  buf b;
  reserve(b,l);
  for(int i=0;i<l;i++)
  {
   const char c=at(x,i);
   const mem m=escape(c);
   append(b,m);
  }
  return detach(b);
 }
References append(), at(), detach(), escape(), get_length(), and reserve().
file_copy()
void file_copy (const mem & x, const mem & y)
Definition at line 2079 of file explore.cc.
 {
  check(is_file(x));
  if(is_dir(y))
  {
   const mem base=path_base(x);
   const mem m=path_concat(y,base);
   file_copy(x,m);
   return;
  }
  const mem qx=quote(x);
  const mem qy=quote(y);
  const mem m=concat("cp -f --preserve ",qx," ",qy);
  os_execute(m);
 }
References check(), concat(), is_dir(), is_file(), os_execute(), path_base(), path_concat(), and quote().
Referenced by doc_generate().
file_eq()
bool file_eq (const mem & x, const mem & y)
Definition at line 2094 of file explore.cc.
 {
  check(is_file(x));
  check(is_file(y));
  const long lx=file_size(x);
  const long ly=file_size(y);
  if(lx!=ly)
   return false;
  const mem mx=load(x);
  const mem my=load(y);
  return eq(mx,my);
 }
References check(), eq(), file_size(), is_file(), and load().
file_locate()
mem file_locate (const mem & x)
Definition at line 2106 of file explore.cc.
 {
  check(is_full(x));
  const mem current=dir_current();
  txt dirs=split(current,'/');
  while(is_full(dirs))
  {
   const mem dir=join(dirs,'/');
   const mem path=path_concat(dir,x);
   if(is_file(path))
    return path_real(path);
   drop_r(dirs);
  }
  stop();
  return {};
 }
References check(), dir_current(), drop_r(), is_file(), is_full(), join(), path_concat(), path_real(), split(), and stop().
file_mtime()
int file_mtime (const mem & x)
Definition at line 2122 of file explore.cc.
 {
  check(is_file(x));
  const struct stat s=fs_stat(x);
  return s.st_mtime;
 }
References check(), fs_stat(), and is_file().
file_size()
long file_size (const mem & x)
Definition at line 2128 of file explore.cc.
 {
  check(is_file(x));
  const struct stat s=fs_stat(x);
  return s.st_size;
 }
References check(), fs_stat(), and is_file().
Referenced by file_eq().
find()
int find (const mem & x, const char y)
Definition at line 2134 of file explore.cc.
 {
  const int l=get_length(x);
  for(int i=0;i<l;i++)
  {
   const char c=at(x,i);
   if(c==y)
    return i;
  }
  return -1;
 }
References at(), and get_length().
flower() [1/2]
void flower ()
Definition at line 2145 of file explore.cc.
 {
  flower("*");
 }
flower() [2/2]
void flower (const mem & x)
Definition at line 2149 of file explore.cc.
 {
  check(is_full(x));
  const int width=term_width();
  const mem m1=repeat(x,width);
  const mem m2=head(m1,width);
  print(m2);
 }
References check(), head(), is_full(), print(), repeat(), and term_width().
front() [1/6]
void front (buf & x, const char y)
Definition at line 2172 of file explore.cc.
 {
  check(is_full(x));
  set(x,0,y);
 }
References check(), is_full(), and set().
front() [2/6]
char front (const buf & x)
Definition at line 2167 of file explore.cc.
 {
  check(is_full(x));
  return at(x,0);
 }
References at(), check(), and is_full().
front() [3/6]
char front (const mem & x)
Definition at line 2157 of file explore.cc.
 {
  check(is_full(x));
  return at(x,0);
 }
References at(), check(), and is_full().
Referenced by front(), get_domain(), match_l(), shift(), trim_l(), and unshift().
front() [4/6]
mem front (const seq & x)
Definition at line 2191 of file explore.cc.
 {
  check(is_full(x));
  const mem m=front(x.text);
  return decode(m);
 }
References check(), decode(), front(), is_full(), and seq::text.
front() [5/6]
mem front (const txt & x)
Definition at line 2177 of file explore.cc.
 {
  check(is_full(x));
  buf b;
  const int l=get_length(x.buffer);
  for(int i=0;i<l;i++)
  {
   const char c=at(x.buffer,i);
   if(c=='\n')
    break;
   push(b,c);
  }
  return detach(b);
 }
References at(), txt::buffer, check(), detach(), get_length(), is_full(), and push().
front() [6/6]
void front (mem & x, const char y)
Definition at line 2162 of file explore.cc.
 {
  check(is_full(x));
  set(x,0,y);
 }
References check(), is_full(), and set().
fs_remove()
void fs_remove (const mem & x)
Definition at line 2197 of file explore.cc.
 {
  check(is_fs(x));
  const mem m=to_c(x);
  const char* p=get_address(m);
  const int n=remove(p);
  check(n==0);
 }
References check(), get_address(), is_fs(), remove(), and to_c().
Referenced by sort(), and translit().
fs_rename()
void fs_rename (const mem & x, const mem & y)
Definition at line 2205 of file explore.cc.
 {
  check(is_fs(x));
  const mem mx=to_c(x);
  const mem my=to_c(y);
  const char* px=get_address(mx);
  const char* py=get_address(my);
  const int n=rename(px,py);
  check(n==0);
 }
References check(), get_address(), is_fs(), and to_c().
Referenced by entry().
fs_stat()
struct stat fs_stat (const mem & x)
Definition at line 2205 of file explore.cc.
 {
  check(is_fs(x));
  const mem m=to_c(x);
  struct stat r;
  const char* p=get_address(m);
  const int n=stat(p,&r);
  check(n==0);
  return r;
 }
Referenced by file_mtime(), and file_size().
get()
mem get (const map & x, const mem & y)
Definition at line 2263 of file explore.cc.
 {
  check(is_full(y));
  map m=x;
  while(is_full(m))
  {
   const mem k=shift(m.keys);
   const mem v=shift(m.values);
   if(eq(k,y))
    return v;
  }
  stop();
  return {};
 }
References check(), eq(), is_full(), map::keys, shift(), stop(), and map::values.
Referenced by on_create().
get_address() [1/7]
const char* get_address (const mem & x)
Definition at line 2233 of file explore.cc.
 {
  return get_address(x,0);
 }
References get_address().
get_address() [2/7]
const char* get_address (const mem & x, const int y)
Definition at line 2255 of file explore.cc.
 {
  return get_address(x.pointer,y);
 }
References get_address(), and mem::pointer.
get_address() [3/7]
const char* get_address (const ptr & x, const int y)
Definition at line 2244 of file explore.cc.
 {
  const int l=get_length(x);
  check(y>=0);
  check(y<l);
  return x.pointer+y;
 }
References check(), get_length(), and ptr::pointer.
get_address() [4/7]
char* get_address (mem & x)
Definition at line 2229 of file explore.cc.
 {
  return get_address(x,0);
 }
References get_address().
get_address() [5/7]
char* get_address (mem & x, const int y)
Definition at line 2251 of file explore.cc.
 {
  return get_address(x.pointer,y);
 }
References get_address(), and mem::pointer.
get_address() [6/7]
char* get_address (ptr & x)
Definition at line 2225 of file explore.cc.
 {
  return get_address(x,0);
 }
Referenced by allocate(), assign(), at(), contain(), copy(), dir_change(), dir_current(), echo(), fs_remove(), fs_rename(), get_address(), is_dir(), is_file(), open(), os_system(), path_base(), path_dir(), path_real(), read(), receive(), send(), set(), to_hexa(), to_long(), to_mem(), unwrap(), wrap(), and write().
get_address() [7/7]
char* get_address (ptr & x, const int y)
Definition at line 2237 of file explore.cc.
 {
  const int l=get_length(x);
  check(y>=0);
  check(y<l);
  return x.pointer+y;
 }
References check(), get_length(), and ptr::pointer.
get_capacity()
int get_capacity (const buf & x)
Definition at line 2259 of file explore.cc.
 {
  return get_length(x.memory);
 }
References get_length(), and buf::memory.
Referenced by drop_l(), get_offset(), get_overhead(), is_circular(), is_filled(), push(), reserve(), and unshift().
get_date() [1/2]
mem get_date ()
Definition at line 2277 of file explore.cc.
 {
  const int n=time(0);
  check(n!=-1);
  return get_date(n);
 }
References check().
get_date() [2/2]
mem get_date (const int x)
Definition at line 2283 of file explore.cc.
 {
  const time_t t=x;
  const tm* p=localtime(&t);
  check(p!=0);
  const tm s=*p;
  const int m=s.tm_mon+1;
  const int y=s.tm_year+1900;
  const mem minute=pad_l(s.tm_min,2);
  const mem hour=pad_l(s.tm_hour,2);
  const mem day=pad_l(s.tm_mday,2);
  const mem month=pad_l(m,2);
  const mem year=to_mem(y);
  const mem date=concat(year,"/",month,"/",day);
  const mem time=concat(hour,"h",minute);
  return concat(date," ",time);
 }
References check(), concat(), pad_l(), and to_mem().
get_domain()
mem get_domain (const mem & x)
Definition at line 2300 of file explore.cc.
 {
  const mem command=concat("nslookup ",x);
  pfile f;
  open(f,command);
  const mem m1=read(f);
  try
  {
   clear(f);
  }
  catch(...)
  {
   return x;
  }
  const txt t1=to_txt(m1);
  const mem m2=front(t1);
  const txt t2=split(m2,'\t');
  const mem m3=back(t2);
  const txt t3=split(m3,' ');
  const mem m4=back(t3);
  return strip_r(m4,'.');
 }
References back(), clear(), concat(), front(), open(), read(), split(), strip_r(), and to_txt().
get_guid() [1/2]
mem get_guid ()
Definition at line 2322 of file explore.cc.
 {
  return get_guid(16);
 }
get_guid() [2/2]
mem get_guid (const int x)
Definition at line 2326 of file explore.cc.
 {
  check(x>0);
  buf b;
  reserve(b,x);
  for(int i=0;i<x;i++)
  {
   const int n=get_random(36);
   if(n<10)
   {
    const char c='0'+n;
    push(b,c);
   }
   else
   {
    const int v=n-10;
    const char c='a'+v;
    push(b,c);
   }
  }
  return detach(b);
 }
References check(), detach(), get_random(), push(), and reserve().
get_ip()
mem get_ip (const fd & x)
Definition at line 2348 of file explore.cc.
 {
  sockaddr_in a;
  socklen_t l=sizeof(a);
  const int n=getpeername(x.handle,(sockaddr*)&a,&l);
  check(n==0);
  const char* p=inet_ntoa(a.sin_addr);
  check(p!=0);
  return p;
 }
References check(), and fd::handle.
get_length() [1/3]
int get_length (const buf & x)
Definition at line 2366 of file explore.cc.
 {
  return x.length;
 }
References buf::length.
get_length() [2/3]
int get_length (const mem & x)
Definition at line 2362 of file explore.cc.
 {
  return get_length(x.pointer);
 }
References get_length(), and mem::pointer.
get_length() [3/3]
int get_length (const ptr & x)
Definition at line 2358 of file explore.cc.
 {
  return x.length;
 }
References ptr::length.
Referenced by allocate(), append(), assign(), at(), back(), contain(), copy(), count(), decode(), dir_current(), drop_l(), drop_r(), echo(), encode(), eq(), escape(), find(), front(), get_address(), get_capacity(), get_length(), get_offset(), glue(), head(), is_alnum(), is_alpha(), is_blank(), is_digit(), is_nl(), is_space(), join(), match_l(), match_r(), normalize(), pad_l(), pad_r(), pop(), prepend(), push(), receive(), repeat(), replace(), send(), set(), shift(), slice(), slice_l(), slice_r(), split(), strip_l(), strip_r(), tail(), to_buf(), to_hexa(), to_lower(), to_mem(), to_upper(), unlift(), unshift(), unwrap(), and write().
get_now()
double get_now ()
Definition at line 2370 of file explore.cc.
 {
  static thread_local const double origin=get_time();
  const double n=get_time();
  return n-origin;
 }
References get_time().
Referenced by clear(), and hit().
get_offset()
int get_offset (const buf & x, const int y)
Definition at line 2376 of file explore.cc.
 {
  const int l=get_length(x);
  check(y>=0);
  check(y<l);
  const int lx=get_capacity(x);
  const int n=x.index+y;
  return n%lx;
 }
References check(), get_capacity(), get_length(), and buf::index.
Referenced by at(), and set().
get_overhead()
int get_overhead (const buf & x)
Definition at line 2385 of file explore.cc.
 {
  const int l=get_capacity(x);
  return l-x.length;
 }
References get_capacity(), and buf::length.
get_random()
int get_random (const int x)
Definition at line 2390 of file explore.cc.
 {
  check(x>=0);
  int v=0;
  int n=0;
  while(n<x)
  {
   const int i=rand();
   v+=i;
   n+=RAND_MAX;
  }
  return v%x;
 }
References check().
Referenced by get_guid(), and shuffle().
get_time()
double get_time ()
Definition at line 2403 of file explore.cc.
 {
  timespec spec;
  const int n=clock_gettime(CLOCK_MONOTONIC,&spec);
  check(n==0);
  const double s=spec.tv_sec;
  const double t=spec.tv_nsec/10e9;
  return s+t;
 }
References check().
Referenced by get_now().
glue() [1/6]
mem glue (const seq & x)
Definition at line 2416 of file explore.cc.
 {
  return glue(x,'\n');
 }
References glue().
glue() [2/6]
mem glue (const seq & x, const char y)
Definition at line 2429 of file explore.cc.
 {
  mem r=join(x,y);
  if(is_empty(r))
   return r;
  check(match_r(r,y));
  drop_r(r);
  return r;
 }
References check(), drop_r(), is_empty(), join(), and match_r().
glue() [3/6]
mem glue (const seq & x, const mem & y)
Definition at line 2448 of file explore.cc.
 {
  mem r=join(x,y);
  if(is_empty(r))
   return r;
  check(match_r(r,y));
  const int l=get_length(y);
  drop_r(r,l);
  return r;
 }
References check(), drop_r(), get_length(), is_empty(), join(), and match_r().
glue() [4/6]
mem glue (const txt & x)
Definition at line 2412 of file explore.cc.
 {
  return glue(x,'\n');
 }
Referenced by compact(), glue(), path_name(), and path_unique().
glue() [5/6]
mem glue (const txt & x, const char y)
Definition at line 2420 of file explore.cc.
 {
  mem r=join(x,y);
  if(is_empty(r))
   return r;
  check(match_r(r,y));
  drop_r(r);
  return r;
 }
References check(), drop_r(), is_empty(), join(), and match_r().
glue() [6/6]
mem glue (const txt & x, const mem & y)
Definition at line 2438 of file explore.cc.
 {
  mem r=join(x,y);
  if(is_empty(r))
   return r;
  check(match_r(r,y));
  const int l=get_length(y);
  drop_r(r,l);
  return r;
 }
References check(), drop_r(), get_length(), is_empty(), join(), and match_r().
has()
bool has (map & x, const mem & y)
Definition at line 2458 of file explore.cc.
 {
  check(is_full(y));
  return contain(x.keys,y);
 }
References check(), contain(), is_full(), and map::keys.
Referenced by set().
head() [1/2]
mem head (const buf & x, const int y)
Definition at line 2471 of file explore.cc.
 {
  check(y>=0);
  const int l=get_length(x);
  if(l<=y)
   return x;
  return slice_l(x,y);
 }
References check(), get_length(), and slice_l().
head() [2/2]
mem head (const mem & x, const int y)
Definition at line 2463 of file explore.cc.
 {
  check(y>=0);
  const int l=get_length(x);
  if(l<=y)
   return x;
  return slice_l(x,y);
 }
References check(), get_length(), and slice_l().
Referenced by flower(), title_l(), and to_mem().
hit()
bool hit (const timer & x)
Definition at line 2479 of file explore.cc.
 {
  const double end=x.start+x.duration;
  const double now=get_now();
  return now>end;
 }
References timer::duration, get_now(), and timer::start.
Referenced by send().
implode() [1/2]
mem implode (const seq & x)
Definition at line 2496 of file explore.cc.
 {
  mem r;
  seq s=x;
  while(is_full(s))
  {
   const mem m=shift(s);
   append(r,m);
  }
  return r;
 }
References append(), is_full(), and shift().
implode() [2/2]
mem implode (const txt & x)
Definition at line 2485 of file explore.cc.
 {
  mem r;
  txt t=x;
  while(is_full(t))
  {
   const mem m=shift(t);
   append(r,m);
  }
  return r;
 }
References append(), is_full(), and shift().
is_alnum() [1/2]
bool is_alnum (const char x)
Definition at line 2507 of file explore.cc.
 {
  if(x=='_')
   return true;
  if(is_alpha(x))
   return true;
  if(is_digit(x))
   return true;
  return false;
 }
References is_alpha(), and is_digit().
Referenced by delimit(), escape(), and is_alnum().
is_alnum() [2/2]
bool is_alnum (const mem & x)
Definition at line 2517 of file explore.cc.
 {
  if(is_empty(x))
   return false;
  const int l=get_length(x);
  for(int i=0;i<l;i++)
  {
   const char c=at(x,i);
   if(!is_alnum(c))
    return false;
  }
  return true;
 }
References at(), get_length(), is_alnum(), and is_empty().
is_alpha() [1/2]
bool is_alpha (const char x)
Definition at line 2530 of file explore.cc.
 {
  static thread_local const mem low="abcdefghijklmnopqrstuvwxyz";
  static thread_local const mem up="ABCDEFGHIJKLMNOPQRSTUVWXYZ";
  if(contain(low,x))
   return true;
  if(contain(up,x))
   return true;
  return false;
 }
References contain().
Referenced by is_alnum(), and is_alpha().
is_alpha() [2/2]
bool is_alpha (const mem & x)
Definition at line 2540 of file explore.cc.
 {
  if(is_empty(x))
   return false;
  const int l=get_length(x);
  for(int i=0;i<l;i++)
  {
   const char c=at(x,i);
   if(!is_alpha(c))
    return false;
  }
  return true;
 }
References at(), get_length(), is_alpha(), and is_empty().
is_blank() [1/2]
bool is_blank (const char x)
Definition at line 2553 of file explore.cc.
 {
  if(x==' ')
   return true;
  if(x=='\t')
   return true;
  if(x=='\n')
   return true;
  if(x=='\r')
   return true;
  return false;
 }
Referenced by is_blank(), trim_l(), and trim_r().
is_blank() [2/2]
bool is_blank (const mem & x)
Definition at line 2565 of file explore.cc.
 {
  if(is_empty(x))
   return true;
  const int l=get_length(x);
  for(int i=0;i<l;i++)
  {
   const char c=at(x,i);
   if(!is_blank(c))
    return false;
  }
  return true;
 }
References at(), get_length(), is_blank(), and is_empty().
is_circular()
bool is_circular (const buf & x)
Definition at line 2578 of file explore.cc.
 {
  const int l=get_capacity(x);
  const int n=x.index+x.length;
  return n>l;
 }
References get_capacity(), buf::index, and buf::length.
Referenced by copy().
is_digit() [1/2]
bool is_digit (const char x)
Definition at line 2584 of file explore.cc.
 {
  static thread_local const mem m="0123456789";
  return contain(m,x);
 }
References contain().
Referenced by is_alnum(), is_digit(), and path_unique().
is_digit() [2/2]
bool is_digit (const mem & x)
Definition at line 2589 of file explore.cc.
 {
  const int l=get_length(x);
  for(int i=0;i<l;i++)
  {
   const char c=at(x,i);
   if(!is_digit(c))
    return false;
  }
  return true;
 }
References at(), get_length(), and is_digit().
is_dir()
bool is_dir (const mem & x)
Definition at line 2600 of file explore.cc.
 {
  const mem m=to_c(x);
  struct stat s;
  const char* p=get_address(m);
  const int n=stat(p,&s);
  if(n!=0)
   return false;
  return S_ISDIR(s.st_mode);
 }
References get_address(), and to_c().
Referenced by dir_clean(), dir_copy(), dir_find(), dir_list(), dir_locate(), dir_make(), dir_remove(), file_copy(), is_fs(), path_resolve(), and save().
is_empty() [1/11]
bool is_empty (const buf & x)
Definition at line 2614 of file explore.cc.
 {
  return x.length==0;
 }
References buf::length.
is_empty() [2/11]
bool is_empty (const fd & x)
Definition at line 2632 of file explore.cc.
 {
  return x.handle<0;
 }
References fd::handle.
is_empty() [3/11]
bool is_empty (const grid & x)
Definition at line 2648 of file explore.cc.
 {
  return is_empty(x.cells);
 }
References grid::cells, and is_empty().
is_empty() [4/11]
bool is_empty (const map & x)
Definition at line 2644 of file explore.cc.
 {
  return is_empty(x.keys);
 }
References is_empty(), and map::keys.
is_empty() [5/11]
bool is_empty (const mem & x)
Definition at line 2618 of file explore.cc.
 {
  return is_empty(x.pointer);
 }
References is_empty(), and mem::pointer.
is_empty() [6/11]
bool is_empty (const pfile & x)
Definition at line 2636 of file explore.cc.
 {
  return x.pointer==0;
 }
References pfile::pointer.
is_empty() [7/11]
bool is_empty (const pthread & x)
Definition at line 2640 of file explore.cc.
 {
  return x.pointer==0;
 }
References pthread::pointer.
is_empty() [8/11]
bool is_empty (const ptr & x)
Definition at line 2610 of file explore.cc.
 {
  return x.length==0;
 }
References ptr::length.
Referenced by allocate(), clear(), compact(), contain(), delimit(), echo(), glue(), is_alnum(), is_alpha(), is_blank(), is_empty(), is_full(), is_nl(), is_space(), match_l(), match_r(), read(), replace(), sort(), to_mem(), trim_r(), and write().
is_empty() [9/11]
bool is_empty (const seq & x)
Definition at line 2628 of file explore.cc.
 {
  return is_empty(x.text);
 }
References is_empty(), and seq::text.
is_empty() [10/11]
bool is_empty (const tbl & x)
Definition at line 2652 of file explore.cc.
 {
  return is_empty(x.cells);
 }
References tbl::cells, and is_empty().
is_empty() [11/11]
bool is_empty (const txt & x)
Definition at line 2622 of file explore.cc.
 {
  if(is_full(x.buffer))
   check(back(x.buffer)=='\n');
  return is_empty(x.buffer);
 }
References back(), txt::buffer, check(), is_empty(), and is_full().
is_file()
bool is_file (const mem & x)
Definition at line 2656 of file explore.cc.
 {
  const mem m=to_c(x);
  struct stat s;
  const char* p=get_address(m);
  const int n=stat(p,&s);
  if(n!=0)
   return false;
  return S_ISREG(s.st_mode);
 }
References get_address(), and to_c().
Referenced by dir_find(), file_copy(), file_eq(), file_locate(), file_mtime(), file_size(), is_fs(), and save().
is_filled()
bool is_filled (const buf & x)
Definition at line 2666 of file explore.cc.
 {
  const int l=get_capacity(x);
  return x.length==l;
 }
References get_capacity(), and buf::length.
Referenced by is_normal(), push(), and unshift().
is_fs()
bool is_fs (const mem & x)
Definition at line 2671 of file explore.cc.
 {
  if(is_dir(x))
   return true;
  if(is_file(x))
   return true;
  return false;
 }
References is_dir(), and is_file().
Referenced by dir_make(), fs_remove(), fs_rename(), path_resolve(), and path_unique().
is_full() [1/11]
bool is_full (const buf & x)
Definition at line 2687 of file explore.cc.
 {
  return !is_empty(x);
 }
References is_empty().
is_full() [2/11]
bool is_full (const fd & x)
Definition at line 2691 of file explore.cc.
 {
  return !is_empty(x);
 }
References is_empty().
is_full() [3/11]
bool is_full (const grid & x)
Definition at line 2715 of file explore.cc.
 {
  return !is_empty(x);
 }
References is_empty().
is_full() [4/11]
bool is_full (const map & x)
Definition at line 2711 of file explore.cc.
 {
  return !is_empty(x);
 }
References is_empty().
is_full() [5/11]
bool is_full (const mem & x)
Definition at line 2683 of file explore.cc.
 {
  return !is_empty(x);
 }
References is_empty().
is_full() [6/11]
bool is_full (const pfile & x)
Definition at line 2695 of file explore.cc.
 {
  return !is_empty(x);
 }
References is_empty().
is_full() [7/11]
bool is_full (const pthread & x)
Definition at line 2699 of file explore.cc.
 {
  return !is_empty(x);
 }
References is_empty().
is_full() [8/11]
bool is_full (const ptr & x)
Definition at line 2679 of file explore.cc.
 {
  return !is_empty(x);
 }
References is_empty().
Referenced by back(), compact(), contain(), decode(), delimit(), deserialize(), dir_find(), dir_list(), dir_locate(), doc_generate(), drop_l(), drop_r(), dump(), file_locate(), flower(), front(), get(), has(), implode(), is_empty(), join(), open(), path_unique(), pop(), put(), replace(), send(), serialize(), shift(), shuffle(), split(), term_hit(), title_l(), title_r(), to_mem(), to_seq(), to_txt(), trim_l(), trim_r(), and write().
is_full() [9/11]
bool is_full (const seq & x)
Definition at line 2703 of file explore.cc.
 {
  return !is_empty(x);
 }
References is_empty().
is_full() [10/11]
bool is_full (const tbl & x)
Definition at line 2719 of file explore.cc.
 {
  return !is_empty(x);
 }
References is_empty().
is_full() [11/11]
bool is_full (const txt & x)
Definition at line 2707 of file explore.cc.
 {
  return !is_empty(x);
 }
References is_empty().
is_line()
bool is_line (const mem & x)
Definition at line 2723 of file explore.cc.
 {
  return !is_text(x);
 }
References is_text().
is_nl() [1/2]
bool is_nl (const char x)
Definition at line 2727 of file explore.cc.
 {
  if(x=='\n')
   return true;
  if(x=='\r')
   return true;
  return false;
 }
Referenced by delimit(), and is_nl().
is_nl() [2/2]
bool is_nl (const mem & x)
Definition at line 2735 of file explore.cc.
 {
  if(is_empty(x))
   return true;
  const int l=get_length(x);
  for(int i=0;i<l;i++)
  {
   const char c=at(x,i);
   if(!is_nl(c))
    return false;
  }
  return false;
 }
References at(), get_length(), is_empty(), and is_nl().
is_normal()
bool is_normal (const buf & x)
Definition at line 2748 of file explore.cc.
 {
  if(x.index>0)
   return false;
  return is_filled(x);
 }
References buf::index, and is_filled().
Referenced by detach(), and normalize().
is_punct()
bool is_punct (const char x)
Definition at line 2754 of file explore.cc.
 {
  static thread_local const mem m="!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~";
  return contain(m,x);
 }
References contain().
Referenced by escape().
is_space() [1/2]
bool is_space (const char x)
Definition at line 2759 of file explore.cc.
 {
  if(x==' ')
   return true;
  if(x=='\t')
   return true;
  return false;
 }
Referenced by delimit(), and is_space().
is_space() [2/2]
bool is_space (const mem & x)
Definition at line 2767 of file explore.cc.
 {
  if(is_empty(x))
   return true;
  const int l=get_length(x);
  for(int i=0;i<l;i++)
  {
   const char c=at(x,i);
   if(!is_space(c))
    return false;
  }
  return true;
 }
References at(), get_length(), is_empty(), and is_space().
is_text()
bool is_text (const mem & x)
Definition at line 2780 of file explore.cc.
 {
  if(contain(x,'\r'))
   return true;
  if(contain(x,'\n'))
   return true;
  return false;
 }
References contain().
Referenced by is_line().
join() [1/6]
mem join (const seq & x)
Definition at line 2792 of file explore.cc.
 {
  return join(x,'\n');
 }
References join().
join() [2/6]
mem join (const seq & x, const char y)
Definition at line 2808 of file explore.cc.
 {
  mem r;
  seq t=x;
  while(is_full(t))
  {
   const mem m=shift(t);
   append(r,m);
   push(r,y);
  }
  return r;
 }
References append(), is_full(), push(), and shift().
join() [3/6]
mem join (const seq & x, const mem & y)
Definition at line 2832 of file explore.cc.
 {
  mem r;
  seq t=x;
  while(is_full(t))
  {
   const mem m=shift(t);
   append(r,m);
   append(r,y);
  }
  return r;
 }
References append(), is_full(), and shift().
join() [4/6]
mem join (const txt & x)
Definition at line 2788 of file explore.cc.
 {
  return to_mem(x);
 }
References to_mem().
Referenced by dir_locate(), doc_generate(), file_locate(), glue(), and join().
join() [5/6]
mem join (const txt & x, const char y)
Definition at line 2796 of file explore.cc.
 {
  mem r=to_mem(x);
  const int l=get_length(r);
  for(int i=0;i<l;i++)
  {
   const char c=at(r,i);
   if(c=='\n')
    set(r,i,y);
  }
  return r;
 }
References at(), get_length(), set(), and to_mem().
join() [6/6]
mem join (const txt & x, const mem & y)
Definition at line 2820 of file explore.cc.
 {
  mem r;
  txt t=x;
  while(is_full(t))
  {
   const mem m=shift(t);
   append(r,m);
   append(r,y);
  }
  return r;
 }
References append(), is_full(), and shift().
lift() [1/3]
void* lift (const map & x)
Definition at line 2857 of file explore.cc.
 {
  mem m;
  serialize(m,x);
  return lift(m);
 }
References lift(), and serialize().
lift() [2/3]
void* lift (const mem & x)
Definition at line 2844 of file explore.cc.
 {
  mem m=encode(x);
  push(m,'\n');
  const ptr p=detach(m);
  return p.pointer;
 }
References detach(), encode(), ptr::pointer, and push().
Referenced by create(), and lift().
lift() [3/3]
void* lift (const txt & x)
Definition at line 2851 of file explore.cc.
 {
  mem m;
  serialize(m,x);
  return lift(m);
 }
References lift(), and serialize().
listen()
void listen (fd & x, const int y)
Definition at line 2863 of file explore.cc.
 {
  clear(x);
  x.handle=socket(AF_INET,SOCK_STREAM,0);
  check(x.handle>=0);
  const int on=1;
  const int n1=setsockopt(x.handle,SOL_SOCKET,SO_REUSEADDR,&on,sizeof(on));
  check(n1==0);
  struct sockaddr_in a;
  a.sin_family=AF_INET;
  a.sin_addr.s_addr=htonl(INADDR_ANY);
  a.sin_port=htons(y);
  const int n2=bind(x.handle,(sockaddr*)&a,sizeof(a));
  check(n2==0);
  const int n3=listen(x.handle,8);
  check(n3==0);
  set_non_block(x);
 }
References check(), clear(), fd::handle, and set_non_block().
load()
mem load (const mem & x)
Definition at line 2881 of file explore.cc.
 {
  fd f;
  open(f,x);
  return read(f);
 }
References open(), and read().
Referenced by file_eq(), and save().
main()
int main (const int x, const char ** y)
Definition at line 2887 of file explore.cc.
 {
  const int n=time(0);
  srand(n);
  txt t;
  for(int i=0;i<x;i++)
  {
   const char* p=y[i];
   push(t,p);
  }
  entry(t);
  return 0;
 }
References entry(), and push().
match_l() [1/4]
bool match_l (const buf & x, const char y)
Definition at line 2907 of file explore.cc.
 {
  if(is_empty(x))
   return false;
  const char c=front(x);
  return c==y;
 }
References front(), and is_empty().
match_l() [2/4]
bool match_l (const buf & x, const mem & y)
Definition at line 2933 of file explore.cc.
 {
  if(is_empty(x))
   return false;
  if(is_empty(y))
   return false;
  const int lx=get_length(x);
  const int ly=get_length(y);
  if(ly>lx)
   return false;
  for(int i=0;i<ly;i++)
  {
   const char cx=at(x,i);
   const char cy=at(y,i);
   if(cx!=cy)
    return false;
  }
  return true;
 }
References at(), get_length(), and is_empty().
match_l() [3/4]
bool match_l (const mem & x, const char y)
Definition at line 2900 of file explore.cc.
 {
  if(is_empty(x))
   return false;
  const char c=front(x);
  return c==y;
 }
References front(), and is_empty().
Referenced by decode(), replace(), split(), strip_l(), and to_txt().
match_l() [4/4]
bool match_l (const mem & x, const mem & y)
Definition at line 2914 of file explore.cc.
 {
  if(is_empty(x))
   return false;
  if(is_empty(y))
   return false;
  const int lx=get_length(x);
  const int ly=get_length(y);
  if(ly>lx)
   return false;
  for(int i=0;i<ly;i++)
  {
   const char cx=at(x,i);
   const char cy=at(y,i);
   if(cx!=cy)
    return false;
  }
  return true;
 }
References at(), get_length(), and is_empty().
match_r() [1/4]
bool match_r (const buf & x, const char y)
Definition at line 2959 of file explore.cc.
 {
  if(is_empty(x))
   return false;
  const char c=back(x);
  return c==y;
 }
References back(), and is_empty().
match_r() [2/4]
bool match_r (const buf & x, const mem & y)
Definition at line 2985 of file explore.cc.
 {
  if(is_empty(x))
   return false;
  if(is_empty(y))
   return false;
  const int lx=get_length(x);
  const int ly=get_length(y);
  if(ly>lx)
   return false;
  for(int i=0;i<ly;i++)
  {
   const char cx=back(x,i);
   const char cy=back(y,i);
   if(cx!=cy)
    return false;
  }
  return true;
 }
References back(), get_length(), and is_empty().
match_r() [3/4]
bool match_r (const mem & x, const char y)
Definition at line 2952 of file explore.cc.
 {
  if(is_empty(x))
   return false;
  const char c=back(x);
  return c==y;
 }
References back(), and is_empty().
Referenced by glue(), strip_r(), and to_txt().
match_r() [4/4]
bool match_r (const mem & x, const mem & y)
Definition at line 2966 of file explore.cc.
 {
  if(is_empty(x))
   return false;
  if(is_empty(y))
   return false;
  const int lx=get_length(x);
  const int ly=get_length(y);
  if(ly>lx)
   return false;
  for(int i=0;i<ly;i++)
  {
   const char cx=back(x,i);
   const char cy=back(y,i);
   if(cx!=cy)
    return false;
  }
  return true;
 }
References back(), get_length(), and is_empty().
move() [1/9]
void move (buf & x, buf & y)
Definition at line 3014 of file explore.cc.
 {
  swap(x,y);
  clear(y);
 }
References clear(), and swap().
move() [2/9]
void move (grid & x, grid & y)
Definition at line 3039 of file explore.cc.
 {
  swap(x,y);
  clear(y);
 }
References clear(), and swap().
move() [3/9]
void move (map & x, map & y)
Definition at line 3029 of file explore.cc.
 {
  swap(x,y);
  clear(y);
 }
References clear(), and swap().
move() [4/9]
void move (mem & x, mem & y)
Definition at line 3009 of file explore.cc.
 {
  swap(x,y);
  clear(y);
 }
References clear(), and swap().
move() [5/9]
void move (ptr & x, ptr & y)
Definition at line 3004 of file explore.cc.
 {
  swap(x,y);
  clear(y);
 }
References clear(), and swap().
Referenced by deserialize(), remove(), serialize(), and shuffle().
move() [6/9]
void move (seq & x, seq & y)
Definition at line 3024 of file explore.cc.
 {
  swap(x,y);
  clear(y);
 }
References clear(), and swap().
move() [7/9]
void move (tbl & x, tbl & y)
Definition at line 3044 of file explore.cc.
 {
  swap(x,y);
  clear(y);
 }
References clear(), and swap().
move() [8/9]
void move (timer & x, timer & y)
Definition at line 3034 of file explore.cc.
 {
  swap(x,y);
  clear(y);
 }
References clear(), and swap().
move() [9/9]
void move (txt & x, txt & y)
Definition at line 3019 of file explore.cc.
 {
  swap(x,y);
  clear(y);
 }
References clear(), and swap().
neq() [1/2]
bool neq (const buf & x, const buf & y)
Definition at line 3053 of file explore.cc.
 {
  return !eq(x,y);
 }
References eq().
neq() [2/2]
bool neq (const mem & x, const mem & y)
Definition at line 3049 of file explore.cc.
 {
  return !eq(x,y);
 }
References eq().
normalize()
void normalize (buf & x)
Definition at line 3057 of file explore.cc.
 {
  if(is_normal(x))
   return;
  mem m=to_mem(x);
  reset(x);
  swap(x.memory,m);
  const int l=get_length(x.memory);
  x.length=l;
 }
References get_length(), is_normal(), buf::length, buf::memory, reset(), swap(), and to_mem().
on_create()
void* on_create (void * x)
Definition at line 1414 of file explore.cc.
 {
  check(x!=0);
  map m1;
  unlift(m1,x);
  const mem m2=get(m1,"routine");
  const mem m3=get(m1,"arguments");
  void* p=0;
  unwrap(p,m2);
  void (*routine)(const map&)=(void (*)(const map&))p;
  map arguments;
  unwrap(arguments,m3);
  routine(arguments);
  return 0;
 }
References check(), get(), unlift(), and unwrap().
Referenced by create().
open() [1/3]
void open (fd & x, const mem & y)
Definition at line 3067 of file explore.cc.
 {
  open(x,y,O_RDONLY);
 }
Referenced by get_domain(), load(), open(), os_execute(), and save().
open() [2/3]
void open (fd & x, const mem & y, const int z)
Definition at line 3071 of file explore.cc.
 {
  clear(x);
  const mem m=to_c(y);
  const char* p=get_address(m);
  x.handle=open(p,z,0644);
  check(is_full(x));
 }
References check(), clear(), get_address(), fd::handle, is_full(), open(), and to_c().
open() [3/3]
void open (pfile & x, const mem & y)
Definition at line 3079 of file explore.cc.
 {
  clear(x);
  const mem m=to_c(y);
  const char* p=get_address(m);
  x.pointer=popen(p,"r");
  check(is_full(x));
 }
References check(), clear(), get_address(), is_full(), pfile::pointer, and to_c().
os_execute()
mem os_execute (const mem & x)
Definition at line 3087 of file explore.cc.
 {
  print(concat("> ",x));
  pfile f;
  open(f,x);
  const mem r=read(f);
  clear(f);
  return r;
 }
References clear(), concat(), open(), print(), and read().
Referenced by dir_copy(), dir_find(), dir_list(), dir_make(), dir_remove(), file_copy(), sort(), term_width(), and translit().
os_system() [1/2]
int os_system (const mem & x)
Definition at line 3096 of file explore.cc.
 {
  const mem m=to_c(x);
  const char* p=get_address(m);
  return system(p);
 }
References get_address(), and to_c().
Referenced by doc_generate(), entry(), and os_system().
os_system() [2/2]
int os_system (const mem & x, const mem & y)
Definition at line 3102 of file explore.cc.
 {
  int r=0;
  const mem previous=dir_current();
  dir_change(x);
  try
  {
   r=os_system(y);
  }
  catch(...)
  {
   dir_change(previous);
   throw;
  }
  dir_change(previous);
  return r;
 }
References dir_change(), dir_current(), and os_system().
pad_l() [1/2]
mem pad_l (const int x, const int y)
Definition at line 3119 of file explore.cc.
 {
  check(y>=0);
  const mem m=to_mem(x);
  return pad_l(m,y,'0');
 }
References check(), and to_mem().
Referenced by escape(), and get_date().
pad_l() [2/2]
mem pad_l (const mem & x, const int y, const char z)
Definition at line 3125 of file explore.cc.
 {
  check(y>=0);
  mem r=x;
  while(true)
  {
   const int l=get_length(r);
   if(l>=y)
    break;
   unshift(r,z);
  }
  return r;
 }
References check(), get_length(), and unshift().
pad_r() [1/2]
mem pad_r (const int x, const int y)
Definition at line 3138 of file explore.cc.
 {
  check(y>=0);
  const mem m=to_mem(x);
  return pad_r(m,y,'0');
 }
References check(), and to_mem().
pad_r() [2/2]
mem pad_r (const mem & x, const int y, const char z)
Definition at line 3144 of file explore.cc.
 {
  check(y>=0);
  mem r=x;
  while(true)
  {
   const int l=get_length(r);
   if(l>=y)
    break;
   push(r,z);
  }
  return r;
 }
References check(), get_length(), and push().
path_base()
mem path_base (const mem & x)
Definition at line 3157 of file explore.cc.
 {
  mem m=to_c(x);
  char* p=get_address(m);
  return basename(p);
 }
References get_address(), and to_c().
Referenced by doc_generate(), file_copy(), path_ext(), path_name(), path_resolve(), and path_tmp().
path_concat()
mem path_concat (const mem & x, const mem & y)
Definition at line 3163 of file explore.cc.
 {
  return concat(x,"/",y);
 }
References concat().
Referenced by dir_list(), dir_locate(), doc_generate(), entry(), file_copy(), file_locate(), path_resolve(), and path_tmp().
path_dir()
mem path_dir (const mem & x)
Definition at line 3167 of file explore.cc.
 {
  mem m=to_c(x);
  char* p=get_address(m);
  return dirname(p);
 }
References get_address(), and to_c().
Referenced by path_resolve(), path_tmp(), path_unique(), and save().
path_ext()
mem path_ext (const mem & x)
Definition at line 3173 of file explore.cc.
 {
  const mem base=path_base(x);
  txt t=split(base,'.');
  const int l=count(t);
  if(l<2)
   return "";
  return pop(t);
 }
References count(), path_base(), pop(), and split().
Referenced by path_unique().
path_name()
mem path_name (const mem & x)
Definition at line 3182 of file explore.cc.
 {
  const mem base=path_base(x);
  txt t=split(base,'.');
  const int l=count(t);
  if(l>1)
   drop_r(t);
  return glue(t,'.');
 }
References count(), drop_r(), glue(), path_base(), and split().
Referenced by path_unique().
path_real()
mem path_real (const mem & x)
Definition at line 3191 of file explore.cc.
 {
  const mem m=to_c(x);
  mem result;
  allocate(result,PATH_MAX);
  const char* p=get_address(m);
  char* presult=get_address(result);
  char* r=realpath(p,presult);
  check(r!=0);
  return r;
 }
References allocate(), check(), get_address(), and to_c().
Referenced by dir_find(), dir_list(), dir_locate(), file_locate(), and path_resolve().
path_resolve()
mem path_resolve (const mem & x)
Definition at line 3202 of file explore.cc.
 {
  if(is_fs(x))
   return path_real(x);
  const mem dir1=path_dir(x);
  if(is_dir(dir1))
  {
   const mem dir2=path_real(dir1);
   const mem base=path_base(x);
   return path_concat(dir2,base);
  }
  return x;
 }
References is_dir(), is_fs(), path_base(), path_concat(), path_dir(), and path_real().
Referenced by path_unique().
path_tmp()
mem path_tmp (const mem & x)
Definition at line 3215 of file explore.cc.
 {
  const mem dir1=dir_locate("tmp");
  const mem dir2=path_dir(x);
  const mem dir3=path_concat(dir1,dir2);
  const mem base=path_base(x);
  const mem path=path_concat(dir3,base);
  return path_unique(path);
 }
References dir_locate(), path_base(), path_concat(), path_dir(), and path_unique().
Referenced by sort(), and translit().
path_unique()
mem path_unique (const mem & x)
Definition at line 3224 of file explore.cc.
 {
  const mem dir=path_dir(x);
  const mem name1=path_name(x);
  const mem ext=path_ext(x);
  txt t=split(name1,'-');
  const mem last=back(t);
  if(is_digit(last))
   drop_r(t);
  const mem name2=glue(t,'-');
  buf b;
  for(int i=0;;i++)
  {
   const mem n=to_mem(i);
   reset(b);
   append(b,dir);
   append(b,"/");
   append(b,name2);
   if(i>0)
   {
    append(b,"-");
    append(b,n);
   }
   if(is_full(ext))
   {
    append(b,".");
    append(b,ext);
   }
   if(!is_fs(b))
    break;
  }
  const mem path=detach(b);
  return path_resolve(path);
 }
References append(), back(), detach(), drop_r(), glue(), is_digit(), is_fs(), is_full(), path_dir(), path_ext(), path_name(), path_resolve(), reset(), split(), and to_mem().
Referenced by path_tmp().
pop() [1/6]
char pop (buf & x)
Definition at line 3274 of file explore.cc.
 {
  check(is_full(x));
  const char r=back(x);
  drop_r(x);
  return r;
 }
References back(), check(), drop_r(), and is_full().
pop() [2/6]
mem pop (buf & x, const int y)
Definition at line 3281 of file explore.cc.
 {
  const int l=get_length(x);
  check(y>=0);
  check(y<=l);
  const mem r=slice_r(x,y);
  drop_r(x,y);
  return r;
 }
References check(), drop_r(), get_length(), and slice_r().
pop() [3/6]
char pop (mem & x)
Definition at line 3258 of file explore.cc.
 {
  check(is_full(x));
  const char r=back(x);
  drop_r(x);
  return r;
 }
References back(), check(), drop_r(), and is_full().
Referenced by path_ext(), and to_mem().
pop() [4/6]
mem pop (mem & x, const int y)
Definition at line 3265 of file explore.cc.
 {
  const int l=get_length(x);
  check(y>=0);
  check(y<=l);
  const mem r=slice_r(x,y);
  drop_r(x,y);
  return r;
 }
References check(), drop_r(), get_length(), and slice_r().
pop() [5/6]
mem pop (seq & x)
Definition at line 3297 of file explore.cc.
 {
  check(is_full(x));
  const mem r=back(x);
  drop_r(x);
  return r;
 }
References back(), check(), drop_r(), and is_full().
pop() [6/6]
mem pop (txt & x)
Definition at line 3290 of file explore.cc.
 {
  check(is_full(x));
  const mem r=back(x);
  drop_r(x);
  return r;
 }
References back(), check(), drop_r(), and is_full().
prepend() [1/6]
void prepend (buf & x, const buf & y)
Definition at line 3330 of file explore.cc.
 {
  const int lx=get_length(x);
  const int ly=get_length(y);
  const int l=lx+ly;
  reserve(x,l);
  for(int i=0;i<ly;i++)
  {
   const char c=back(y,i);
   unshift(x,c);
  }
 }
References back(), get_length(), reserve(), and unshift().
prepend() [2/6]
void prepend (buf & x, const char * y)
Definition at line 3313 of file explore.cc.
 {
  const mem m=y;
  prepend(x,m);
 }
References prepend().
prepend() [3/6]
void prepend (buf & x, const mem & y)
Definition at line 3318 of file explore.cc.
 {
  const int lx=get_length(x);
  const int ly=get_length(y);
  const int l=lx+ly;
  reserve(x,l);
  for(int i=0;i<ly;i++)
  {
   const char c=back(y,i);
   unshift(x,c);
  }
 }
References back(), get_length(), reserve(), and unshift().
prepend() [4/6]
void prepend (mem & x, const mem & y)
Definition at line 3304 of file explore.cc.
 {
  const int lx=get_length(x);
  const int ly=get_length(y);
  const int l=lx+ly;
  allocate(x,l);
  copy(x,lx,0,lx);
  copy(x,0,y,0,ly);
 }
References allocate(), copy(), and get_length().
Referenced by prepend(), and unshift().
prepend() [5/6]
void prepend (seq & x, const seq & y)
Definition at line 3346 of file explore.cc.
 {
  prepend(x.text,y.text);
 }
References prepend(), and seq::text.
prepend() [6/6]
void prepend (txt & x, const txt & y)
Definition at line 3342 of file explore.cc.
 {
  prepend(x.buffer,y.buffer);
 }
References txt::buffer, and prepend().
print() [1/15]
void print ()
Definition at line 3350 of file explore.cc.
 {
  echo("\n");
 }
References echo().
Referenced by dump(), flower(), os_execute(), report(), title_l(), and title_r().
print() [2/15]
void print (const bool x)
Definition at line 3354 of file explore.cc.
 {
  echo(x);
  echo("\n");
 }
References echo().
print() [3/15]
void print (const buf & x)
Definition at line 3399 of file explore.cc.
 {
  echo(x);
  echo("\n");
 }
References echo().
print() [4/15]
void print (const char * x)
Definition at line 3404 of file explore.cc.
 {
  check(x!=0);
  echo(x);
  echo("\n");
 }
References check(), and echo().
print() [5/15]
void print (const char x)
Definition at line 3359 of file explore.cc.
 {
  echo(x);
  echo("\n");
 }
References echo().
print() [6/15]
void print (const double x)
Definition at line 3384 of file explore.cc.
 {
  echo(x);
  echo("\n");
 }
References echo().
print() [7/15]
void print (const int x)
Definition at line 3364 of file explore.cc.
 {
  echo(x);
  echo("\n");
 }
References echo().
print() [8/15]
void print (const long x)
Definition at line 3374 of file explore.cc.
 {
  echo(x);
  echo("\n");
 }
References echo().
print() [9/15]
void print (const map & x)
Definition at line 3418 of file explore.cc.
 {
  dump(x);
 }
References dump().
print() [10/15]
void print (const mem & x)
Definition at line 3394 of file explore.cc.
 {
  echo(x);
  echo("\n");
 }
References echo().
print() [11/15]
void print (const seq & x)
Definition at line 3414 of file explore.cc.
 {
  dump(x.text);
 }
References dump(), and seq::text.
print() [12/15]
void print (const txt & x)
Definition at line 3410 of file explore.cc.
 {
  dump(x.buffer);
 }
References txt::buffer, and dump().
print() [13/15]
void print (const unsigned long x)
Definition at line 3379 of file explore.cc.
 {
  echo(x);
  echo("\n");
 }
References echo().
print() [14/15]
void print (const unsigned x)
Definition at line 3369 of file explore.cc.
 {
  echo(x);
  echo("\n");
 }
References echo().
print() [15/15]
void print (const void * x)
Definition at line 3389 of file explore.cc.
 {
  echo(x);
  echo("\n");
 }
References echo().
push() [1/4]
void push (buf & x, const char y)
Definition at line 3429 of file explore.cc.
 {
  if(is_filled(x))
  {
   const int l=get_capacity(x)+1024;
   reserve(x,l);
  }
  x.length++;
  back(x,0,y);
 }
References back(), get_capacity(), is_filled(), buf::length, and reserve().
push() [2/4]
void push (mem & x, const char y)
Definition at line 3422 of file explore.cc.
 {
  const int l=get_length(x);
  const int lx=l+1;
  allocate(x,lx);
  back(x,0,y);
 }
References allocate(), back(), and get_length().
Referenced by append(), assign(), compact(), decode(), delimit(), dir_find(), dir_list(), doc_generate(), encode(), escape(), front(), get_guid(), join(), lift(), main(), pad_r(), push(), put(), quote(), remove(), replace(), serialize(), set(), shuffle(), single_quote(), split(), term_read(), to_c(), to_lower(), to_mem(), to_seq(), to_txt(), to_upper(), trim_l(), trim_r(), and unlift().
push() [3/4]
void push (seq & x, const mem & y)
Definition at line 3445 of file explore.cc.
 {
  const mem m=encode(y);
  push(x.text,m);
 }
References encode(), push(), and seq::text.
push() [4/4]
void push (txt & x, const mem & y)
Definition at line 3439 of file explore.cc.
 {
  check(!contain(y,'\n'));
  append(x.buffer,y);
  push(x.buffer,'\n');
 }
References append(), txt::buffer, check(), contain(), and push().
put()
void put (map & x, const mem & y, const mem & z)
Definition at line 3450 of file explore.cc.
 {
  check(is_full(y));
  map m;
  swap(m,x);
  bool found=false;
  while(is_full(m))
  {
   const mem k=shift(m.keys);
   const mem v=shift(m.values);
   push(x.keys,k);
   if(eq(k,y))
   {
    push(x.values,z);
    found=true;
   }
   else
    push(x.values,v);
  }
  if(!found)
  {
   push(x.keys,y);
   push(x.values,z);
  }
 }
References check(), eq(), is_full(), map::keys, push(), shift(), swap(), and map::values.
Referenced by deserialize().
quote()
mem quote (const mem & x)
Definition at line 3475 of file explore.cc.
 {
  mem r;
  push(r,'"');
  append(r,x);
  push(r,'"');
  return r;
 }
References append(), and push().
Referenced by dir_copy(), dir_find(), dir_list(), dir_make(), dir_remove(), file_copy(), and to_lit().
read() [1/4]
mem read (const fd & x)
Definition at line 3483 of file explore.cc.
 {
  buf b;
  while(true)
  {
   const mem m=read(x,1024);
   if(is_empty(m))
    break;
   append(b,m);
  }
  return detach(b);
 }
References append(), detach(), and is_empty().
Referenced by get_domain(), load(), os_execute(), read(), receive(), and term_read().
read() [2/4]
mem read (const fd & x, const int y)
Definition at line 3507 of file explore.cc.
 {
  check(y>=0);
  mem r;
  if(y==0)
   return r;
  allocate(r,y);
  char* p=get_address(r);
  const int n=read(x.handle,p,y);
  check(n>=0);
  check(n<=y);
  allocate(r,n);
  return r;
 }
References allocate(), check(), get_address(), fd::handle, and read().
read() [3/4]
mem read (const pfile & x)
Definition at line 3495 of file explore.cc.
 {
  buf b;
  while(true)
  {
   const mem m=read(x,1024);
   if(is_empty(m))
    break;
   append(b,m);
  }
  return detach(b);
 }
References append(), detach(), is_empty(), and read().
read() [4/4]
mem read (const pfile & x, const int y)
Definition at line 3521 of file explore.cc.
 {
  check(y>=0);
  mem r;
  if(y==0)
   return r;
  allocate(r,y);
  char* p=get_address(r);
  const int n=fread(p,1,y,x.pointer);
  check(n>=0);
  check(n<=y);
  allocate(r,n);
  return r;
 }
References allocate(), check(), get_address(), and pfile::pointer.
receive()
mem receive (const fd & x)
Definition at line 3535 of file explore.cc.
 {
  mem r;
  while(true)
  {
   mem m;
   allocate(m,1024);
   const int l=get_length(m);
   char* p=get_address(m);
   const int n=read(x.handle,p,l);
   if(n==0)
    break;
   if(n==-1)
   {
    check(errno==EAGAIN||errno==EWOULDBLOCK);
    break;
   }
   check(n>0);
   check(n<=l);
   allocate(m,n);
   append(r,m);
  }
  return r;
 }
References allocate(), append(), check(), get_address(), get_length(), fd::handle, and read().
remove() [1/4]
void remove (seq & x, const int y)
Definition at line 3580 of file explore.cc.
 {
  remove(x.text,y);
 }
References remove(), and seq::text.
remove() [2/4]
void remove (seq & x, const int y, const int z)
Definition at line 3584 of file explore.cc.
 {
  remove(x.text,y,z);
 }
References remove(), and seq::text.
remove() [3/4]
void remove (txt & x, const int y)
Definition at line 3559 of file explore.cc.
 {
  remove(x,y,1);
 }
Referenced by fs_remove(), remove(), and shuffle().
remove() [4/4]
void remove (txt & x, const int y, const int z)
Definition at line 3563 of file explore.cc.
 {
  const int l=count(x);
  check(y>=0);
  check(z>=0);
  check(y<l);
  check(y+z<=l);
  txt t;
  const int n=y+z;
  move(t,x);
  for(int i=0;i<l;i++)
  {
   const mem m=shift(t);
   if(i<y||i>n)
    push(x,m);
  }
 }
References check(), count(), move(), push(), and shift().
repeat()
mem repeat (const mem & x, const int y)
Definition at line 3588 of file explore.cc.
 {
  check(y>=0);
  buf b;
  const int l=get_length(x);
  const int ly=l*y;
  reserve(b,ly);
  for(int i=0;i<y;i++)
  {
   append(b,x);
  }
  return detach(b);
 }
References append(), check(), detach(), get_length(), and reserve().
Referenced by flower(), title_l(), and title_r().
replace() [1/2]
mem replace (const mem & x, const char y, const char z)
Definition at line 3601 of file explore.cc.
 {
  mem r=x;
  const int l=get_length(r);
  for(int i=0;i<l;i++)
  {
   const char c=at(r,i);
   if(c==y)
    set(r,i,z);
  }
  return r;
 }
References at(), get_length(), and set().
replace() [2/2]
mem replace (const mem & x, const mem & y, const mem & z)
Definition at line 3613 of file explore.cc.
 {
  if(is_empty(y))
   return x;
  buf bx=to_buf(x);
  buf br;
  while(is_full(bx))
  {
   if(match_l(bx,y))
   {
    const int l=get_length(y);
    shift(bx,l);
    append(br,z);
   }
   else
   {
    const char c=shift(bx);
    push(br,c);
   }
  }
  return detach(br);
 }
References append(), detach(), get_length(), is_empty(), is_full(), match_l(), push(), shift(), and to_buf().
report()
void report ()
Definition at line 3635 of file explore.cc.
 {
  const int n=errno;
  const mem m=strerror(n);
  print(concat("error ",to_lit(m)));
  print(concat("number ",to_mem(n)));
 }
References concat(), print(), to_lit(), and to_mem().
Referenced by destruct().
reserve()
void reserve (buf & x, const int y)
Definition at line 3642 of file explore.cc.
 {
  check(y>=0);
  const int lx=x.length;
  const int l=get_capacity(x);
  if(y<=lx)
   return;
  if(y<=l)
   return;
  buf b;
  swap(b,x);
  allocate(x.memory,y);
  x.length=lx;
  copy(x,0,b,0,lx);
 }
References allocate(), check(), copy(), get_capacity(), buf::length, buf::memory, and swap().
Referenced by append(), assign(), dim(), encode(), escape(), get_guid(), prepend(), push(), repeat(), and unshift().
reset()
void reset (buf & x)
Definition at line 3657 of file explore.cc.
 {
  x.index=0;
  x.length=0;
 }
References buf::index, and buf::length.
Referenced by assign(), detach(), normalize(), and path_unique().
save()
void save (const mem & x, const mem & y)
Definition at line 3662 of file explore.cc.
 {
  if(is_file(x))
  {
   const mem m=load(x);
   if(eq(m,y))
    return;
  }
  const mem dir=path_dir(x);
  if(!is_dir(dir))
   dir_make(dir);
  fd f;
  const int flag=O_WRONLY|O_CREAT|O_TRUNC;
  open(f,x,flag);
  write(f,y);
 }
References dir_make(), eq(), is_dir(), is_file(), load(), open(), path_dir(), and write().
Referenced by doc_generate(), sort(), and translit().
send()
void send (const fd & x, const mem & y)
Definition at line 3678 of file explore.cc.
 {
  const timer t=timeout(0.1);
  mem m=y;
  while(is_full(m))
  {
   check(!hit(t));
   const int l=get_length(m);
   const char* p=get_address(m);
   const int n=write(x.handle,p,l);
   if(n==-1)
   {
    check(errno==EAGAIN||errno==EWOULDBLOCK);
    wait(0.01);
   }
   check(n>=0);
   check(n<=l);
   drop_l(m,n);
  }
 }
References check(), drop_l(), get_address(), get_length(), fd::handle, hit(), is_full(), timeout(), wait(), and write().
serialize() [1/2]
void serialize (mem & x, const map & y)
Definition at line 3703 of file explore.cc.
 {
  map m=y;
  txt t;
  while(is_full(m))
  {
   const mem m1=shift(m.keys);
   const mem m2=shift(m.values);
   const mem key=encode(m1);
   const mem value=encode(m2);
   push(t,key);
   push(t,value);
  }
  serialize(x,t);
 }
References encode(), is_full(), map::keys, push(), serialize(), shift(), and map::values.
serialize() [2/2]
void serialize (mem & x, const txt & y)
Definition at line 3698 of file explore.cc.
 {
  mem m=to_mem(y);
  move(x,m);
 }
References move(), and to_mem().
Referenced by lift(), serialize(), to_mem(), and wrap().
set() [1/3]
void set (buf & x, const int y, const char z)
Definition at line 3726 of file explore.cc.
 {
  const int l=get_length(x);
  check(y>=0);
  check(y<l);
  const int n=get_offset(x,y);
  set(x.memory,n,z);
 }
References check(), get_length(), get_offset(), buf::memory, and set().
set() [2/3]
void set (map & x, const mem & y, const mem & z)
Definition at line 3734 of file explore.cc.
 {
  check(!has(x,y));
  push(x.keys,y);
  push(x.values,z);
 }
References check(), has(), map::keys, push(), and map::values.
set() [3/3]
void set (mem & x, const int y, const char z)
Definition at line 3718 of file explore.cc.
 {
  const int l=get_length(x);
  check(y>=0);
  check(y<l);
  char* p=get_address(x,y);
  *p=z;
 }
References check(), get_address(), and get_length().
Referenced by back(), copy(), create(), front(), join(), replace(), and set().
set_non_block()
void set_non_block (const fd & x)
Definition at line 3740 of file explore.cc.
 {
  const int n1=fcntl(x.handle,F_GETFL,0);
  check(n1!=-1);
  const int n2=n1|O_NONBLOCK;
  const int n3=fcntl(x.handle,F_SETFL,n2);
  check(n3!=-1);
 }
References check(), and fd::handle.
Referenced by accept(), and listen().
shift() [1/6]
char shift (buf & x)
Definition at line 3764 of file explore.cc.
 {
  check(is_full(x));
  const char r=front(x);
  drop_l(x);
  return r;
 }
References check(), drop_l(), front(), and is_full().
shift() [2/6]
mem shift (buf & x, const int y)
Definition at line 3771 of file explore.cc.
 {
  const int l=get_length(x);
  check(y>=0);
  check(y<=l);
  const mem r=slice_l(x,y);
  drop_l(x,y);
  return r;
 }
References check(), drop_l(), get_length(), and slice_l().
shift() [3/6]
char shift (mem & x)
Definition at line 3748 of file explore.cc.
 {
  check(is_full(x));
  const char r=front(x);
  drop_l(x);
  return r;
 }
References check(), drop_l(), front(), and is_full().
Referenced by at(), compact(), contain(), decode(), delimit(), deserialize(), dir_find(), dir_list(), doc_generate(), drop_l(), dump(), get(), implode(), join(), put(), remove(), replace(), serialize(), split(), to_mem(), to_seq(), to_txt(), trim_l(), and trim_r().
shift() [4/6]
mem shift (mem & x, const int y)
Definition at line 3755 of file explore.cc.
 {
  const int l=get_length(x);
  check(y>=0);
  check(y<=l);
  const mem r=slice_l(x,y);
  drop_l(x,y);
  return r;
 }
References check(), drop_l(), get_length(), and slice_l().
shift() [5/6]
mem shift (seq & x)
Definition at line 3787 of file explore.cc.
 {
  check(is_full(x));
  const mem r=front(x);
  drop_l(x);
  return r;
 }
References check(), drop_l(), front(), and is_full().
shift() [6/6]
mem shift (txt & x)
Definition at line 3780 of file explore.cc.
 {
  check(is_full(x));
  const mem r=front(x);
  drop_l(x);
  return r;
 }
References check(), drop_l(), front(), and is_full().
shuffle() [1/2]
void shuffle (seq & x)
Definition at line 3807 of file explore.cc.
 {
  shuffle(x.text);
 }
References shuffle(), and seq::text.
shuffle() [2/2]
void shuffle (txt & x)
Definition at line 3794 of file explore.cc.
 {
  txt t;
  move(t,x);
  while(is_full(t))
  {
   const int l=count(t);
   const int n=get_random(l);
   const mem m=at(t,n);
   push(x,m);
   remove(t,n);
  }
 }
References at(), count(), get_random(), is_full(), move(), push(), and remove().
Referenced by shuffle().
single_quote()
mem single_quote (const mem & x)
Definition at line 3811 of file explore.cc.
 {
  mem r;
  push(r,'\'');
  append(r,x);
  push(r,'\'');
  return r;
 }
References append(), and push().
Referenced by to_lit().
slice() [1/8]
mem slice (const buf & x, const int y)
Definition at line 3827 of file explore.cc.
 {
  const int l=get_length(x);
  check(y>=0);
  check(y<=l);
  const int ly=l-y;
  return slice(x,y,ly);
 }
References check(), get_length(), and slice().
slice() [2/8]
mem slice (const buf & x, const int y, const int z)
Definition at line 3860 of file explore.cc.
 {
  const int l=get_length(x);
  check(y>=0);
  check(y<=l);
  check(z>=0);
  check(y+z<=l);
  mem r;
  allocate(r,z);
  copy(r,0,x,y,z);
  return r;
 }
References allocate(), check(), copy(), and get_length().
slice() [3/8]
mem slice (const mem & x, const int y)
Definition at line 3819 of file explore.cc.
 {
  const int l=get_length(x);
  check(y>=0);
  check(y<=l);
  const int ly=l-y;
  return slice(x,y,ly);
 }
References check(), and get_length().
Referenced by slice(), slice_l(), slice_r(), and strip_l().
slice() [4/8]
mem slice (const mem & x, const int y, const int z)
Definition at line 3848 of file explore.cc.
 {
  const int l=get_length(x);
  check(y>=0);
  check(y<=l);
  check(z>=0);
  check(y+z<=l);
  mem r;
  allocate(r,z);
  copy(r,0,x,y,z);
  return r;
 }
References allocate(), check(), copy(), and get_length().
slice() [5/8]
seq slice (const seq & x, const int y)
Definition at line 3843 of file explore.cc.
 {
  const txt t=slice(x.text,y);
  return to_seq(t);
 }
References slice(), seq::text, and to_seq().
slice() [6/8]
seq slice (const seq & x, const int y, const int z)
Definition at line 3885 of file explore.cc.
 {
  const txt t=slice(x.text,y,z);
  return to_seq(t);
 }
References slice(), seq::text, and to_seq().
slice() [7/8]
txt slice (const txt & x, const int y)
Definition at line 3835 of file explore.cc.
 {
  const int l=count(x);
  check(y>=0);
  check(y<=l);
  const int ly=l-y;
  return slice(x,y,ly);
 }
References check(), count(), and slice().
slice() [8/8]
txt slice (const txt & x, const int y, const int z)
Definition at line 3872 of file explore.cc.
 {
  const int l=count(x);
  check(y>=0);
  check(y<=l);
  check(z>=0);
  check(y+z<=l);
  const int ly=l-y-z;
  txt r=x;
  drop_l(r,y);
  drop_r(r,ly);
  return r;
 }
References check(), count(), drop_l(), and drop_r().
slice_l() [1/4]
mem slice_l (const buf & x, const int y)
Definition at line 3897 of file explore.cc.
 {
  const int l=get_length(x);
  check(y>=0);
  check(y<=l);
  return slice(x,0,y);
 }
References check(), get_length(), and slice().
slice_l() [2/4]
mem slice_l (const mem & x, const int y)
Definition at line 3890 of file explore.cc.
 {
  const int l=get_length(x);
  check(y>=0);
  check(y<=l);
  return slice(x,0,y);
 }
References check(), get_length(), and slice().
Referenced by head(), shift(), slice_l(), and strip_r().
slice_l() [3/4]
seq slice_l (const seq & x, const int y)
Definition at line 3911 of file explore.cc.
 {
  const txt t=slice_l(x.text,y);
  return to_seq(t);
 }
References slice_l(), seq::text, and to_seq().
slice_l() [4/4]
txt slice_l (const txt & x, const int y)
Definition at line 3904 of file explore.cc.
 {
  const int l=count(x);
  check(y>=0);
  check(y<=l);
  return slice(x,0,y);
 }
References check(), count(), and slice().
slice_r() [1/4]
mem slice_r (const buf & x, const int y)
Definition at line 3924 of file explore.cc.
 {
  const int l=get_length(x);
  check(y>=0);
  check(y<=l);
  const int n=l-y;
  return slice(x,n,y);
 }
References check(), get_length(), and slice().
slice_r() [2/4]
mem slice_r (const mem & x, const int y)
Definition at line 3916 of file explore.cc.
 {
  const int l=get_length(x);
  check(y>=0);
  check(y<=l);
  const int n=l-y;
  return slice(x,n,y);
 }
References check(), get_length(), and slice().
Referenced by pop(), slice_r(), and tail().
slice_r() [3/4]
seq slice_r (const seq & x, const int y)
Definition at line 3940 of file explore.cc.
 {
  const txt t=slice_r(x.text,y);
  return to_seq(t);
 }
References slice_r(), seq::text, and to_seq().
slice_r() [4/4]
txt slice_r (const txt & x, const int y)
Definition at line 3932 of file explore.cc.
 {
  const int l=count(x);
  check(y>=0);
  check(y<=l);
  const int n=l-y;
  return slice(x,n,y);
 }
References check(), count(), and slice().
sort()
void sort (txt & x)
Definition at line 3945 of file explore.cc.
 {
  if(is_empty(x))
   return;
  const mem path=path_tmp("sort.txt");
  const mem content=to_mem(x);
  save(path,content);
  const mem command=concat("sort ",path);
  const mem result=os_execute(command);
  fs_remove(path);
  x=to_txt(result);
 }
References concat(), fs_remove(), is_empty(), os_execute(), path_tmp(), save(), to_mem(), and to_txt().
Referenced by dir_find(), and dir_list().
split() [1/2]
txt split (const mem & x, const char y)
Definition at line 3957 of file explore.cc.
 {
  txt r;
  buf b1=to_buf(x);
  buf b2;
  while(is_full(b1))
  {
   const char c=shift(b1);
   if(c==y)
   {
    const mem m=detach(b2);
    push(r,m);
   }
   else
    push(b2,c);
  }
  if(is_full(b2))
  {
   const mem m=detach(b2);
   push(r,m);
  }
  return r;
 }
References detach(), is_full(), push(), shift(), and to_buf().
Referenced by dir_locate(), file_locate(), get_domain(), path_ext(), path_name(), path_unique(), and to_mem().
split() [2/2]
txt split (const mem & x, const mem & y)
Definition at line 3980 of file explore.cc.
 {
  check(is_full(y));
  txt r;
  buf b1=to_buf(x);
  buf b2;
  const int l=get_length(y);
  while(is_full(b1))
  {
   if(match_l(b1,y))
   {
    shift(b1,l);
    const mem m=detach(b2);
    push(r,m);
   }
   else
   {
    const char c=shift(b1);
    push(b2,c);
   }
  }
  if(is_full(b2))
  {
   const mem m=detach(b2);
   push(r,m);
  }
  return r;
 }
References check(), detach(), get_length(), is_full(), match_l(), push(), shift(), and to_buf().
stop()
void stop ()
Definition at line 4008 of file explore.cc.
 {
  throw 42;
 }
Referenced by check(), dir_locate(), fd::fd(), file_locate(), get(), fd::operator=(), pfile::operator=(), pthread::operator=(), pfile::pfile(), and pthread::pthread().
strip_l() [1/4]
mem strip_l (const buf & x, const char y)
Definition at line 4018 of file explore.cc.
 {
  if(match_l(x,y))
   return slice(x,1);
  return x;
 }
References match_l(), and slice().
strip_l() [2/4]
mem strip_l (const buf & x, const mem & y)
Definition at line 4033 of file explore.cc.
 {
  if(match_l(x,y))
  {
   const int l=get_length(y);
   return slice(x,l);
  }
  return x;
 }
References get_length(), match_l(), and slice().
strip_l() [3/4]
mem strip_l (const mem & x, const char y)
Definition at line 4012 of file explore.cc.
 {
  if(match_l(x,y))
   return slice(x,1);
  return x;
 }
References match_l(), and slice().
strip_l() [4/4]
mem strip_l (const mem & x, const mem & y)
Definition at line 4024 of file explore.cc.
 {
  if(match_l(x,y))
  {
   const int l=get_length(y);
   return slice(x,l);
  }
  return x;
 }
References get_length(), match_l(), and slice().
strip_r() [1/4]
mem strip_r (const buf & x, const char y)
Definition at line 4052 of file explore.cc.
 {
  if(match_r(x,y))
  {
   const int l=get_length(x);
   const int lx=l-1;
   return slice_l(x,lx);
  }
  return x;
 }
References get_length(), match_r(), and slice_l().
strip_r() [2/4]
mem strip_r (const buf & x, const mem & y)
Definition at line 4073 of file explore.cc.
 {
  if(match_r(x,y))
  {
   const int lx=get_length(x);
   const int ly=get_length(x);
   const int l=lx-ly;
   return slice_l(x,l);
  }
  return x;
 }
References get_length(), match_r(), and slice_l().
strip_r() [3/4]
mem strip_r (const mem & x, const char y)
Definition at line 4042 of file explore.cc.
 {
  if(match_r(x,y))
  {
   const int l=get_length(x);
   const int lx=l-1;
   return slice_l(x,lx);
  }
  return x;
 }
References get_length(), match_r(), and slice_l().
Referenced by get_domain().
strip_r() [4/4]
mem strip_r (const mem & x, const mem & y)
Definition at line 4062 of file explore.cc.
 {
  if(match_r(x,y))
  {
   const int lx=get_length(x);
   const int ly=get_length(x);
   const int l=lx-ly;
   return slice_l(x,l);
  }
  return x;
 }
References get_length(), match_r(), and slice_l().
swap() [1/20]
void swap (bool & x, bool & y)
Definition at line 4084 of file explore.cc.
 {
  const bool b=x;
  x=y;
  y=b;
 }
Referenced by buf::buf(), detach(), fd::fd(), mem::mem(), move(), normalize(), buf::operator=(), fd::operator=(), map::operator=(), mem::operator=(), seq::operator=(), txt::operator=(), put(), reserve(), seq::seq(), swap(), to_txt(), and txt::txt().
swap() [2/20]
void swap (buf & x, buf & y)
Definition at line 4147 of file explore.cc.
 {
  swap(x.index,y.index);
  swap(x.length,y.length);
  swap(x.memory,y.memory);
 }
References buf::index, buf::length, buf::memory, and swap().
swap() [3/20]
void swap (char & x, char & y)
Definition at line 4090 of file explore.cc.
 {
  const bool b=x;
  x=y;
  y=b;
 }
swap() [4/20]
void swap (char *& x, char *& y)
Definition at line 4126 of file explore.cc.
 {
  char* p=x;
  x=y;
  y=p;
 }
swap() [5/20]
void swap (double & x, double & y)
Definition at line 4120 of file explore.cc.
 {
  const double n=x;
  x=y;
  y=n;
 }
swap() [6/20]
void swap (fd & x, fd & y)
Definition at line 4161 of file explore.cc.
 {
  swap(x.handle,y.handle);
 }
References fd::handle, and swap().
swap() [7/20]
void swap (FILE *& x, FILE *& y)
Definition at line 4132 of file explore.cc.
 {
  FILE* p=x;
  x=y;
  y=p;
 }
swap() [8/20]
void swap (grid & x, grid & y)
Definition at line 4174 of file explore.cc.
 {
  swap(x.width,y.width);
  swap(x.height,y.height);
  swap(x.cells,y.cells);
 }
References grid::cells, grid::height, swap(), and grid::width.
swap() [9/20]
void swap (int & x, int & y)
Definition at line 4096 of file explore.cc.
 {
  const int n=x;
  x=y;
  y=n;
 }
swap() [10/20]
void swap (long & x, long & y)
Definition at line 4108 of file explore.cc.
 {
  const long n=x;
  x=y;
  y=n;
 }
swap() [11/20]
void swap (map & x, map & y)
Definition at line 4169 of file explore.cc.
 {
  swap(x.keys,y.keys);
  swap(x.values,y.values);
 }
References map::keys, swap(), and map::values.
swap() [12/20]
void swap (mem & x, mem & y)
Definition at line 4143 of file explore.cc.
 {
  swap(x.pointer,y.pointer);
 }
References mem::pointer, and swap().
swap() [13/20]
void swap (pfile & x, pfile & y)
Definition at line 4165 of file explore.cc.
 {
  swap(x.pointer,y.pointer);
 }
References pfile::pointer, and swap().
swap() [14/20]
void swap (ptr & x, ptr & y)
Definition at line 4138 of file explore.cc.
 {
  swap(x.pointer,y.pointer);
  swap(x.length,y.length);
 }
References ptr::length, ptr::pointer, and swap().
swap() [15/20]
void swap (seq & x, seq & y)
Definition at line 4157 of file explore.cc.
 {
  swap(x.text,y.text);
 }
References swap(), and seq::text.
swap() [16/20]
void swap (tbl & x, tbl & y)
Definition at line 4180 of file explore.cc.
 {
  swap(x.columns,y.columns);
  swap(x.cells,y.cells);
 }
References tbl::cells, tbl::columns, and swap().
swap() [17/20]
void swap (timer & x, timer & y)
Definition at line 4185 of file explore.cc.
 {
  swap(x.start,y.start);
  swap(x.duration,y.duration);
 }
References timer::duration, timer::start, and swap().
swap() [18/20]
void swap (txt & x, txt & y)
Definition at line 4153 of file explore.cc.
 {
  swap(x.buffer,y.buffer);
 }
References txt::buffer, and swap().
swap() [19/20]
void swap (unsigned & x, unsigned & y)
Definition at line 4102 of file explore.cc.
 {
  const unsigned n=x;
  x=y;
  y=n;
 }
swap() [20/20]
void swap (unsigned long & x, unsigned long & y)
Definition at line 4114 of file explore.cc.
 {
  const unsigned long n=x;
  x=y;
  y=n;
 }
tail() [1/2]
mem tail (const buf & x, const int y)
Definition at line 4198 of file explore.cc.
 {
  check(y>=0);
  const int l=get_length(x);
  if(l<=y)
   return x;
  return slice_r(x,y);
 }
References check(), get_length(), and slice_r().
tail() [2/2]
mem tail (const mem & x, const int y)
Definition at line 4190 of file explore.cc.
 {
  check(y>=0);
  const int l=get_length(x);
  if(l<=y)
   return x;
  return slice_r(x,y);
 }
References check(), get_length(), and slice_r().
Referenced by title_r().
term_hit()
bool term_hit ()
Definition at line 4206 of file explore.cc.
 {
  const mem m=term_read();
  return is_full(m);
 }
References is_full(), and term_read().
term_read()
mem term_read ()
Definition at line 4211 of file explore.cc.
 {
  mem r;
  fd f;
  f.handle=dup(STDIN_FILENO);
  termios t1;
  const int n0=tcgetattr(f.handle,&t1);
  check(n0==0);
  const termios t2=t1;
  t1.c_lflag&=~ICANON;
  t1.c_lflag&=~ECHO;
  const int n1=tcsetattr(f.handle,TCSANOW,&t1);
  check(n1==0);
  const int n2=fcntl(f.handle,F_GETFL);
  check(n2!=-1);
  const int a=n2|O_NONBLOCK;
  const int n3=fcntl(f.handle,F_SETFL,a);
  check(n3!=-1);
  char c=0;
  const int n4=read(f.handle,&c,1);
  if(n4==1)
  {
   push(r,c);
   while(true)
   {
    const int n5=read(f.handle,&c,1);
    if(n5<=0)
     break;
    push(r,c);
   }
  }
  const int n6=tcsetattr(f.handle,TCSANOW,&t2);
  check(n6==0);
  return r;
 }
References check(), fd::handle, push(), and read().
Referenced by term_hit().
term_width()
int term_width ()
Definition at line 4246 of file explore.cc.
 {
  const mem m=os_execute("tput cols");
  return to_int(m);
 }
References os_execute(), and to_int().
Referenced by flower(), title_l(), and title_r().
timeout()
timer timeout (const double x)
Definition at line 4251 of file explore.cc.
 {
  check(x>=0);
  timer r;
  r.duration=x;
  return r;
 }
References check(), and timer::duration.
Referenced by send().
title_l() [1/2]
void title_l (const mem & x)
Definition at line 4258 of file explore.cc.
 {
  title_l(x,"*");
 }
title_l() [2/2]
void title_l (const mem & x, const mem & y)
Definition at line 4262 of file explore.cc.
 {
  check(is_full(x));
  check(is_full(y));
  const int width=term_width();
  const mem m1=repeat(y,2);
  const mem m2=repeat(y,width);
  const mem m3=concat(m1," ",x," ",m2);
  const mem m4=head(m3,width);
  print(m4);
 }
References check(), concat(), head(), is_full(), print(), repeat(), and term_width().
title_r() [1/2]
void title_r (const mem & x)
Definition at line 4273 of file explore.cc.
 {
  title_r(x,"*");
 }
title_r() [2/2]
void title_r (const mem & x, const mem & y)
Definition at line 4277 of file explore.cc.
 {
  check(is_full(x));
  check(is_full(y));
  const int width=term_width();
  const mem m1=repeat(y,2);
  const mem m2=repeat(y,width);
  const mem m3=concat(m2," ",x," ",m1);
  const mem m4=tail(m3,width);
  print(m4);
 }
References check(), concat(), is_full(), print(), repeat(), tail(), and term_width().
to_bsize()
mem to_bsize (const long x)
Definition at line 4288 of file explore.cc.
 {
  check(x>=0);
  const double v=x;
  const double kb=1024;
  const double mb=1024*kb;
  const double gb=1024*mb;
  const double tb=1024*gb;
  if(v<kb)
  {
   const mem m=to_mem(x);
   return concat(m,"b");
  }
  if(v<mb)
  {
   const double n=v/kb;
   const mem m=to_mem(n,2);
   return concat(m,"Kb");
  }
  if(v<gb)
  {
   const double n=v/mb;
   const mem m=to_mem(n,2);
   return concat(m,"Mb");
  }
  if(v<tb)
  {
   const double n=v/gb;
   const mem m=to_mem(n,2);
   return concat(m,"Gb");
  }
  const double n=v/tb;
  const mem m=to_mem(n,2);
  return concat(m,"Tb");
 }
References check(), concat(), and to_mem().
to_buf()
buf to_buf (const mem & x)
Definition at line 4323 of file explore.cc.
 {
  const int l=get_length(x);
  buf r;
  dim(r,l);
  copy(r,0,x,0,l);
  return r;
 }
References copy(), dim(), and get_length().
Referenced by decode(), delimit(), replace(), split(), to_txt(), trim_l(), and trim_r().
to_c()
mem to_c (const mem & x)
Definition at line 4331 of file explore.cc.
 {
  mem r=x;
  push(r,0);
  return r;
 }
References push().
Referenced by dir_change(), fs_remove(), fs_rename(), is_dir(), is_file(), open(), os_system(), path_base(), path_dir(), path_real(), and to_long().
to_hexa()
mem to_hexa (const int x)
Definition at line 4337 of file explore.cc.
 {
  mem r;
  allocate(r,256);
  const int l=get_length(r);
  char* p=get_address(r);
  const int n=sprintf(p,"%X",x);
  check(n>=0);
  check(n<l);
  allocate(r,n);
  return r;
 }
References allocate(), check(), get_address(), and get_length().
Referenced by escape().
to_int()
int to_int (const mem & x)
Definition at line 4349 of file explore.cc.
 {
  const long l=to_long(x);
  const int r=l;
  const long n=r;
  check(l==n);
  return r;
 }
References check(), and to_long().
Referenced by term_width().
to_lit() [1/3]
mem to_lit (const buf & x)
Definition at line 4367 of file explore.cc.
 {
  const mem m=to_mem(x);
  return to_lit(m);
 }
References to_lit(), and to_mem().
to_lit() [2/3]
mem to_lit (const char x)
Definition at line 4357 of file explore.cc.
 {
  const mem m=escape(x);
  return single_quote(m);
 }
References escape(), and single_quote().
Referenced by dump(), report(), and to_lit().
to_lit() [3/3]
mem to_lit (const mem & x)
Definition at line 4362 of file explore.cc.
 {
  const mem m=escape(x);
  return quote(m);
 }
References escape(), and quote().
to_long()
long to_long (const mem & x)
Definition at line 4372 of file explore.cc.
 {
  const mem m=to_c(x);
  const char* p=get_address(m);
  const long r=strtol(p,0,10);
  check(r!=LONG_MIN);
  check(r!=LONG_MAX);
  return r;
 }
References check(), get_address(), and to_c().
Referenced by to_int().
to_lower() [1/2]
char to_lower (const char x)
Definition at line 4381 of file explore.cc.
 {
  return tolower(x);
 }
Referenced by to_lower().
to_lower() [2/2]
mem to_lower (const mem & x)
Definition at line 4385 of file explore.cc.
 {
  mem r;
  const int l=get_length(x);
  for(int i=0;i<l;i++)
  {
   const char c=at(x,i);
   const char n=to_lower(c);
   push(r,n);
  }
  return r;
 }
References at(), get_length(), push(), and to_lower().
to_mem() [1/14]
mem to_mem (const bool x)
Definition at line 4397 of file explore.cc.
 {
  if(x)
   return "true";
  return "false";
 }
Referenced by detach(), dump(), echo(), get_date(), join(), normalize(), pad_l(), pad_r(), path_unique(), report(), serialize(), sort(), to_bsize(), to_lit(), and to_mem().
to_mem() [2/14]
mem to_mem (const buf & x)
Definition at line 4520 of file explore.cc.
 {
  return x;
 }
to_mem() [3/14]
mem to_mem (const char * x)
Definition at line 4515 of file explore.cc.
 {
  check(x!=0);
  return x;
 }
References check().
to_mem() [4/14]
mem to_mem (const char x)
Definition at line 4403 of file explore.cc.
 {
  mem r;
  push(r,x);
  return r;
 }
References push().
to_mem() [5/14]
mem to_mem (const double x)
Definition at line 4457 of file explore.cc.
 {
  mem r;
  allocate(r,256);
  const int l=get_length(r);
  char* p=get_address(r);
  const int n=sprintf(p,"%f",x);
  check(n>=0);
  check(n<l);
  allocate(r,n);
  while(is_full(r))
  {
   const char c=back(r);
   if(c!='0')
    break;
   drop_r(r);
  }
  const char c=back(r);
  if(c=='.')
   drop_r(r);
  return r;
 }
References allocate(), back(), check(), drop_r(), get_address(), get_length(), and is_full().
to_mem() [6/14]
mem to_mem (const double x, const int y)
Definition at line 4479 of file explore.cc.
 {
  check(y>=0);
  const mem m=to_mem(x);
  if(!contain(m,'.'))
   return m;
  txt t=split(m,'.');
  const mem integer=shift(t);
  const mem real=shift(t);
  check(is_empty(t));
  mem round=head(real,y);
  if(is_empty(round))
   return integer;
  while(is_full(round))
  {
   const char c=back(round);
   if(c!='0')
    break;
   pop(round);
  }
  if(is_empty(round))
   return integer;
  return concat(integer,".",round);
 }
References back(), check(), concat(), contain(), head(), is_empty(), is_full(), pop(), shift(), split(), and to_mem().
to_mem() [7/14]
mem to_mem (const int x)
Definition at line 4409 of file explore.cc.
 {
  mem r;
  allocate(r,256);
  const int l=get_length(r);
  char* p=get_address(r);
  const int n=sprintf(p,"%d",x);
  check(n>=0);
  check(n<l);
  allocate(r,n);
  return r;
 }
References allocate(), check(), get_address(), and get_length().
to_mem() [8/14]
mem to_mem (const long x)
Definition at line 4433 of file explore.cc.
 {
  mem r;
  allocate(r,256);
  const int l=get_length(r);
  char* p=get_address(r);
  const int n=sprintf(p,"%ld",x);
  check(n>=0);
  check(n<l);
  allocate(r,n);
  return r;
 }
References allocate(), check(), get_address(), and get_length().
to_mem() [9/14]
mem to_mem (const map & x)
Definition at line 4532 of file explore.cc.
 {
  mem r;
  serialize(r,x);
  return r;
 }
References serialize().
to_mem() [10/14]
mem to_mem (const seq & x)
Definition at line 4528 of file explore.cc.
 {
  return to_mem(x.text);
 }
References seq::text, and to_mem().
to_mem() [11/14]
mem to_mem (const txt & x)
Definition at line 4524 of file explore.cc.
 {
  return to_mem(x.buffer);
 }
References txt::buffer, and to_mem().
to_mem() [12/14]
mem to_mem (const unsigned long x)
Definition at line 4445 of file explore.cc.
 {
  mem r;
  allocate(r,256);
  const int l=get_length(r);
  char* p=get_address(r);
  const int n=sprintf(p,"%lu",x);
  check(n>=0);
  check(n<l);
  allocate(r,n);
  return r;
 }
References allocate(), check(), get_address(), and get_length().
to_mem() [13/14]
mem to_mem (const unsigned x)
Definition at line 4421 of file explore.cc.
 {
  mem r;
  allocate(r,256);
  const int l=get_length(r);
  char* p=get_address(r);
  const int n=sprintf(p,"%u",x);
  check(n>=0);
  check(n<l);
  allocate(r,n);
  return r;
 }
References allocate(), check(), get_address(), and get_length().
to_mem() [14/14]
mem to_mem (const void * x)
Definition at line 4503 of file explore.cc.
 {
  mem r;
  allocate(r,256);
  const int l=get_length(r);
  char* p=get_address(r);
  const int n=sprintf(p,"%p",x);
  check(n>=0);
  check(n<l);
  allocate(r,n);
  return r;
 }
References allocate(), check(), get_address(), and get_length().
to_seq()
seq to_seq (const txt & x)
Definition at line 4538 of file explore.cc.
 {
  seq r;
  txt t=x;
  while(is_full(t))
  {
   const mem m=shift(t);
   push(r,m);
  }
  return r;
 }
References is_full(), push(), and shift().
Referenced by slice(), slice_l(), and slice_r().
to_txt()
txt to_txt (const mem & x)
Definition at line 4549 of file explore.cc.
 {
  txt r;
  buf b1=to_buf(x);
  buf b2;
  while(is_full(b1))
  {
   if(match_l(b1,"\r\n"))
   {
    shift(b1,2);
    push(b2,'\n');
   }
   else if(match_l(b1,'\r'))
   {
    shift(b1);
    push(b2,'\n');
   }
   else
   {
    const char c=shift(b1);
    push(b2,c);
   }
  }
  if(!match_r(b2,'\n'))
   push(b2,'\n');
  swap(r.buffer,b2);
  return r;
 }
References txt::buffer, is_full(), match_l(), match_r(), push(), shift(), swap(), and to_buf().
Referenced by compact(), deserialize(), dir_find(), dir_list(), get_domain(), and sort().
to_upper() [1/2]
char to_upper (const char x)
Definition at line 4577 of file explore.cc.
 {
  return toupper(x);
 }
Referenced by to_upper().
to_upper() [2/2]
mem to_upper (const mem & x)
Definition at line 4581 of file explore.cc.
 {
  mem r;
  const int l=get_length(x);
  for(int i=0;i<l;i++)
  {
   const char c=at(x,i);
   const char n=to_upper(c);
   push(r,n);
  }
  return r;
 }
References at(), get_length(), push(), and to_upper().
translit()
mem translit (const mem & x)
Definition at line 4593 of file explore.cc.
 {
  mem r;
  const mem tmp=path_tmp("translit.txt");
  save(tmp,x);
  try
  {
   r=os_execute(concat("iconv -f UTF-8 -t ASCII//TRANSLIT ",tmp));
  }
  catch(...)
  {
   fs_remove(tmp);
   throw;
  }
  fs_remove(tmp);
  return r;
 }
References concat(), fs_remove(), os_execute(), path_tmp(), and save().
trim()
mem trim (const mem & x)
Definition at line 4610 of file explore.cc.
 {
  const mem s=trim_l(x);
  return trim_r(s);
 }
References trim_l(), and trim_r().
Referenced by deserialize().
trim_l() [1/2]
mem trim_l (const mem & x)
Definition at line 4615 of file explore.cc.
 {
  buf b=to_buf(x);
  while(is_full(b))
  {
   const char c=front(b);
   if(!is_blank(c))
    break;
   shift(b);
  }
  return detach(b);
 }
References detach(), front(), is_blank(), is_full(), shift(), and to_buf().
Referenced by trim(), and trim_l().
trim_l() [2/2]
txt trim_l (const txt & x)
Definition at line 4627 of file explore.cc.
 {
  txt r;
  txt t=x;
  while(is_full(t))
  {
   const mem m1=shift(t);
   const mem m2=trim_l(m1);
   push(r,m2);
  }
  return r;
 }
References is_full(), push(), shift(), and trim_l().
trim_r() [1/2]
mem trim_r (const mem & x)
Definition at line 4639 of file explore.cc.
 {
  buf b=to_buf(x);
  while(is_full(b))
  {
   const char c=back(b);
   if(!is_blank(c))
    break;
   drop_r(b);
  }
  return detach(b);
 }
References back(), detach(), drop_r(), is_blank(), is_full(), and to_buf().
Referenced by compact(), trim(), and trim_r().
trim_r() [2/2]
txt trim_r (const txt & x)
Definition at line 4651 of file explore.cc.
 {
  txt r;
  txt t=x;
  while(is_full(t))
  {
   const mem m1=shift(t);
   const mem m2=trim_r(m1);
   push(r,m2);
  }
  while(is_full(r))
  {
   const mem m=back(r);
   if(is_empty(m))
    drop_r(r);
   else
    break;
  }
  return r;
 }
References back(), drop_r(), is_empty(), is_full(), push(), shift(), and trim_r().
unlift() [1/3]
void unlift (map & x, void * y)
Definition at line 4695 of file explore.cc.
 {
  check(y!=0);
  mem m;
  unlift(m,y);
  deserialize(x,m);
 }
References check(), deserialize(), and unlift().
unlift() [2/3]
void unlift (mem & x, void * y)
Definition at line 4671 of file explore.cc.
 {
  check(y!=0);
  buf b;
  while(true)
  {
   const int l=get_length(b);
   char* p=(char*)y;
   const char c=p[l];
   if(c=='\n')
    break;
   push(b,c);
  }
  const mem m=detach(b);
  free(y);
  x=decode(m);
 }
References check(), decode(), detach(), get_length(), and push().
Referenced by on_create(), and unlift().
unlift() [3/3]
void unlift (txt & x, void * y)
Definition at line 4688 of file explore.cc.
 {
  check(y!=0);
  mem m;
  unlift(m,y);
  deserialize(x,m);
 }
References check(), deserialize(), and unlift().
unshift() [1/4]
void unshift (buf & x, const char y)
Definition at line 4710 of file explore.cc.
 {
  if(is_filled(x))
  {
   const int l=get_capacity(x);
   const int lx=l+1024;
   reserve(x,lx);
  }
  if(x.index==0)
  {
   const int l=get_capacity(x);
   const int lx=l-1;
   x.index=lx;
  }
  else
   x.index--;
  x.length++;
  front(x,y);
 }
References front(), get_capacity(), buf::index, is_filled(), buf::length, and reserve().
unshift() [2/4]
void unshift (mem & x, const char y)
Definition at line 4702 of file explore.cc.
 {
  const int lx=get_length(x);
  const int l=lx+1;
  allocate(x,l);
  copy(x,1,0,lx);
  front(x,y);
 }
References allocate(), copy(), front(), and get_length().
Referenced by back(), pad_l(), prepend(), and unshift().
unshift() [3/4]
void unshift (seq & x, const mem & y)
Definition at line 4735 of file explore.cc.
 {
  const mem m=encode(y);
  unshift(x.text,m);
 }
References encode(), seq::text, and unshift().
unshift() [4/4]
void unshift (txt & x, const mem & y)
Definition at line 4729 of file explore.cc.
 {
  check(!contain(y,'\n'));
  unshift(x.buffer,'\n');
  prepend(x.buffer,y);
 }
References txt::buffer, check(), contain(), prepend(), and unshift().
unwrap() [1/11]
void unwrap (bool & x, const mem & y)
Definition at line 4749 of file explore.cc.
 {
  unwrap(&x,sizeof(x),y);
 }
References unwrap().
unwrap() [2/11]
void unwrap (char & x, const mem & y)
Definition at line 4753 of file explore.cc.
 {
  unwrap(&x,sizeof(x),y);
 }
References unwrap().
unwrap() [3/11]
void unwrap (double & x, const mem & y)
Definition at line 4773 of file explore.cc.
 {
  unwrap(&x,sizeof(x),y);
 }
References unwrap().
unwrap() [4/11]
void unwrap (int & x, const mem & y)
Definition at line 4757 of file explore.cc.
 {
  unwrap(&x,sizeof(x),y);
 }
References unwrap().
unwrap() [5/11]
void unwrap (long & x, const mem & y)
Definition at line 4765 of file explore.cc.
 {
  unwrap(&x,sizeof(x),y);
 }
References unwrap().
unwrap() [6/11]
void unwrap (map & x, const mem & y)
Definition at line 4785 of file explore.cc.
 {
  deserialize(x,y);
 }
References deserialize().
unwrap() [7/11]
void unwrap (txt & x, const mem & y)
Definition at line 4781 of file explore.cc.
 {
  deserialize(x,y);
 }
References deserialize().
unwrap() [8/11]
void unwrap (unsigned & x, const mem & y)
Definition at line 4761 of file explore.cc.
 {
  unwrap(&x,sizeof(x),y);
 }
References unwrap().
unwrap() [9/11]
void unwrap (unsigned long & x, const mem & y)
Definition at line 4769 of file explore.cc.
 {
  unwrap(&x,sizeof(x),y);
 }
References unwrap().
unwrap() [10/11]
void unwrap (void *& x, const mem & y)
Definition at line 4777 of file explore.cc.
 {
  unwrap(&x,sizeof(x),y);
 }
References unwrap().
unwrap() [11/11]
void unwrap (void * x, const int y, const mem & z)
Definition at line 4740 of file explore.cc.
 {
  const int l=get_length(z);
  check(x!=0);
  check(y>0);
  check(y==l);
  const char* p=get_address(z);
  memcpy(x,p,y);
 }
References check(), get_address(), and get_length().
Referenced by on_create(), and unwrap().
wait()
void wait (const double x)
Definition at line 4789 of file explore.cc.
 {
  const double t=x*10e5;
  const int n=usleep(t);
  check(n==0);
 }
References check().
Referenced by send().
wrap() [1/11]
mem wrap (const bool y)
Definition at line 4805 of file explore.cc.
 {
  return wrap(&y,sizeof(y));
 }
References wrap().
wrap() [2/11]
mem wrap (const char y)
Definition at line 4809 of file explore.cc.
 {
  return wrap(&y,sizeof(y));
 }
References wrap().
wrap() [3/11]
mem wrap (const double y)
Definition at line 4829 of file explore.cc.
 {
  return wrap(&y,sizeof(y));
 }
References wrap().
wrap() [4/11]
mem wrap (const int y)
Definition at line 4813 of file explore.cc.
 {
  return wrap(&y,sizeof(y));
 }
References wrap().
wrap() [5/11]
mem wrap (const long y)
Definition at line 4821 of file explore.cc.
 {
  return wrap(&y,sizeof(y));
 }
References wrap().
wrap() [6/11]
mem wrap (const map & x)
Definition at line 4843 of file explore.cc.
 {
  mem m;
  serialize(m,x);
  return m;
 }
References serialize().
wrap() [7/11]
mem wrap (const txt & x)
Definition at line 4837 of file explore.cc.
 {
  mem m;
  serialize(m,x);
  return m;
 }
References serialize().
wrap() [8/11]
mem wrap (const unsigned long y)
Definition at line 4825 of file explore.cc.
 {
  return wrap(&y,sizeof(y));
 }
References wrap().
wrap() [9/11]
mem wrap (const unsigned y)
Definition at line 4817 of file explore.cc.
 {
  return wrap(&y,sizeof(y));
 }
References wrap().
wrap() [10/11]
mem wrap (const void * x, const int y)
Definition at line 4795 of file explore.cc.
 {
  check(x!=0);
  check(y>0);
  mem r;
  allocate(r,y);
  char* p=get_address(r);
  memcpy(p,x,y);
  return r;
 }
References allocate(), check(), and get_address().
Referenced by create(), and wrap().
wrap() [11/11]
mem wrap (const void * y)
Definition at line 4833 of file explore.cc.
 {
  return wrap(&y,sizeof(y));
 }
References wrap().
write()
void write (const fd & x, const mem & y)
Definition at line 4849 of file explore.cc.
 {
  check(is_full(x));
  if(is_empty(y))
   return;
  const char* p=get_address(y);
  const int l=get_length(y);
  const int n=write(x.handle,p,l);
  check(n==l);
 }
References check(), get_address(), get_length(), fd::handle, is_empty(), and is_full().
Referenced by echo(), save(), and send().