source: txt Struct Reference
txt Struct Reference
Public Member Functions
txt ()
txt (const txt &x)
txt (txt &&x)
void operator= (const txt &x)
void operator= (txt &&x)
txt ()
txt (const txt &x)
txt (txt &&x)
void operator= (const txt &x)
void operator= (txt &&x)
txt ()
txt (const txt &x)
txt (txt &&x)
void operator= (const txt &x)
void operator= (txt &&x)
txt ()
txt (const txt &x)
txt (txt &&x)
void operator= (const txt &x)
void operator= (txt &&x)
txt ()
txt (const txt &x)
txt (txt &&x)
void operator= (const txt &x)
void operator= (txt &&x)
txt ()
txt (const txt &x)
txt (txt &&x)
void operator= (const txt &x)
void operator= (txt &&x)
txt ()
txt (const txt &x)
txt (txt &&x)
void operator= (const txt &x)
void operator= (txt &&x)
txt ()
txt (const txt &x)
txt (txt &&x)
void operator= (const txt &x)
void operator= (txt &&x)
txt ()
txt (const txt &x)
txt (txt &&x)
void operator= (const txt &x)
void operator= (txt &&x)
Public Attributes
buf buffer
Detailed Description
Definition at line 589 of file backup.cc.
Constructor & Destructor Documentation
txt() [1/27]
txt::txt () inline
Definition at line 592 of file backup.cc.
  {
  }
txt() [2/27]
txt::txt (const txt & x) inline
Definition at line 595 of file backup.cc.
  {
   assign(*this,x);
  }
References assign().
txt() [3/27]
txt::txt (txt && x) inline
Definition at line 599 of file backup.cc.
  {
   swap(*this,x);
  }
References swap().
txt() [4/27]
txt::txt () inline
Definition at line 613 of file build.cc.
  {
  }
txt() [5/27]
txt::txt (const txt & x) inline
Definition at line 616 of file build.cc.
  {
   assign(*this,x);
  }
References assign().
txt() [6/27]
txt::txt (txt && x) inline
Definition at line 620 of file build.cc.
  {
   swap(*this,x);
  }
References swap().
txt() [7/27]
txt::txt () inline
Definition at line 593 of file commit.cc.
  {
  }
txt() [8/27]
txt::txt (const txt & x) inline
Definition at line 596 of file commit.cc.
  {
   assign(*this,x);
  }
References assign().
txt() [9/27]
txt::txt (txt && x) inline
Definition at line 600 of file commit.cc.
  {
   swap(*this,x);
  }
References swap().
txt() [10/27]
txt::txt () inline
Definition at line 592 of file convert.cc.
  {
  }
txt() [11/27]
txt::txt (const txt & x) inline
Definition at line 595 of file convert.cc.
  {
   assign(*this,x);
  }
References assign().
txt() [12/27]
txt::txt (txt && x) inline
Definition at line 599 of file convert.cc.
  {
   swap(*this,x);
  }
References swap().
txt() [13/27]
txt::txt () inline
Definition at line 603 of file download.cc.
  {
  }
txt() [14/27]
txt::txt (const txt & x) inline
Definition at line 606 of file download.cc.
  {
   assign(*this,x);
  }
References assign().
txt() [15/27]
txt::txt (txt && x) inline
Definition at line 610 of file download.cc.
  {
   swap(*this,x);
  }
References swap().
txt() [16/27]
txt::txt () inline
Definition at line 593 of file explore.cc.
  {
  }
txt() [17/27]
txt::txt (const txt & x) inline
Definition at line 596 of file explore.cc.
  {
   assign(*this,x);
  }
References assign().
txt() [18/27]
txt::txt (txt && x) inline
Definition at line 600 of file explore.cc.
  {
   swap(*this,x);
  }
References swap().
txt() [19/27]
txt::txt () inline
Definition at line 597 of file normalize.cc.
  {
  }
txt() [20/27]
txt::txt (const txt & x) inline
Definition at line 600 of file normalize.cc.
  {
   assign(*this,x);
  }
References assign().
txt() [21/27]
txt::txt (txt && x) inline
Definition at line 604 of file normalize.cc.
  {
   swap(*this,x);
  }
References swap().
txt() [22/27]
txt::txt () inline
Definition at line 608 of file serve.cc.
  {
  }
txt() [23/27]
txt::txt (const txt & x) inline
Definition at line 611 of file serve.cc.
  {
   assign(*this,x);
  }
References assign().
txt() [24/27]
txt::txt (txt && x) inline
Definition at line 615 of file serve.cc.
  {
   swap(*this,x);
  }
References swap().
txt() [25/27]
txt::txt () inline
Definition at line 593 of file test.cc.
  {
  }
txt() [26/27]
txt::txt (const txt & x) inline
Definition at line 596 of file test.cc.
  {
   assign(*this,x);
  }
References assign().
txt() [27/27]
txt::txt (txt && x) inline
Definition at line 600 of file test.cc.
  {
   swap(*this,x);
  }
References swap().
Member Function Documentation
operator=() [1/18]
void txt::operator= (const txt & x) inline
Definition at line 603 of file backup.cc.
  {
   assign(*this,x);
  }
References assign().
operator=() [2/18]
void txt::operator= (const txt & x) inline
Definition at line 624 of file build.cc.
  {
   assign(*this,x);
  }
References assign().
operator=() [3/18]
void txt::operator= (const txt & x) inline
Definition at line 604 of file commit.cc.
  {
   assign(*this,x);
  }
References assign().
operator=() [4/18]
void txt::operator= (const txt & x) inline
Definition at line 603 of file convert.cc.
  {
   assign(*this,x);
  }
References assign().
operator=() [5/18]
void txt::operator= (const txt & x) inline
Definition at line 614 of file download.cc.
  {
   assign(*this,x);
  }
References assign().
operator=() [6/18]
void txt::operator= (const txt & x) inline
Definition at line 604 of file explore.cc.
  {
   assign(*this,x);
  }
References assign().
operator=() [7/18]
void txt::operator= (const txt & x) inline
Definition at line 608 of file normalize.cc.
  {
   assign(*this,x);
  }
References assign().
operator=() [8/18]
void txt::operator= (const txt & x) inline
Definition at line 619 of file serve.cc.
  {
   assign(*this,x);
  }
References assign().
operator=() [9/18]
void txt::operator= (const txt & x) inline
Definition at line 604 of file test.cc.
  {
   assign(*this,x);
  }
References assign().
operator=() [10/18]
void txt::operator= (txt && x) inline
Definition at line 607 of file backup.cc.
  {
   swap(*this,x);
  }
References swap().
operator=() [11/18]
void txt::operator= (txt && x) inline
Definition at line 628 of file build.cc.
  {
   swap(*this,x);
  }
References swap().
operator=() [12/18]
void txt::operator= (txt && x) inline
Definition at line 608 of file commit.cc.
  {
   swap(*this,x);
  }
References swap().
operator=() [13/18]
void txt::operator= (txt && x) inline
Definition at line 607 of file convert.cc.
  {
   swap(*this,x);
  }
References swap().
operator=() [14/18]
void txt::operator= (txt && x) inline
Definition at line 618 of file download.cc.
  {
   swap(*this,x);
  }
References swap().
operator=() [15/18]
void txt::operator= (txt && x) inline
Definition at line 608 of file explore.cc.
  {
   swap(*this,x);
  }
References swap().
operator=() [16/18]
void txt::operator= (txt && x) inline
Definition at line 612 of file normalize.cc.
  {
   swap(*this,x);
  }
References swap().
operator=() [17/18]
void txt::operator= (txt && x) inline
Definition at line 623 of file serve.cc.
  {
   swap(*this,x);
  }
References swap().
operator=() [18/18]
void txt::operator= (txt && x) inline
Definition at line 608 of file test.cc.
  {
   swap(*this,x);
  }
References swap().
Member Data Documentation
buffer
buf txt::buffer
Definition at line 591 of file backup.cc.
Referenced by append(), assign(), back(), clear(), count(), drop_l(), drop_r(), front(), is_empty(), prepend(), print(), push(), swap(), to_mem(), to_txt(), and unshift().
The documentation for this struct was generated from the following files:
code/backup.cc
code/build.cc
code/commit.cc
code/convert.cc
code/download.cc
code/explore.cc
code/normalize.cc
code/serve.cc
code/test.cc