source: map Struct Reference
map Struct Reference
Public Member Functions
map ()
map (const map &x)
map (map &&x)
void operator= (const map &x)
void operator= (map &&x)
map ()
map (const map &x)
map (map &&x)
void operator= (const map &x)
void operator= (map &&x)
map ()
map (const map &x)
map (map &&x)
void operator= (const map &x)
void operator= (map &&x)
map ()
map (const map &x)
map (map &&x)
void operator= (const map &x)
void operator= (map &&x)
map ()
map (const map &x)
map (map &&x)
void operator= (const map &x)
void operator= (map &&x)
map ()
map (const map &x)
map (map &&x)
void operator= (const map &x)
void operator= (map &&x)
map ()
map (const map &x)
map (map &&x)
void operator= (const map &x)
void operator= (map &&x)
map ()
map (const map &x)
map (map &&x)
void operator= (const map &x)
void operator= (map &&x)
map ()
map (const map &x)
map (map &&x)
void operator= (const map &x)
void operator= (map &&x)
Public Attributes
seq keys
seq values
Detailed Description
Definition at line 635 of file backup.cc.
Constructor & Destructor Documentation
map() [1/27]
map::map () inline
Definition at line 639 of file backup.cc.
  {
  }
map() [2/27]
map::map (const map & x) inline
Definition at line 642 of file backup.cc.
  {
   assign(*this,x);
  }
References assign().
map() [3/27]
map::map (map && x) inline
Definition at line 646 of file backup.cc.
  {
   assign(*this,x);
  }
References assign().
map() [4/27]
map::map () inline
Definition at line 660 of file build.cc.
  {
  }
map() [5/27]
map::map (const map & x) inline
Definition at line 663 of file build.cc.
  {
   assign(*this,x);
  }
References assign().
map() [6/27]
map::map (map && x) inline
Definition at line 667 of file build.cc.
  {
   assign(*this,x);
  }
References assign().
map() [7/27]
map::map () inline
Definition at line 640 of file commit.cc.
  {
  }
map() [8/27]
map::map (const map & x) inline
Definition at line 643 of file commit.cc.
  {
   assign(*this,x);
  }
References assign().
map() [9/27]
map::map (map && x) inline
Definition at line 647 of file commit.cc.
  {
   assign(*this,x);
  }
References assign().
map() [10/27]
map::map () inline
Definition at line 639 of file convert.cc.
  {
  }
map() [11/27]
map::map (const map & x) inline
Definition at line 642 of file convert.cc.
  {
   assign(*this,x);
  }
References assign().
map() [12/27]
map::map (map && x) inline
Definition at line 646 of file convert.cc.
  {
   assign(*this,x);
  }
References assign().
map() [13/27]
map::map () inline
Definition at line 650 of file download.cc.
  {
  }
map() [14/27]
map::map (const map & x) inline
Definition at line 653 of file download.cc.
  {
   assign(*this,x);
  }
References assign().
map() [15/27]
map::map (map && x) inline
Definition at line 657 of file download.cc.
  {
   assign(*this,x);
  }
References assign().
map() [16/27]
map::map () inline
Definition at line 640 of file explore.cc.
  {
  }
map() [17/27]
map::map (const map & x) inline
Definition at line 643 of file explore.cc.
  {
   assign(*this,x);
  }
References assign().
map() [18/27]
map::map (map && x) inline
Definition at line 647 of file explore.cc.
  {
   assign(*this,x);
  }
References assign().
map() [19/27]
map::map () inline
Definition at line 644 of file normalize.cc.
  {
  }
map() [20/27]
map::map (const map & x) inline
Definition at line 647 of file normalize.cc.
  {
   assign(*this,x);
  }
References assign().
map() [21/27]
map::map (map && x) inline
Definition at line 651 of file normalize.cc.
  {
   assign(*this,x);
  }
References assign().
map() [22/27]
map::map () inline
Definition at line 655 of file serve.cc.
  {
  }
map() [23/27]
map::map (const map & x) inline
Definition at line 658 of file serve.cc.
  {
   assign(*this,x);
  }
References assign().
map() [24/27]
map::map (map && x) inline
Definition at line 662 of file serve.cc.
  {
   assign(*this,x);
  }
References assign().
map() [25/27]
map::map () inline
Definition at line 640 of file test.cc.
  {
  }
map() [26/27]
map::map (const map & x) inline
Definition at line 643 of file test.cc.
  {
   assign(*this,x);
  }
References assign().
map() [27/27]
map::map (map && x) inline
Definition at line 647 of file test.cc.
  {
   assign(*this,x);
  }
References assign().
Member Function Documentation
operator=() [1/18]
void map::operator= (const map & x) inline
Definition at line 650 of file backup.cc.
  {
   assign(*this,x);
  }
References assign().
operator=() [2/18]
void map::operator= (const map & x) inline
Definition at line 671 of file build.cc.
  {
   assign(*this,x);
  }
References assign().
operator=() [3/18]
void map::operator= (const map & x) inline
Definition at line 651 of file commit.cc.
  {
   assign(*this,x);
  }
References assign().
operator=() [4/18]
void map::operator= (const map & x) inline
Definition at line 650 of file convert.cc.
  {
   assign(*this,x);
  }
References assign().
operator=() [5/18]
void map::operator= (const map & x) inline
Definition at line 661 of file download.cc.
  {
   assign(*this,x);
  }
References assign().
operator=() [6/18]
void map::operator= (const map & x) inline
Definition at line 651 of file explore.cc.
  {
   assign(*this,x);
  }
References assign().
operator=() [7/18]
void map::operator= (const map & x) inline
Definition at line 655 of file normalize.cc.
  {
   assign(*this,x);
  }
References assign().
operator=() [8/18]
void map::operator= (const map & x) inline
Definition at line 666 of file serve.cc.
  {
   assign(*this,x);
  }
References assign().
operator=() [9/18]
void map::operator= (const map & x) inline
Definition at line 651 of file test.cc.
  {
   assign(*this,x);
  }
References assign().
operator=() [10/18]
void map::operator= (map && x) inline
Definition at line 654 of file backup.cc.
  {
   swap(*this,x);
  }
References swap().
operator=() [11/18]
void map::operator= (map && x) inline
Definition at line 675 of file build.cc.
  {
   swap(*this,x);
  }
References swap().
operator=() [12/18]
void map::operator= (map && x) inline
Definition at line 655 of file commit.cc.
  {
   swap(*this,x);
  }
References swap().
operator=() [13/18]
void map::operator= (map && x) inline
Definition at line 654 of file convert.cc.
  {
   swap(*this,x);
  }
References swap().
operator=() [14/18]
void map::operator= (map && x) inline
Definition at line 665 of file download.cc.
  {
   swap(*this,x);
  }
References swap().
operator=() [15/18]
void map::operator= (map && x) inline
Definition at line 655 of file explore.cc.
  {
   swap(*this,x);
  }
References swap().
operator=() [16/18]
void map::operator= (map && x) inline
Definition at line 659 of file normalize.cc.
  {
   swap(*this,x);
  }
References swap().
operator=() [17/18]
void map::operator= (map && x) inline
Definition at line 670 of file serve.cc.
  {
   swap(*this,x);
  }
References swap().
operator=() [18/18]
void map::operator= (map && x) inline
Definition at line 655 of file test.cc.
  {
   swap(*this,x);
  }
References swap().
Member Data Documentation
keys
seq map::keys
Definition at line 637 of file backup.cc.
Referenced by assign(), clear(), count(), dump(), get(), has(), is_empty(), put(), serialize(), set(), and swap().
values
seq map::values
Definition at line 638 of file backup.cc.
Referenced by assign(), clear(), dump(), get(), put(), serialize(), set(), and swap().
The documentation for this struct was generated from the following files:
code/backup.cc
code/build.cc
code/commit.cc
code/convert.cc
code/download.cc
code/explore.cc
code/normalize.cc
code/serve.cc
code/test.cc