source: mem Struct Reference
mem Struct Reference
Public Member Functions
mem ()
mem (const char *x)
mem (const mem &x)
mem (const buf &x)
mem (mem &&x)
~mem ()
void operator= (const char *x)
void operator= (const mem &x)
void operator= (const buf &x)
void operator= (mem &&x)
mem ()
mem (const char *x)
mem (const mem &x)
mem (const buf &x)
mem (mem &&x)
~mem ()
void operator= (const char *x)
void operator= (const mem &x)
void operator= (const buf &x)
void operator= (mem &&x)
mem ()
mem (const char *x)
mem (const mem &x)
mem (const buf &x)
mem (mem &&x)
~mem ()
void operator= (const char *x)
void operator= (const mem &x)
void operator= (const buf &x)
void operator= (mem &&x)
mem ()
mem (const char *x)
mem (const mem &x)
mem (const buf &x)
mem (mem &&x)
~mem ()
void operator= (const char *x)
void operator= (const mem &x)
void operator= (const buf &x)
void operator= (mem &&x)
mem ()
mem (const char *x)
mem (const mem &x)
mem (const buf &x)
mem (mem &&x)
~mem ()
void operator= (const char *x)
void operator= (const mem &x)
void operator= (const buf &x)
void operator= (mem &&x)
mem ()
mem (const char *x)
mem (const mem &x)
mem (const buf &x)
mem (mem &&x)
~mem ()
void operator= (const char *x)
void operator= (const mem &x)
void operator= (const buf &x)
void operator= (mem &&x)
mem ()
mem (const char *x)
mem (const mem &x)
mem (const buf &x)
mem (mem &&x)
~mem ()
void operator= (const char *x)
void operator= (const mem &x)
void operator= (const buf &x)
void operator= (mem &&x)
mem ()
mem (const char *x)
mem (const mem &x)
mem (const buf &x)
mem (mem &&x)
~mem ()
void operator= (const char *x)
void operator= (const mem &x)
void operator= (const buf &x)
void operator= (mem &&x)
mem ()
mem (const char *x)
mem (const mem &x)
mem (const buf &x)
mem (mem &&x)
~mem ()
void operator= (const char *x)
void operator= (const mem &x)
void operator= (const buf &x)
void operator= (mem &&x)
Public Attributes
ptr pointer
Detailed Description
Definition at line 513 of file backup.cc.
Constructor & Destructor Documentation
mem() [1/45]
mem::mem () inline
Definition at line 516 of file backup.cc.
  {
  }
mem() [2/45]
mem::mem (const char * x) inline
Definition at line 519 of file backup.cc.
  {
   assign(*this,x);
  }
References assign().
mem() [3/45]
mem::mem (const mem & x) inline
Definition at line 523 of file backup.cc.
  {
   assign(*this,x);
  }
References assign().
mem() [4/45]
mem::mem (const buf & x) inline
Definition at line 527 of file backup.cc.
  {
   assign(*this,x);
  }
References assign().
mem() [5/45]
mem::mem (mem && x) inline
Definition at line 531 of file backup.cc.
  {
   swap(*this,x);
  }
References swap().
~mem() [1/9]
mem::~mem () inline
Definition at line 535 of file backup.cc.
  {
   destruct(*this);
  }
References destruct().
mem() [6/45]
mem::mem () inline
Definition at line 537 of file build.cc.
  {
  }
mem() [7/45]
mem::mem (const char * x) inline
Definition at line 540 of file build.cc.
  {
   assign(*this,x);
  }
References assign().
mem() [8/45]
mem::mem (const mem & x) inline
Definition at line 544 of file build.cc.
  {
   assign(*this,x);
  }
References assign().
mem() [9/45]
mem::mem (const buf & x) inline
Definition at line 548 of file build.cc.
  {
   assign(*this,x);
  }
References assign().
mem() [10/45]
mem::mem (mem && x) inline
Definition at line 552 of file build.cc.
  {
   swap(*this,x);
  }
References swap().
~mem() [2/9]
mem::~mem () inline
Definition at line 556 of file build.cc.
  {
   destruct(*this);
  }
References destruct().
mem() [11/45]
mem::mem () inline
Definition at line 517 of file commit.cc.
  {
  }
mem() [12/45]
mem::mem (const char * x) inline
Definition at line 520 of file commit.cc.
  {
   assign(*this,x);
  }
References assign().
mem() [13/45]
mem::mem (const mem & x) inline
Definition at line 524 of file commit.cc.
  {
   assign(*this,x);
  }
References assign().
mem() [14/45]
mem::mem (const buf & x) inline
Definition at line 528 of file commit.cc.
  {
   assign(*this,x);
  }
References assign().
mem() [15/45]
mem::mem (mem && x) inline
Definition at line 532 of file commit.cc.
  {
   swap(*this,x);
  }
References swap().
~mem() [3/9]
mem::~mem () inline
Definition at line 536 of file commit.cc.
  {
   destruct(*this);
  }
References destruct().
mem() [16/45]
mem::mem () inline
Definition at line 516 of file convert.cc.
  {
  }
mem() [17/45]
mem::mem (const char * x) inline
Definition at line 519 of file convert.cc.
  {
   assign(*this,x);
  }
References assign().
mem() [18/45]
mem::mem (const mem & x) inline
Definition at line 523 of file convert.cc.
  {
   assign(*this,x);
  }
References assign().
mem() [19/45]
mem::mem (const buf & x) inline
Definition at line 527 of file convert.cc.
  {
   assign(*this,x);
  }
References assign().
mem() [20/45]
mem::mem (mem && x) inline
Definition at line 531 of file convert.cc.
  {
   swap(*this,x);
  }
References swap().
~mem() [4/9]
mem::~mem () inline
Definition at line 535 of file convert.cc.
  {
   destruct(*this);
  }
References destruct().
mem() [21/45]
mem::mem () inline
Definition at line 527 of file download.cc.
  {
  }
mem() [22/45]
mem::mem (const char * x) inline
Definition at line 530 of file download.cc.
  {
   assign(*this,x);
  }
References assign().
mem() [23/45]
mem::mem (const mem & x) inline
Definition at line 534 of file download.cc.
  {
   assign(*this,x);
  }
References assign().
mem() [24/45]
mem::mem (const buf & x) inline
Definition at line 538 of file download.cc.
  {
   assign(*this,x);
  }
References assign().
mem() [25/45]
mem::mem (mem && x) inline
Definition at line 542 of file download.cc.
  {
   swap(*this,x);
  }
References swap().
~mem() [5/9]
mem::~mem () inline
Definition at line 546 of file download.cc.
  {
   destruct(*this);
  }
References destruct().
mem() [26/45]
mem::mem () inline
Definition at line 517 of file explore.cc.
  {
  }
mem() [27/45]
mem::mem (const char * x) inline
Definition at line 520 of file explore.cc.
  {
   assign(*this,x);
  }
References assign().
mem() [28/45]
mem::mem (const mem & x) inline
Definition at line 524 of file explore.cc.
  {
   assign(*this,x);
  }
References assign().
mem() [29/45]
mem::mem (const buf & x) inline
Definition at line 528 of file explore.cc.
  {
   assign(*this,x);
  }
References assign().
mem() [30/45]
mem::mem (mem && x) inline
Definition at line 532 of file explore.cc.
  {
   swap(*this,x);
  }
References swap().
~mem() [6/9]
mem::~mem () inline
Definition at line 536 of file explore.cc.
  {
   destruct(*this);
  }
References destruct().
mem() [31/45]
mem::mem () inline
Definition at line 521 of file normalize.cc.
  {
  }
mem() [32/45]
mem::mem (const char * x) inline
Definition at line 524 of file normalize.cc.
  {
   assign(*this,x);
  }
References assign().
mem() [33/45]
mem::mem (const mem & x) inline
Definition at line 528 of file normalize.cc.
  {
   assign(*this,x);
  }
References assign().
mem() [34/45]
mem::mem (const buf & x) inline
Definition at line 532 of file normalize.cc.
  {
   assign(*this,x);
  }
References assign().
mem() [35/45]
mem::mem (mem && x) inline
Definition at line 536 of file normalize.cc.
  {
   swap(*this,x);
  }
References swap().
~mem() [7/9]
mem::~mem () inline
Definition at line 540 of file normalize.cc.
  {
   destruct(*this);
  }
References destruct().
mem() [36/45]
mem::mem () inline
Definition at line 532 of file serve.cc.
  {
  }
mem() [37/45]
mem::mem (const char * x) inline
Definition at line 535 of file serve.cc.
  {
   assign(*this,x);
  }
References assign().
mem() [38/45]
mem::mem (const mem & x) inline
Definition at line 539 of file serve.cc.
  {
   assign(*this,x);
  }
References assign().
mem() [39/45]
mem::mem (const buf & x) inline
Definition at line 543 of file serve.cc.
  {
   assign(*this,x);
  }
References assign().
mem() [40/45]
mem::mem (mem && x) inline
Definition at line 547 of file serve.cc.
  {
   swap(*this,x);
  }
References swap().
~mem() [8/9]
mem::~mem () inline
Definition at line 551 of file serve.cc.
  {
   destruct(*this);
  }
References destruct().
mem() [41/45]
mem::mem () inline
Definition at line 517 of file test.cc.
  {
  }
mem() [42/45]
mem::mem (const char * x) inline
Definition at line 520 of file test.cc.
  {
   assign(*this,x);
  }
References assign().
mem() [43/45]
mem::mem (const mem & x) inline
Definition at line 524 of file test.cc.
  {
   assign(*this,x);
  }
References assign().
mem() [44/45]
mem::mem (const buf & x) inline
Definition at line 528 of file test.cc.
  {
   assign(*this,x);
  }
References assign().
mem() [45/45]
mem::mem (mem && x) inline
Definition at line 532 of file test.cc.
  {
   swap(*this,x);
  }
References swap().
~mem() [9/9]
mem::~mem () inline
Definition at line 536 of file test.cc.
  {
   destruct(*this);
  }
References destruct().
Member Function Documentation
operator=() [1/36]
void mem::operator= (const buf & x) inline
Definition at line 547 of file backup.cc.
  {
   assign(*this,x);
  }
References assign().
operator=() [2/36]
void mem::operator= (const buf & x) inline
Definition at line 568 of file build.cc.
  {
   assign(*this,x);
  }
References assign().
operator=() [3/36]
void mem::operator= (const buf & x) inline
Definition at line 548 of file commit.cc.
  {
   assign(*this,x);
  }
References assign().
operator=() [4/36]
void mem::operator= (const buf & x) inline
Definition at line 547 of file convert.cc.
  {
   assign(*this,x);
  }
References assign().
operator=() [5/36]
void mem::operator= (const buf & x) inline
Definition at line 558 of file download.cc.
  {
   assign(*this,x);
  }
References assign().
operator=() [6/36]
void mem::operator= (const buf & x) inline
Definition at line 548 of file explore.cc.
  {
   assign(*this,x);
  }
References assign().
operator=() [7/36]
void mem::operator= (const buf & x) inline
Definition at line 552 of file normalize.cc.
  {
   assign(*this,x);
  }
References assign().
operator=() [8/36]
void mem::operator= (const buf & x) inline
Definition at line 563 of file serve.cc.
  {
   assign(*this,x);
  }
References assign().
operator=() [9/36]
void mem::operator= (const buf & x) inline
Definition at line 548 of file test.cc.
  {
   assign(*this,x);
  }
References assign().
operator=() [10/36]
void mem::operator= (const char * x) inline
Definition at line 539 of file backup.cc.
  {
   assign(*this,x);
  }
References assign().
operator=() [11/36]
void mem::operator= (const char * x) inline
Definition at line 560 of file build.cc.
  {
   assign(*this,x);
  }
References assign().
operator=() [12/36]
void mem::operator= (const char * x) inline
Definition at line 540 of file commit.cc.
  {
   assign(*this,x);
  }
References assign().
operator=() [13/36]
void mem::operator= (const char * x) inline
Definition at line 539 of file convert.cc.
  {
   assign(*this,x);
  }
References assign().
operator=() [14/36]
void mem::operator= (const char * x) inline
Definition at line 550 of file download.cc.
  {
   assign(*this,x);
  }
References assign().
operator=() [15/36]
void mem::operator= (const char * x) inline
Definition at line 540 of file explore.cc.
  {
   assign(*this,x);
  }
References assign().
operator=() [16/36]
void mem::operator= (const char * x) inline
Definition at line 544 of file normalize.cc.
  {
   assign(*this,x);
  }
References assign().
operator=() [17/36]
void mem::operator= (const char * x) inline
Definition at line 555 of file serve.cc.
  {
   assign(*this,x);
  }
References assign().
operator=() [18/36]
void mem::operator= (const char * x) inline
Definition at line 540 of file test.cc.
  {
   assign(*this,x);
  }
References assign().
operator=() [19/36]
void mem::operator= (const mem & x) inline
Definition at line 543 of file backup.cc.
  {
   assign(*this,x);
  }
References assign().
operator=() [20/36]
void mem::operator= (const mem & x) inline
Definition at line 564 of file build.cc.
  {
   assign(*this,x);
  }
References assign().
operator=() [21/36]
void mem::operator= (const mem & x) inline
Definition at line 544 of file commit.cc.
  {
   assign(*this,x);
  }
References assign().
operator=() [22/36]
void mem::operator= (const mem & x) inline
Definition at line 543 of file convert.cc.
  {
   assign(*this,x);
  }
References assign().
operator=() [23/36]
void mem::operator= (const mem & x) inline
Definition at line 554 of file download.cc.
  {
   assign(*this,x);
  }
References assign().
operator=() [24/36]
void mem::operator= (const mem & x) inline
Definition at line 544 of file explore.cc.
  {
   assign(*this,x);
  }
References assign().
operator=() [25/36]
void mem::operator= (const mem & x) inline
Definition at line 548 of file normalize.cc.
  {
   assign(*this,x);
  }
References assign().
operator=() [26/36]
void mem::operator= (const mem & x) inline
Definition at line 559 of file serve.cc.
  {
   assign(*this,x);
  }
References assign().
operator=() [27/36]
void mem::operator= (const mem & x) inline
Definition at line 544 of file test.cc.
  {
   assign(*this,x);
  }
References assign().
operator=() [28/36]
void mem::operator= (mem && x) inline
Definition at line 551 of file backup.cc.
  {
   swap(*this,x);
  }
References swap().
operator=() [29/36]
void mem::operator= (mem && x) inline
Definition at line 572 of file build.cc.
  {
   swap(*this,x);
  }
References swap().
operator=() [30/36]
void mem::operator= (mem && x) inline
Definition at line 552 of file commit.cc.
  {
   swap(*this,x);
  }
References swap().
operator=() [31/36]
void mem::operator= (mem && x) inline
Definition at line 551 of file convert.cc.
  {
   swap(*this,x);
  }
References swap().
operator=() [32/36]
void mem::operator= (mem && x) inline
Definition at line 562 of file download.cc.
  {
   swap(*this,x);
  }
References swap().
operator=() [33/36]
void mem::operator= (mem && x) inline
Definition at line 552 of file explore.cc.
  {
   swap(*this,x);
  }
References swap().
operator=() [34/36]
void mem::operator= (mem && x) inline
Definition at line 556 of file normalize.cc.
  {
   swap(*this,x);
  }
References swap().
operator=() [35/36]
void mem::operator= (mem && x) inline
Definition at line 567 of file serve.cc.
  {
   swap(*this,x);
  }
References swap().
operator=() [36/36]
void mem::operator= (mem && x) inline
Definition at line 552 of file test.cc.
  {
   swap(*this,x);
  }
References swap().
Member Data Documentation
pointer
ptr mem::pointer
Definition at line 515 of file backup.cc.
Referenced by allocate(), clear(), copy(), detach(), get_address(), get_length(), is_empty(), and swap().
The documentation for this struct was generated from the following files:
code/backup.cc
code/build.cc
code/commit.cc
code/convert.cc
code/download.cc
code/explore.cc
code/normalize.cc
code/serve.cc
code/test.cc