source: pfile Struct Reference
pfile Struct Reference
Public Member Functions
pfile ()
pfile (const pfile &x)
pfile (pfile &&x)
~pfile ()
void operator= (const pfile &x)
void operator= (pfile &&x)
pfile ()
pfile (const pfile &x)
pfile (pfile &&x)
~pfile ()
void operator= (const pfile &x)
void operator= (pfile &&x)
pfile ()
pfile (const pfile &x)
pfile (pfile &&x)
~pfile ()
void operator= (const pfile &x)
void operator= (pfile &&x)
pfile ()
pfile (const pfile &x)
pfile (pfile &&x)
~pfile ()
void operator= (const pfile &x)
void operator= (pfile &&x)
pfile ()
pfile (const pfile &x)
pfile (pfile &&x)
~pfile ()
void operator= (const pfile &x)
void operator= (pfile &&x)
pfile ()
pfile (const pfile &x)
pfile (pfile &&x)
~pfile ()
void operator= (const pfile &x)
void operator= (pfile &&x)
pfile ()
pfile (const pfile &x)
pfile (pfile &&x)
~pfile ()
void operator= (const pfile &x)
void operator= (pfile &&x)
pfile ()
pfile (const pfile &x)
pfile (pfile &&x)
~pfile ()
void operator= (const pfile &x)
void operator= (pfile &&x)
pfile ()
pfile (const pfile &x)
pfile (pfile &&x)
~pfile ()
void operator= (const pfile &x)
void operator= (pfile &&x)
Public Attributes
FILE * pointer =0
Detailed Description
Definition at line 697 of file backup.cc.
Constructor & Destructor Documentation
pfile() [1/27]
pfile::pfile () inline
Definition at line 700 of file backup.cc.
  {
  }
pfile() [2/27]
pfile::pfile (const pfile & x) inline
Definition at line 703 of file backup.cc.
  {
   stop();
  }
References stop().
pfile() [3/27]
pfile::pfile (pfile && x) inline
Definition at line 707 of file backup.cc.
  {
   stop();
  }
References stop().
~pfile() [1/9]
pfile::~pfile () inline
Definition at line 711 of file backup.cc.
  {
   destruct(*this);
  }
References destruct().
pfile() [4/27]
pfile::pfile () inline
Definition at line 721 of file build.cc.
  {
  }
pfile() [5/27]
pfile::pfile (const pfile & x) inline
Definition at line 724 of file build.cc.
  {
   stop();
  }
References stop().
pfile() [6/27]
pfile::pfile (pfile && x) inline
Definition at line 728 of file build.cc.
  {
   stop();
  }
References stop().
~pfile() [2/9]
pfile::~pfile () inline
Definition at line 732 of file build.cc.
  {
   destruct(*this);
  }
References destruct().
pfile() [7/27]
pfile::pfile () inline
Definition at line 701 of file commit.cc.
  {
  }
pfile() [8/27]
pfile::pfile (const pfile & x) inline
Definition at line 704 of file commit.cc.
  {
   stop();
  }
References stop().
pfile() [9/27]
pfile::pfile (pfile && x) inline
Definition at line 708 of file commit.cc.
  {
   stop();
  }
References stop().
~pfile() [3/9]
pfile::~pfile () inline
Definition at line 712 of file commit.cc.
  {
   destruct(*this);
  }
References destruct().
pfile() [10/27]
pfile::pfile () inline
Definition at line 700 of file convert.cc.
  {
  }
pfile() [11/27]
pfile::pfile (const pfile & x) inline
Definition at line 703 of file convert.cc.
  {
   stop();
  }
References stop().
pfile() [12/27]
pfile::pfile (pfile && x) inline
Definition at line 707 of file convert.cc.
  {
   stop();
  }
References stop().
~pfile() [4/9]
pfile::~pfile () inline
Definition at line 711 of file convert.cc.
  {
   destruct(*this);
  }
References destruct().
pfile() [13/27]
pfile::pfile () inline
Definition at line 711 of file download.cc.
  {
  }
pfile() [14/27]
pfile::pfile (const pfile & x) inline
Definition at line 714 of file download.cc.
  {
   stop();
  }
References stop().
pfile() [15/27]
pfile::pfile (pfile && x) inline
Definition at line 718 of file download.cc.
  {
   stop();
  }
References stop().
~pfile() [5/9]
pfile::~pfile () inline
Definition at line 722 of file download.cc.
  {
   destruct(*this);
  }
References destruct().
pfile() [16/27]
pfile::pfile () inline
Definition at line 701 of file explore.cc.
  {
  }
pfile() [17/27]
pfile::pfile (const pfile & x) inline
Definition at line 704 of file explore.cc.
  {
   stop();
  }
References stop().
pfile() [18/27]
pfile::pfile (pfile && x) inline
Definition at line 708 of file explore.cc.
  {
   stop();
  }
References stop().
~pfile() [6/9]
pfile::~pfile () inline
Definition at line 712 of file explore.cc.
  {
   destruct(*this);
  }
References destruct().
pfile() [19/27]
pfile::pfile () inline
Definition at line 705 of file normalize.cc.
  {
  }
pfile() [20/27]
pfile::pfile (const pfile & x) inline
Definition at line 708 of file normalize.cc.
  {
   stop();
  }
References stop().
pfile() [21/27]
pfile::pfile (pfile && x) inline
Definition at line 712 of file normalize.cc.
  {
   stop();
  }
References stop().
~pfile() [7/9]
pfile::~pfile () inline
Definition at line 716 of file normalize.cc.
  {
   destruct(*this);
  }
References destruct().
pfile() [22/27]
pfile::pfile () inline
Definition at line 716 of file serve.cc.
  {
  }
pfile() [23/27]
pfile::pfile (const pfile & x) inline
Definition at line 719 of file serve.cc.
  {
   stop();
  }
References stop().
pfile() [24/27]
pfile::pfile (pfile && x) inline
Definition at line 723 of file serve.cc.
  {
   stop();
  }
References stop().
~pfile() [8/9]
pfile::~pfile () inline
Definition at line 727 of file serve.cc.
  {
   destruct(*this);
  }
References destruct().
pfile() [25/27]
pfile::pfile () inline
Definition at line 701 of file test.cc.
  {
  }
pfile() [26/27]
pfile::pfile (const pfile & x) inline
Definition at line 704 of file test.cc.
  {
   stop();
  }
References stop().
pfile() [27/27]
pfile::pfile (pfile && x) inline
Definition at line 708 of file test.cc.
  {
   stop();
  }
References stop().
~pfile() [9/9]
pfile::~pfile () inline
Definition at line 712 of file test.cc.
  {
   destruct(*this);
  }
References destruct().
Member Function Documentation
operator=() [1/18]
void pfile::operator= (const pfile & x) inline
Definition at line 715 of file backup.cc.
  {
   stop();
  }
References stop().
operator=() [2/18]
void pfile::operator= (const pfile & x) inline
Definition at line 736 of file build.cc.
  {
   stop();
  }
References stop().
operator=() [3/18]
void pfile::operator= (const pfile & x) inline
Definition at line 716 of file commit.cc.
  {
   stop();
  }
References stop().
operator=() [4/18]
void pfile::operator= (const pfile & x) inline
Definition at line 715 of file convert.cc.
  {
   stop();
  }
References stop().
operator=() [5/18]
void pfile::operator= (const pfile & x) inline
Definition at line 726 of file download.cc.
  {
   stop();
  }
References stop().
operator=() [6/18]
void pfile::operator= (const pfile & x) inline
Definition at line 716 of file explore.cc.
  {
   stop();
  }
References stop().
operator=() [7/18]
void pfile::operator= (const pfile & x) inline
Definition at line 720 of file normalize.cc.
  {
   stop();
  }
References stop().
operator=() [8/18]
void pfile::operator= (const pfile & x) inline
Definition at line 731 of file serve.cc.
  {
   stop();
  }
References stop().
operator=() [9/18]
void pfile::operator= (const pfile & x) inline
Definition at line 716 of file test.cc.
  {
   stop();
  }
References stop().
operator=() [10/18]
void pfile::operator= (pfile && x) inline
Definition at line 719 of file backup.cc.
  {
   stop();
  }
References stop().
operator=() [11/18]
void pfile::operator= (pfile && x) inline
Definition at line 740 of file build.cc.
  {
   stop();
  }
References stop().
operator=() [12/18]
void pfile::operator= (pfile && x) inline
Definition at line 720 of file commit.cc.
  {
   stop();
  }
References stop().
operator=() [13/18]
void pfile::operator= (pfile && x) inline
Definition at line 719 of file convert.cc.
  {
   stop();
  }
References stop().
operator=() [14/18]
void pfile::operator= (pfile && x) inline
Definition at line 730 of file download.cc.
  {
   stop();
  }
References stop().
operator=() [15/18]
void pfile::operator= (pfile && x) inline
Definition at line 720 of file explore.cc.
  {
   stop();
  }
References stop().
operator=() [16/18]
void pfile::operator= (pfile && x) inline
Definition at line 724 of file normalize.cc.
  {
   stop();
  }
References stop().
operator=() [17/18]
void pfile::operator= (pfile && x) inline
Definition at line 735 of file serve.cc.
  {
   stop();
  }
References stop().
operator=() [18/18]
void pfile::operator= (pfile && x) inline
Definition at line 720 of file test.cc.
  {
   stop();
  }
References stop().
Member Data Documentation
pointer
FILE * pfile::pointer =0
Definition at line 699 of file backup.cc.
Referenced by clear(), is_empty(), open(), read(), and swap().
The documentation for this struct was generated from the following files:
code/backup.cc
code/build.cc
code/commit.cc
code/convert.cc
code/download.cc
code/explore.cc
code/normalize.cc
code/serve.cc
code/test.cc