source: timer Struct Reference
timer Struct Reference
Public Attributes
double start =get_now()
double duration =1
Detailed Description
Definition at line 751 of file backup.cc.
Member Data Documentation
duration
double timer::duration =1
Definition at line 754 of file backup.cc.
Referenced by clear(), hit(), swap(), and timeout().
start
double timer::start =get_now()
Definition at line 753 of file backup.cc.
Referenced by clear(), hit(), and swap().
The documentation for this struct was generated from the following files:
code/backup.cc
code/build.cc
code/commit.cc
code/convert.cc
code/download.cc
code/explore.cc
code/normalize.cc
code/serve.cc
code/test.cc