source: fd Struct Reference
fd Struct Reference
Public Member Functions
fd ()
fd (const fd &x)
fd (fd &&x)
~fd ()
void operator= (const fd &x)
void operator= (fd &&x)
fd ()
fd (const fd &x)
fd (fd &&x)
~fd ()
void operator= (const fd &x)
void operator= (fd &&x)
fd ()
fd (const fd &x)
fd (fd &&x)
~fd ()
void operator= (const fd &x)
void operator= (fd &&x)
fd ()
fd (const fd &x)
fd (fd &&x)
~fd ()
void operator= (const fd &x)
void operator= (fd &&x)
fd ()
fd (const fd &x)
fd (fd &&x)
~fd ()
void operator= (const fd &x)
void operator= (fd &&x)
fd ()
fd (const fd &x)
fd (fd &&x)
~fd ()
void operator= (const fd &x)
void operator= (fd &&x)
fd ()
fd (const fd &x)
fd (fd &&x)
~fd ()
void operator= (const fd &x)
void operator= (fd &&x)
fd ()
fd (const fd &x)
fd (fd &&x)
~fd ()
void operator= (const fd &x)
void operator= (fd &&x)
fd ()
fd (const fd &x)
fd (fd &&x)
~fd ()
void operator= (const fd &x)
void operator= (fd &&x)
Public Attributes
int handle =-1
Detailed Description
Definition at line 670 of file backup.cc.
Constructor & Destructor Documentation
fd() [1/27]
fd::fd () inline
Definition at line 673 of file backup.cc.
  {
  }
fd() [2/27]
fd::fd (const fd & x) inline
Definition at line 676 of file backup.cc.
  {
   stop();
  }
References stop().
fd() [3/27]
fd::fd (fd && x) inline
Definition at line 680 of file backup.cc.
  {
   swap(*this,x);
  }
References swap().
~fd() [1/9]
fd::~fd () inline
Definition at line 684 of file backup.cc.
  {
   destruct(*this);
  }
References destruct().
fd() [4/27]
fd::fd () inline
Definition at line 694 of file build.cc.
  {
  }
fd() [5/27]
fd::fd (const fd & x) inline
Definition at line 697 of file build.cc.
  {
   stop();
  }
References stop().
fd() [6/27]
fd::fd (fd && x) inline
Definition at line 701 of file build.cc.
  {
   swap(*this,x);
  }
References swap().
~fd() [2/9]
fd::~fd () inline
Definition at line 705 of file build.cc.
  {
   destruct(*this);
  }
References destruct().
fd() [7/27]
fd::fd () inline
Definition at line 674 of file commit.cc.
  {
  }
fd() [8/27]
fd::fd (const fd & x) inline
Definition at line 677 of file commit.cc.
  {
   stop();
  }
References stop().
fd() [9/27]
fd::fd (fd && x) inline
Definition at line 681 of file commit.cc.
  {
   swap(*this,x);
  }
References swap().
~fd() [3/9]
fd::~fd () inline
Definition at line 685 of file commit.cc.
  {
   destruct(*this);
  }
References destruct().
fd() [10/27]
fd::fd () inline
Definition at line 673 of file convert.cc.
  {
  }
fd() [11/27]
fd::fd (const fd & x) inline
Definition at line 676 of file convert.cc.
  {
   stop();
  }
References stop().
fd() [12/27]
fd::fd (fd && x) inline
Definition at line 680 of file convert.cc.
  {
   swap(*this,x);
  }
References swap().
~fd() [4/9]
fd::~fd () inline
Definition at line 684 of file convert.cc.
  {
   destruct(*this);
  }
References destruct().
fd() [13/27]
fd::fd () inline
Definition at line 684 of file download.cc.
  {
  }
fd() [14/27]
fd::fd (const fd & x) inline
Definition at line 687 of file download.cc.
  {
   stop();
  }
References stop().
fd() [15/27]
fd::fd (fd && x) inline
Definition at line 691 of file download.cc.
  {
   swap(*this,x);
  }
References swap().
~fd() [5/9]
fd::~fd () inline
Definition at line 695 of file download.cc.
  {
   destruct(*this);
  }
References destruct().
fd() [16/27]
fd::fd () inline
Definition at line 674 of file explore.cc.
  {
  }
fd() [17/27]
fd::fd (const fd & x) inline
Definition at line 677 of file explore.cc.
  {
   stop();
  }
References stop().
fd() [18/27]
fd::fd (fd && x) inline
Definition at line 681 of file explore.cc.
  {
   swap(*this,x);
  }
References swap().
~fd() [6/9]
fd::~fd () inline
Definition at line 685 of file explore.cc.
  {
   destruct(*this);
  }
References destruct().
fd() [19/27]
fd::fd () inline
Definition at line 678 of file normalize.cc.
  {
  }
fd() [20/27]
fd::fd (const fd & x) inline
Definition at line 681 of file normalize.cc.
  {
   stop();
  }
References stop().
fd() [21/27]
fd::fd (fd && x) inline
Definition at line 685 of file normalize.cc.
  {
   swap(*this,x);
  }
References swap().
~fd() [7/9]
fd::~fd () inline
Definition at line 689 of file normalize.cc.
  {
   destruct(*this);
  }
References destruct().
fd() [22/27]
fd::fd () inline
Definition at line 689 of file serve.cc.
  {
  }
fd() [23/27]
fd::fd (const fd & x) inline
Definition at line 692 of file serve.cc.
  {
   stop();
  }
References stop().
fd() [24/27]
fd::fd (fd && x) inline
Definition at line 696 of file serve.cc.
  {
   swap(*this,x);
  }
References swap().
~fd() [8/9]
fd::~fd () inline
Definition at line 700 of file serve.cc.
  {
   destruct(*this);
  }
References destruct().
fd() [25/27]
fd::fd () inline
Definition at line 674 of file test.cc.
  {
  }
fd() [26/27]
fd::fd (const fd & x) inline
Definition at line 677 of file test.cc.
  {
   stop();
  }
References stop().
fd() [27/27]
fd::fd (fd && x) inline
Definition at line 681 of file test.cc.
  {
   swap(*this,x);
  }
References swap().
~fd() [9/9]
fd::~fd () inline
Definition at line 685 of file test.cc.
  {
   destruct(*this);
  }
References destruct().
Member Function Documentation
operator=() [1/18]
void fd::operator= (const fd & x) inline
Definition at line 688 of file backup.cc.
  {
   stop();
  }
References stop().
operator=() [2/18]
void fd::operator= (const fd & x) inline
Definition at line 709 of file build.cc.
  {
   stop();
  }
References stop().
operator=() [3/18]
void fd::operator= (const fd & x) inline
Definition at line 689 of file commit.cc.
  {
   stop();
  }
References stop().
operator=() [4/18]
void fd::operator= (const fd & x) inline
Definition at line 688 of file convert.cc.
  {
   stop();
  }
References stop().
operator=() [5/18]
void fd::operator= (const fd & x) inline
Definition at line 699 of file download.cc.
  {
   stop();
  }
References stop().
operator=() [6/18]
void fd::operator= (const fd & x) inline
Definition at line 689 of file explore.cc.
  {
   stop();
  }
References stop().
operator=() [7/18]
void fd::operator= (const fd & x) inline
Definition at line 693 of file normalize.cc.
  {
   stop();
  }
References stop().
operator=() [8/18]
void fd::operator= (const fd & x) inline
Definition at line 704 of file serve.cc.
  {
   stop();
  }
References stop().
operator=() [9/18]
void fd::operator= (const fd & x) inline
Definition at line 689 of file test.cc.
  {
   stop();
  }
References stop().
operator=() [10/18]
void fd::operator= (fd && x) inline
Definition at line 692 of file backup.cc.
  {
   swap(*this,x);
  }
References swap().
operator=() [11/18]
void fd::operator= (fd && x) inline
Definition at line 713 of file build.cc.
  {
   swap(*this,x);
  }
References swap().
operator=() [12/18]
void fd::operator= (fd && x) inline
Definition at line 693 of file commit.cc.
  {
   swap(*this,x);
  }
References swap().
operator=() [13/18]
void fd::operator= (fd && x) inline
Definition at line 692 of file convert.cc.
  {
   swap(*this,x);
  }
References swap().
operator=() [14/18]
void fd::operator= (fd && x) inline
Definition at line 703 of file download.cc.
  {
   swap(*this,x);
  }
References swap().
operator=() [15/18]
void fd::operator= (fd && x) inline
Definition at line 693 of file explore.cc.
  {
   swap(*this,x);
  }
References swap().
operator=() [16/18]
void fd::operator= (fd && x) inline
Definition at line 697 of file normalize.cc.
  {
   swap(*this,x);
  }
References swap().
operator=() [17/18]
void fd::operator= (fd && x) inline
Definition at line 708 of file serve.cc.
  {
   swap(*this,x);
  }
References swap().
operator=() [18/18]
void fd::operator= (fd && x) inline
Definition at line 693 of file test.cc.
  {
   swap(*this,x);
  }
References swap().
Member Data Documentation
handle
int fd::handle =-1
Definition at line 672 of file backup.cc.
Referenced by accept(), clear(), get_ip(), is_empty(), listen(), open(), read(), receive(), send(), set_non_block(), swap(), term_read(), and write().
The documentation for this struct was generated from the following files:
code/backup.cc
code/build.cc
code/commit.cc
code/convert.cc
code/download.cc
code/explore.cc
code/normalize.cc
code/serve.cc
code/test.cc