source: pthread Struct Reference
pthread Struct Reference
Public Member Functions
pthread ()
pthread (const pthread &x)
pthread (pthread &&x)
~pthread ()
void operator= (const pthread &x)
void operator= (pthread &&x)
pthread ()
pthread (const pthread &x)
pthread (pthread &&x)
~pthread ()
void operator= (const pthread &x)
void operator= (pthread &&x)
pthread ()
pthread (const pthread &x)
pthread (pthread &&x)
~pthread ()
void operator= (const pthread &x)
void operator= (pthread &&x)
pthread ()
pthread (const pthread &x)
pthread (pthread &&x)
~pthread ()
void operator= (const pthread &x)
void operator= (pthread &&x)
pthread ()
pthread (const pthread &x)
pthread (pthread &&x)
~pthread ()
void operator= (const pthread &x)
void operator= (pthread &&x)
pthread ()
pthread (const pthread &x)
pthread (pthread &&x)
~pthread ()
void operator= (const pthread &x)
void operator= (pthread &&x)
pthread ()
pthread (const pthread &x)
pthread (pthread &&x)
~pthread ()
void operator= (const pthread &x)
void operator= (pthread &&x)
pthread ()
pthread (const pthread &x)
pthread (pthread &&x)
~pthread ()
void operator= (const pthread &x)
void operator= (pthread &&x)
pthread ()
pthread (const pthread &x)
pthread (pthread &&x)
~pthread ()
void operator= (const pthread &x)
void operator= (pthread &&x)
Public Attributes
pthread_t pointer =0
Detailed Description
Definition at line 724 of file backup.cc.
Constructor & Destructor Documentation
pthread() [1/27]
pthread::pthread () inline
Definition at line 727 of file backup.cc.
  {
  }
pthread() [2/27]
pthread::pthread (const pthread & x) inline
Definition at line 730 of file backup.cc.
  {
   stop();
  }
References stop().
pthread() [3/27]
pthread::pthread (pthread && x) inline
Definition at line 734 of file backup.cc.
  {
   stop();
  }
References stop().
~pthread() [1/9]
pthread::~pthread () inline
Definition at line 738 of file backup.cc.
  {
   destruct(*this);
  }
References destruct().
pthread() [4/27]
pthread::pthread () inline
Definition at line 748 of file build.cc.
  {
  }
pthread() [5/27]
pthread::pthread (const pthread & x) inline
Definition at line 751 of file build.cc.
  {
   stop();
  }
References stop().
pthread() [6/27]
pthread::pthread (pthread && x) inline
Definition at line 755 of file build.cc.
  {
   stop();
  }
References stop().
~pthread() [2/9]
pthread::~pthread () inline
Definition at line 759 of file build.cc.
  {
   destruct(*this);
  }
References destruct().
pthread() [7/27]
pthread::pthread () inline
Definition at line 728 of file commit.cc.
  {
  }
pthread() [8/27]
pthread::pthread (const pthread & x) inline
Definition at line 731 of file commit.cc.
  {
   stop();
  }
References stop().
pthread() [9/27]
pthread::pthread (pthread && x) inline
Definition at line 735 of file commit.cc.
  {
   stop();
  }
References stop().
~pthread() [3/9]
pthread::~pthread () inline
Definition at line 739 of file commit.cc.
  {
   destruct(*this);
  }
References destruct().
pthread() [10/27]
pthread::pthread () inline
Definition at line 727 of file convert.cc.
  {
  }
pthread() [11/27]
pthread::pthread (const pthread & x) inline
Definition at line 730 of file convert.cc.
  {
   stop();
  }
References stop().
pthread() [12/27]
pthread::pthread (pthread && x) inline
Definition at line 734 of file convert.cc.
  {
   stop();
  }
References stop().
~pthread() [4/9]
pthread::~pthread () inline
Definition at line 738 of file convert.cc.
  {
   destruct(*this);
  }
References destruct().
pthread() [13/27]
pthread::pthread () inline
Definition at line 738 of file download.cc.
  {
  }
pthread() [14/27]
pthread::pthread (const pthread & x) inline
Definition at line 741 of file download.cc.
  {
   stop();
  }
References stop().
pthread() [15/27]
pthread::pthread (pthread && x) inline
Definition at line 745 of file download.cc.
  {
   stop();
  }
References stop().
~pthread() [5/9]
pthread::~pthread () inline
Definition at line 749 of file download.cc.
  {
   destruct(*this);
  }
References destruct().
pthread() [16/27]
pthread::pthread () inline
Definition at line 728 of file explore.cc.
  {
  }
pthread() [17/27]
pthread::pthread (const pthread & x) inline
Definition at line 731 of file explore.cc.
  {
   stop();
  }
References stop().
pthread() [18/27]
pthread::pthread (pthread && x) inline
Definition at line 735 of file explore.cc.
  {
   stop();
  }
References stop().
~pthread() [6/9]
pthread::~pthread () inline
Definition at line 739 of file explore.cc.
  {
   destruct(*this);
  }
References destruct().
pthread() [19/27]
pthread::pthread () inline
Definition at line 732 of file normalize.cc.
  {
  }
pthread() [20/27]
pthread::pthread (const pthread & x) inline
Definition at line 735 of file normalize.cc.
  {
   stop();
  }
References stop().
pthread() [21/27]
pthread::pthread (pthread && x) inline
Definition at line 739 of file normalize.cc.
  {
   stop();
  }
References stop().
~pthread() [7/9]
pthread::~pthread () inline
Definition at line 743 of file normalize.cc.
  {
   destruct(*this);
  }
References destruct().
pthread() [22/27]
pthread::pthread () inline
Definition at line 743 of file serve.cc.
  {
  }
pthread() [23/27]
pthread::pthread (const pthread & x) inline
Definition at line 746 of file serve.cc.
  {
   stop();
  }
References stop().
pthread() [24/27]
pthread::pthread (pthread && x) inline
Definition at line 750 of file serve.cc.
  {
   stop();
  }
References stop().
~pthread() [8/9]
pthread::~pthread () inline
Definition at line 754 of file serve.cc.
  {
   destruct(*this);
  }
References destruct().
pthread() [25/27]
pthread::pthread () inline
Definition at line 728 of file test.cc.
  {
  }
pthread() [26/27]
pthread::pthread (const pthread & x) inline
Definition at line 731 of file test.cc.
  {
   stop();
  }
References stop().
pthread() [27/27]
pthread::pthread (pthread && x) inline
Definition at line 735 of file test.cc.
  {
   stop();
  }
References stop().
~pthread() [9/9]
pthread::~pthread () inline
Definition at line 739 of file test.cc.
  {
   destruct(*this);
  }
References destruct().
Member Function Documentation
operator=() [1/18]
void pthread::operator= (const pthread & x) inline
Definition at line 742 of file backup.cc.
  {
   stop();
  }
References stop().
operator=() [2/18]
void pthread::operator= (const pthread & x) inline
Definition at line 763 of file build.cc.
  {
   stop();
  }
References stop().
operator=() [3/18]
void pthread::operator= (const pthread & x) inline
Definition at line 743 of file commit.cc.
  {
   stop();
  }
References stop().
operator=() [4/18]
void pthread::operator= (const pthread & x) inline
Definition at line 742 of file convert.cc.
  {
   stop();
  }
References stop().
operator=() [5/18]
void pthread::operator= (const pthread & x) inline
Definition at line 753 of file download.cc.
  {
   stop();
  }
References stop().
operator=() [6/18]
void pthread::operator= (const pthread & x) inline
Definition at line 743 of file explore.cc.
  {
   stop();
  }
References stop().
operator=() [7/18]
void pthread::operator= (const pthread & x) inline
Definition at line 747 of file normalize.cc.
  {
   stop();
  }
References stop().
operator=() [8/18]
void pthread::operator= (const pthread & x) inline
Definition at line 758 of file serve.cc.
  {
   stop();
  }
References stop().
operator=() [9/18]
void pthread::operator= (const pthread & x) inline
Definition at line 743 of file test.cc.
  {
   stop();
  }
References stop().
operator=() [10/18]
void pthread::operator= (pthread && x) inline
Definition at line 746 of file backup.cc.
  {
   stop();
  }
References stop().
operator=() [11/18]
void pthread::operator= (pthread && x) inline
Definition at line 767 of file build.cc.
  {
   stop();
  }
References stop().
operator=() [12/18]
void pthread::operator= (pthread && x) inline
Definition at line 747 of file commit.cc.
  {
   stop();
  }
References stop().
operator=() [13/18]
void pthread::operator= (pthread && x) inline
Definition at line 746 of file convert.cc.
  {
   stop();
  }
References stop().
operator=() [14/18]
void pthread::operator= (pthread && x) inline
Definition at line 757 of file download.cc.
  {
   stop();
  }
References stop().
operator=() [15/18]
void pthread::operator= (pthread && x) inline
Definition at line 747 of file explore.cc.
  {
   stop();
  }
References stop().
operator=() [16/18]
void pthread::operator= (pthread && x) inline
Definition at line 751 of file normalize.cc.
  {
   stop();
  }
References stop().
operator=() [17/18]
void pthread::operator= (pthread && x) inline
Definition at line 762 of file serve.cc.
  {
   stop();
  }
References stop().
operator=() [18/18]
void pthread::operator= (pthread && x) inline
Definition at line 747 of file test.cc.
  {
   stop();
  }
References stop().
Member Data Documentation
pointer
pthread_t pthread::pointer =0
Definition at line 726 of file backup.cc.
Referenced by clear(), create(), and is_empty().
The documentation for this struct was generated from the following files:
code/backup.cc
code/build.cc
code/commit.cc
code/convert.cc
code/download.cc
code/explore.cc
code/normalize.cc
code/serve.cc
code/test.cc