source: buf Struct Reference
buf Struct Reference
Public Member Functions
buf ()
buf (const char *x)
buf (const buf &x)
buf (buf &&x)
void operator= (const char *x)
void operator= (const buf &x)
void operator= (buf &&x)
buf ()
buf (const char *x)
buf (const buf &x)
buf (buf &&x)
void operator= (const char *x)
void operator= (const buf &x)
void operator= (buf &&x)
buf ()
buf (const char *x)
buf (const buf &x)
buf (buf &&x)
void operator= (const char *x)
void operator= (const buf &x)
void operator= (buf &&x)
buf ()
buf (const char *x)
buf (const buf &x)
buf (buf &&x)
void operator= (const char *x)
void operator= (const buf &x)
void operator= (buf &&x)
buf ()
buf (const char *x)
buf (const buf &x)
buf (buf &&x)
void operator= (const char *x)
void operator= (const buf &x)
void operator= (buf &&x)
buf ()
buf (const char *x)
buf (const buf &x)
buf (buf &&x)
void operator= (const char *x)
void operator= (const buf &x)
void operator= (buf &&x)
buf ()
buf (const char *x)
buf (const buf &x)
buf (buf &&x)
void operator= (const char *x)
void operator= (const buf &x)
void operator= (buf &&x)
buf ()
buf (const char *x)
buf (const buf &x)
buf (buf &&x)
void operator= (const char *x)
void operator= (const buf &x)
void operator= (buf &&x)
buf ()
buf (const char *x)
buf (const buf &x)
buf (buf &&x)
void operator= (const char *x)
void operator= (const buf &x)
void operator= (buf &&x)
Public Attributes
int index =0
int length =0
mem memory
Detailed Description
Definition at line 556 of file backup.cc.
Constructor & Destructor Documentation
buf() [1/36]
buf::buf () inline
Definition at line 561 of file backup.cc.
  {
  }
buf() [2/36]
buf::buf (const char * x) inline
Definition at line 564 of file backup.cc.
  {
   assign(*this,x);
  }
References assign().
buf() [3/36]
buf::buf (const buf & x) inline
Definition at line 568 of file backup.cc.
  {
   assign(*this,x);
  }
References assign().
buf() [4/36]
buf::buf (buf && x) inline
Definition at line 572 of file backup.cc.
  {
   swap(*this,x);
  }
References swap().
buf() [5/36]
buf::buf () inline
Definition at line 582 of file build.cc.
  {
  }
buf() [6/36]
buf::buf (const char * x) inline
Definition at line 585 of file build.cc.
  {
   assign(*this,x);
  }
References assign().
buf() [7/36]
buf::buf (const buf & x) inline
Definition at line 589 of file build.cc.
  {
   assign(*this,x);
  }
References assign().
buf() [8/36]
buf::buf (buf && x) inline
Definition at line 593 of file build.cc.
  {
   swap(*this,x);
  }
References swap().
buf() [9/36]
buf::buf () inline
Definition at line 562 of file commit.cc.
  {
  }
buf() [10/36]
buf::buf (const char * x) inline
Definition at line 565 of file commit.cc.
  {
   assign(*this,x);
  }
References assign().
buf() [11/36]
buf::buf (const buf & x) inline
Definition at line 569 of file commit.cc.
  {
   assign(*this,x);
  }
References assign().
buf() [12/36]
buf::buf (buf && x) inline
Definition at line 573 of file commit.cc.
  {
   swap(*this,x);
  }
References swap().
buf() [13/36]
buf::buf () inline
Definition at line 561 of file convert.cc.
  {
  }
buf() [14/36]
buf::buf (const char * x) inline
Definition at line 564 of file convert.cc.
  {
   assign(*this,x);
  }
References assign().
buf() [15/36]
buf::buf (const buf & x) inline
Definition at line 568 of file convert.cc.
  {
   assign(*this,x);
  }
References assign().
buf() [16/36]
buf::buf (buf && x) inline
Definition at line 572 of file convert.cc.
  {
   swap(*this,x);
  }
References swap().
buf() [17/36]
buf::buf () inline
Definition at line 572 of file download.cc.
  {
  }
buf() [18/36]
buf::buf (const char * x) inline
Definition at line 575 of file download.cc.
  {
   assign(*this,x);
  }
References assign().
buf() [19/36]
buf::buf (const buf & x) inline
Definition at line 579 of file download.cc.
  {
   assign(*this,x);
  }
References assign().
buf() [20/36]
buf::buf (buf && x) inline
Definition at line 583 of file download.cc.
  {
   swap(*this,x);
  }
References swap().
buf() [21/36]
buf::buf () inline
Definition at line 562 of file explore.cc.
  {
  }
buf() [22/36]
buf::buf (const char * x) inline
Definition at line 565 of file explore.cc.
  {
   assign(*this,x);
  }
References assign().
buf() [23/36]
buf::buf (const buf & x) inline
Definition at line 569 of file explore.cc.
  {
   assign(*this,x);
  }
References assign().
buf() [24/36]
buf::buf (buf && x) inline
Definition at line 573 of file explore.cc.
  {
   swap(*this,x);
  }
References swap().
buf() [25/36]
buf::buf () inline
Definition at line 566 of file normalize.cc.
  {
  }
buf() [26/36]
buf::buf (const char * x) inline
Definition at line 569 of file normalize.cc.
  {
   assign(*this,x);
  }
References assign().
buf() [27/36]
buf::buf (const buf & x) inline
Definition at line 573 of file normalize.cc.
  {
   assign(*this,x);
  }
References assign().
buf() [28/36]
buf::buf (buf && x) inline
Definition at line 577 of file normalize.cc.
  {
   swap(*this,x);
  }
References swap().
buf() [29/36]
buf::buf () inline
Definition at line 577 of file serve.cc.
  {
  }
buf() [30/36]
buf::buf (const char * x) inline
Definition at line 580 of file serve.cc.
  {
   assign(*this,x);
  }
References assign().
buf() [31/36]
buf::buf (const buf & x) inline
Definition at line 584 of file serve.cc.
  {
   assign(*this,x);
  }
References assign().
buf() [32/36]
buf::buf (buf && x) inline
Definition at line 588 of file serve.cc.
  {
   swap(*this,x);
  }
References swap().
buf() [33/36]
buf::buf () inline
Definition at line 562 of file test.cc.
  {
  }
buf() [34/36]
buf::buf (const char * x) inline
Definition at line 565 of file test.cc.
  {
   assign(*this,x);
  }
References assign().
buf() [35/36]
buf::buf (const buf & x) inline
Definition at line 569 of file test.cc.
  {
   assign(*this,x);
  }
References assign().
buf() [36/36]
buf::buf (buf && x) inline
Definition at line 573 of file test.cc.
  {
   swap(*this,x);
  }
References swap().
Member Function Documentation
operator=() [1/27]
void buf::operator= (buf && x) inline
Definition at line 584 of file backup.cc.
  {
   swap(*this,x);
  }
References swap().
operator=() [2/27]
void buf::operator= (buf && x) inline
Definition at line 605 of file build.cc.
  {
   swap(*this,x);
  }
References swap().
operator=() [3/27]
void buf::operator= (buf && x) inline
Definition at line 585 of file commit.cc.
  {
   swap(*this,x);
  }
References swap().
operator=() [4/27]
void buf::operator= (buf && x) inline
Definition at line 584 of file convert.cc.
  {
   swap(*this,x);
  }
References swap().
operator=() [5/27]
void buf::operator= (buf && x) inline
Definition at line 595 of file download.cc.
  {
   swap(*this,x);
  }
References swap().
operator=() [6/27]
void buf::operator= (buf && x) inline
Definition at line 585 of file explore.cc.
  {
   swap(*this,x);
  }
References swap().
operator=() [7/27]
void buf::operator= (buf && x) inline
Definition at line 589 of file normalize.cc.
  {
   swap(*this,x);
  }
References swap().
operator=() [8/27]
void buf::operator= (buf && x) inline
Definition at line 600 of file serve.cc.
  {
   swap(*this,x);
  }
References swap().
operator=() [9/27]
void buf::operator= (buf && x) inline
Definition at line 585 of file test.cc.
  {
   swap(*this,x);
  }
References swap().
operator=() [10/27]
void buf::operator= (const buf & x) inline
Definition at line 580 of file backup.cc.
  {
   assign(*this,x);
  }
References assign().
operator=() [11/27]
void buf::operator= (const buf & x) inline
Definition at line 601 of file build.cc.
  {
   assign(*this,x);
  }
References assign().
operator=() [12/27]
void buf::operator= (const buf & x) inline
Definition at line 581 of file commit.cc.
  {
   assign(*this,x);
  }
References assign().
operator=() [13/27]
void buf::operator= (const buf & x) inline
Definition at line 580 of file convert.cc.
  {
   assign(*this,x);
  }
References assign().
operator=() [14/27]
void buf::operator= (const buf & x) inline
Definition at line 591 of file download.cc.
  {
   assign(*this,x);
  }
References assign().
operator=() [15/27]
void buf::operator= (const buf & x) inline
Definition at line 581 of file explore.cc.
  {
   assign(*this,x);
  }
References assign().
operator=() [16/27]
void buf::operator= (const buf & x) inline
Definition at line 585 of file normalize.cc.
  {
   assign(*this,x);
  }
References assign().
operator=() [17/27]
void buf::operator= (const buf & x) inline
Definition at line 596 of file serve.cc.
  {
   assign(*this,x);
  }
References assign().
operator=() [18/27]
void buf::operator= (const buf & x) inline
Definition at line 581 of file test.cc.
  {
   assign(*this,x);
  }
References assign().
operator=() [19/27]
void buf::operator= (const char * x) inline
Definition at line 576 of file backup.cc.
  {
   assign(*this,x);
  }
References assign().
operator=() [20/27]
void buf::operator= (const char * x) inline
Definition at line 597 of file build.cc.
  {
   assign(*this,x);
  }
References assign().
operator=() [21/27]
void buf::operator= (const char * x) inline
Definition at line 577 of file commit.cc.
  {
   assign(*this,x);
  }
References assign().
operator=() [22/27]
void buf::operator= (const char * x) inline
Definition at line 576 of file convert.cc.
  {
   assign(*this,x);
  }
References assign().
operator=() [23/27]
void buf::operator= (const char * x) inline
Definition at line 587 of file download.cc.
  {
   assign(*this,x);
  }
References assign().
operator=() [24/27]
void buf::operator= (const char * x) inline
Definition at line 577 of file explore.cc.
  {
   assign(*this,x);
  }
References assign().
operator=() [25/27]
void buf::operator= (const char * x) inline
Definition at line 581 of file normalize.cc.
  {
   assign(*this,x);
  }
References assign().
operator=() [26/27]
void buf::operator= (const char * x) inline
Definition at line 592 of file serve.cc.
  {
   assign(*this,x);
  }
References assign().
operator=() [27/27]
void buf::operator= (const char * x) inline
Definition at line 577 of file test.cc.
  {
   assign(*this,x);
  }
References assign().
Member Data Documentation
index
int buf::index =0
Definition at line 558 of file backup.cc.
Referenced by clear(), copy(), drop_l(), get_offset(), is_circular(), is_normal(), reset(), swap(), and unshift().
length
int buf::length =0
Definition at line 559 of file backup.cc.
Referenced by clear(), dim(), drop_l(), drop_r(), get_length(), get_overhead(), is_circular(), is_empty(), is_filled(), normalize(), push(), reserve(), reset(), swap(), and unshift().
memory
mem buf::memory
Definition at line 560 of file backup.cc.
Referenced by at(), clear(), copy(), detach(), get_capacity(), normalize(), reserve(), set(), and swap().
The documentation for this struct was generated from the following files:
code/backup.cc
code/build.cc
code/commit.cc
code/convert.cc
code/download.cc
code/explore.cc
code/normalize.cc
code/serve.cc
code/test.cc