source: seq Struct Reference
seq Struct Reference
Public Member Functions
seq ()
seq (const seq &x)
seq (seq &&x)
void operator= (const seq &x)
void operator= (seq &&x)
seq ()
seq (const seq &x)
seq (seq &&x)
void operator= (const seq &x)
void operator= (seq &&x)
seq ()
seq (const seq &x)
seq (seq &&x)
void operator= (const seq &x)
void operator= (seq &&x)
seq ()
seq (const seq &x)
seq (seq &&x)
void operator= (const seq &x)
void operator= (seq &&x)
seq ()
seq (const seq &x)
seq (seq &&x)
void operator= (const seq &x)
void operator= (seq &&x)
seq ()
seq (const seq &x)
seq (seq &&x)
void operator= (const seq &x)
void operator= (seq &&x)
seq ()
seq (const seq &x)
seq (seq &&x)
void operator= (const seq &x)
void operator= (seq &&x)
seq ()
seq (const seq &x)
seq (seq &&x)
void operator= (const seq &x)
void operator= (seq &&x)
seq ()
seq (const seq &x)
seq (seq &&x)
void operator= (const seq &x)
void operator= (seq &&x)
Public Attributes
txt text
Detailed Description
Definition at line 612 of file backup.cc.
Constructor & Destructor Documentation
seq() [1/27]
seq::seq () inline
Definition at line 615 of file backup.cc.
  {
  }
seq() [2/27]
seq::seq (const seq & x) inline
Definition at line 618 of file backup.cc.
  {
   assign(*this,x);
  }
References assign().
seq() [3/27]
seq::seq (seq && x) inline
Definition at line 622 of file backup.cc.
  {
   swap(*this,x);
  }
References swap().
seq() [4/27]
seq::seq () inline
Definition at line 636 of file build.cc.
  {
  }
seq() [5/27]
seq::seq (const seq & x) inline
Definition at line 639 of file build.cc.
  {
   assign(*this,x);
  }
References assign().
seq() [6/27]
seq::seq (seq && x) inline
Definition at line 643 of file build.cc.
  {
   swap(*this,x);
  }
References swap().
seq() [7/27]
seq::seq () inline
Definition at line 616 of file commit.cc.
  {
  }
seq() [8/27]
seq::seq (const seq & x) inline
Definition at line 619 of file commit.cc.
  {
   assign(*this,x);
  }
References assign().
seq() [9/27]
seq::seq (seq && x) inline
Definition at line 623 of file commit.cc.
  {
   swap(*this,x);
  }
References swap().
seq() [10/27]
seq::seq () inline
Definition at line 615 of file convert.cc.
  {
  }
seq() [11/27]
seq::seq (const seq & x) inline
Definition at line 618 of file convert.cc.
  {
   assign(*this,x);
  }
References assign().
seq() [12/27]
seq::seq (seq && x) inline
Definition at line 622 of file convert.cc.
  {
   swap(*this,x);
  }
References swap().
seq() [13/27]
seq::seq () inline
Definition at line 626 of file download.cc.
  {
  }
seq() [14/27]
seq::seq (const seq & x) inline
Definition at line 629 of file download.cc.
  {
   assign(*this,x);
  }
References assign().
seq() [15/27]
seq::seq (seq && x) inline
Definition at line 633 of file download.cc.
  {
   swap(*this,x);
  }
References swap().
seq() [16/27]
seq::seq () inline
Definition at line 616 of file explore.cc.
  {
  }
seq() [17/27]
seq::seq (const seq & x) inline
Definition at line 619 of file explore.cc.
  {
   assign(*this,x);
  }
References assign().
seq() [18/27]
seq::seq (seq && x) inline
Definition at line 623 of file explore.cc.
  {
   swap(*this,x);
  }
References swap().
seq() [19/27]
seq::seq () inline
Definition at line 620 of file normalize.cc.
  {
  }
seq() [20/27]
seq::seq (const seq & x) inline
Definition at line 623 of file normalize.cc.
  {
   assign(*this,x);
  }
References assign().
seq() [21/27]
seq::seq (seq && x) inline
Definition at line 627 of file normalize.cc.
  {
   swap(*this,x);
  }
References swap().
seq() [22/27]
seq::seq () inline
Definition at line 631 of file serve.cc.
  {
  }
seq() [23/27]
seq::seq (const seq & x) inline
Definition at line 634 of file serve.cc.
  {
   assign(*this,x);
  }
References assign().
seq() [24/27]
seq::seq (seq && x) inline
Definition at line 638 of file serve.cc.
  {
   swap(*this,x);
  }
References swap().
seq() [25/27]
seq::seq () inline
Definition at line 616 of file test.cc.
  {
  }
seq() [26/27]
seq::seq (const seq & x) inline
Definition at line 619 of file test.cc.
  {
   assign(*this,x);
  }
References assign().
seq() [27/27]
seq::seq (seq && x) inline
Definition at line 623 of file test.cc.
  {
   swap(*this,x);
  }
References swap().
Member Function Documentation
operator=() [1/18]
void seq::operator= (const seq & x) inline
Definition at line 626 of file backup.cc.
  {
   assign(*this,x);
  }
References assign().
operator=() [2/18]
void seq::operator= (const seq & x) inline
Definition at line 647 of file build.cc.
  {
   assign(*this,x);
  }
References assign().
operator=() [3/18]
void seq::operator= (const seq & x) inline
Definition at line 627 of file commit.cc.
  {
   assign(*this,x);
  }
References assign().
operator=() [4/18]
void seq::operator= (const seq & x) inline
Definition at line 626 of file convert.cc.
  {
   assign(*this,x);
  }
References assign().
operator=() [5/18]
void seq::operator= (const seq & x) inline
Definition at line 637 of file download.cc.
  {
   assign(*this,x);
  }
References assign().
operator=() [6/18]
void seq::operator= (const seq & x) inline
Definition at line 627 of file explore.cc.
  {
   assign(*this,x);
  }
References assign().
operator=() [7/18]
void seq::operator= (const seq & x) inline
Definition at line 631 of file normalize.cc.
  {
   assign(*this,x);
  }
References assign().
operator=() [8/18]
void seq::operator= (const seq & x) inline
Definition at line 642 of file serve.cc.
  {
   assign(*this,x);
  }
References assign().
operator=() [9/18]
void seq::operator= (const seq & x) inline
Definition at line 627 of file test.cc.
  {
   assign(*this,x);
  }
References assign().
operator=() [10/18]
void seq::operator= (seq && x) inline
Definition at line 630 of file backup.cc.
  {
   swap(*this,x);
  }
References swap().
operator=() [11/18]
void seq::operator= (seq && x) inline
Definition at line 651 of file build.cc.
  {
   swap(*this,x);
  }
References swap().
operator=() [12/18]
void seq::operator= (seq && x) inline
Definition at line 631 of file commit.cc.
  {
   swap(*this,x);
  }
References swap().
operator=() [13/18]
void seq::operator= (seq && x) inline
Definition at line 630 of file convert.cc.
  {
   swap(*this,x);
  }
References swap().
operator=() [14/18]
void seq::operator= (seq && x) inline
Definition at line 641 of file download.cc.
  {
   swap(*this,x);
  }
References swap().
operator=() [15/18]
void seq::operator= (seq && x) inline
Definition at line 631 of file explore.cc.
  {
   swap(*this,x);
  }
References swap().
operator=() [16/18]
void seq::operator= (seq && x) inline
Definition at line 635 of file normalize.cc.
  {
   swap(*this,x);
  }
References swap().
operator=() [17/18]
void seq::operator= (seq && x) inline
Definition at line 646 of file serve.cc.
  {
   swap(*this,x);
  }
References swap().
operator=() [18/18]
void seq::operator= (seq && x) inline
Definition at line 631 of file test.cc.
  {
   swap(*this,x);
  }
References swap().
Member Data Documentation
text
txt seq::text
Definition at line 614 of file backup.cc.
Referenced by append(), assign(), at(), back(), clear(), contain(), count(), drop_l(), drop_r(), front(), is_empty(), prepend(), print(), push(), remove(), shuffle(), slice(), slice_l(), slice_r(), swap(), to_mem(), and unshift().
The documentation for this struct was generated from the following files:
code/backup.cc
code/build.cc
code/commit.cc
code/convert.cc
code/download.cc
code/explore.cc
code/normalize.cc
code/serve.cc
code/test.cc